### ISSUE TITLE
Powerline glyphs please?

### ISSUE THREAD

**Issue by tomByrer** [chrissimpkins/Hack#1]
https://github.com/powerline/powerline#vim-statusline

BTW, thanks for building the WOFF[2] versions, & lower-casing the web names!

**Comment by chrissimpkins** [comment]
I was actually just looking into this yesterday.  The power line documentation doesn't detail the glyphs that are required and how the fonts are modified to support this.  Do you happen to know or have a reference?  

I'd be happy to do this.

**Comment by tomByrer** [comment]
I would simply open one of the other OSS PowerLine fonts, copy/paste, then tweak.
I think one has a glyphs listed.  (Sorry on phone)

**Comment by chrissimpkins** [comment]
It doesn't seem to be quite that easy to merge in FontForge.  The glyphs are separated over hundreds of different character positions in the editor and if you select all and paste the glyphs in, it will overwrite the existing ones in this font.  I found an .otf file of the Powerline specific glyphs.  I will look into how they map them and try to create a modified version of Hack that works.  Will let you know if I come up with something that seems to work for me.  From what I gather after reading a bit about this, it can be monitor specific.  Some users have complained about spacing issues in Retina/HD vs. non-Retina/HD displays.  

You willing to help me test this a bit if I come up with something that appears to work?

**Comment by tomByrer** [comment]
Sure I can help out as I can.

**Comment by chrissimpkins** [comment]
excellent thanks much.   looking into it this weekend.  did some more poking around in the powerline repos today

**Comment by chrissimpkins** [comment]
Script to automate this: 

https://github.com/powerline/fontpatcher/blob/develop/scripts/powerline-fontpatcher

**Comment by chrissimpkins** [comment]
Will try to push a file that you can test this weekend

**Comment by chrissimpkins** [comment]
Here is a test Powerline version.  It has all of the Powerline glyphs.  Let me know how it works on your system.

https://github.com/chrissimpkins/Hack/raw/powerline/build/ttf/Hack-Regular-Powerline.ttf

**Comment by chrissimpkins** [comment]
Actually give this one a try instead.  The ttf seems to have an error. 

https://github.com/chrissimpkins/Hack/raw/powerline/build/otf/Hack-Regular-Powerline.otf

**Comment by tomByrer** [comment]
Will be a few days before I get to test fully; long days.
Sorry!

**Comment by chrissimpkins** [comment]
No worries!  Let me know when you have a chance.  I am updating all of the font files with a number of changes and will add the Powerline glyphs if this works.

**Comment by chrissimpkins** [comment]
The new release files for the regular version of the font include the Powerline glyphs.  I haven't added this to the changelog until it is tested.  Let me know if either the ttf or otf file work in your setup.  Thanks much.

**Comment by chrissimpkins** [comment]
Mind letting me know if you are still interested in this issue?  I will close it if it is no longer necessary.  Thanks much.

**Comment by chrissimpkins** [comment]
See #13 for current test release that includes the Powerline glyphs.
