### ISSUE TITLE
"<" and ">" looks edgy

### ISSUE THREAD

**Issue by bremenpl** [chrissimpkins/Hack#101]
Hello there,
First of all I would like to thank the authors for a great font. Since I found it I am using it everywhere, thank you.

This is probably not a big thing, but just something to consider. I have noticed that "<" and ">" signs look a lot more edgy than the rest of the signs. I can see this in Notepad++ and Eclipse (A lot more visible in the second one).

![signs](https://cloud.githubusercontent.com/assets/1183500/9849316/0c10d28a-5aea-11e5-8532-dcea8e55767f.png)

Maybe this is just me but I think that those signs stand out. Looking forward to some feedback.
(I am using windows 7)

**Comment by RasPat1** [comment]
+1 
Using Hack on intellij idea and angle brackets are a bit pixelated. Looks pretty good on a retina screen (15.4-inch (2880 x 1800)) but not great on a 27-inch (2560 x 1440) thunderbolt display.  Using version 1.3 I believe.
This screenshot is probably useless but here it is anyways: 
![image](https://cloud.githubusercontent.com/assets/2310588/9856996/085368d2-5ae6-11e5-82eb-64ab00f6b38b.png)

**Comment by chrissimpkins** [comment]
@bremenpl are you using the otf or ttf files? Which version?

**Comment by chrissimpkins** [comment]
@RasPat1 we've had some problems with the renderer in the JetBrains editors.  Does this happen in your terminal or other editors on OS X?

**Comment by bremenpl** [comment]
Hack-v2_010-ttf. Thank you for feedback.

**Comment by chrissimpkins** [comment]
@bremenpl mind trying the new v2.013 build?  It is the current release linked on the README.

**Comment by bremenpl** [comment]
Sure, ill give it a spin first thing in the morning.

**Comment by bremenpl** [comment]
Btw, do I need to reinstall the old font 1st or will windows just let me 
update it in a clean way?

**Comment by chrissimpkins** [comment]
I am not certain of the correct answer to that but when I test on windows I always delete the old files before installing the new ones.

**Comment by bremenpl** [comment]
Alright, thank you.

**Comment by RasPat1** [comment]
@chrissimpkins 
Yeah looks a bit janky in Sublime as well. (only other place i'm using it)

**Comment by bremenpl** [comment]
@chrissimpkins I have installed the neverst version, but the brackets look the same.

**Comment by chrissimpkins** [comment]
What text sizes are you using in your editors and does this occur when you change up and down by a text size or two?  The glyphs are drawn with straight lines.  This is going to be an issue with the way that they are rendered to fit the pixel box on different platforms (and in some cases this may even differ between editors).  This may be an antialiasing issue on your systems.  On the Windows side of things, is there a way to change the antialiasing settings in your editor to see if that helps?

On OS X, try to add [subpixel antialiasing to the Sublime Text settings](http://www.sublimetext.com/forum/viewtopic.php?f=3&t=8259) to see if that helps to smooth the lines in those characters.

Let me know if either of these address the issue.

**Comment by bremenpl** [comment]
I have tried changing the rendering engine in windows generaly, to be 
more like OS X or Linux with 3rd party tools but that didnt work out 
well. I have no build in way of changing antialiasing in the editors. In 
Microsoft Word for example, it looks a bit better as it uses hes own 
rendering engine. Changing the font size doesnt help, I have tested this 
in several code editors (also in visual studio it looks edgy as well).

**Comment by chrissimpkins** [comment]
And ClearType is turned on?

**Comment by bremenpl** [comment]
Yes.

**Comment by chrissimpkins** [comment]
I will take a look in Windows and see if there are any other optimizations that I can come up with.  Is this a problem in other fonts or only something you noticed here?

**Comment by bremenpl** [comment]
I have used consolas before and I would say it was less sharp:
![brackets](https://cloud.githubusercontent.com/assets/1183500/9875931/8499ce5a-5bb2-11e5-8d70-978bad8e367d.png)

**Comment by chrissimpkins** [comment]
Look like wider shapes in the vertical dimension.  Let me check this across Linux platforms as well.  It is possible that we may need to slightly adjust the shapes so that they render better.

**Comment by manuel-uberti** [comment]
I don't think this would be of any help, but ```<``` and ```>``` looks fine on my Emacs running on Debian unstable.

**Comment by chrissimpkins** [comment]
@manuel-uberti thanks for that input.  this is definitely a platform/editor dependent issue.  they look ok for me as well.  I have had some requests to increase vertical size of these characters.  Any opinion about the design itself as we address these issues?

**Comment by bremenpl** [comment]
In my opinion the design in overal is great.

**Comment by chrissimpkins** [comment]
@bremenpl thank you very much Łukasz.  I really appreciate that.  Do you happen to have any thoughts about the `<` and `>` glyphs in the body of source where you use these?

**Comment by bremenpl** [comment]
Maybe like you said yourselve- if the brackets were a bit tighter, the 
angle would be smaller and they would look less pixely like in consolas?

**Comment by chrissimpkins** [comment]
Sounds good.  I take it you don’t have a strong opinion about the shape and just want them to appear better as is.  Will experiment a bit on Windows and see if I can find any optimizations.  Will let you know if I come across anything.  


Any other Windows or OS X users out there who have a different experience and any thoughts, please feel free to chime in.


—
Chris

**Comment by manuel-uberti** [comment]
About the design: I just can say Hack is the ONLY font able to drive me away from Source Code Pro. So thanks a lot for your efforts.

**Comment by bremenpl** [comment]
I have also switched to hack from source code pro.

**Comment by chrissimpkins** [comment]
@manuel-uberti I really appreciate that feedback.  This is definitely a group effort and we make progress because of input and contributions from those who find all of its ugly, and sometime subtle, blemishes.  It is impossible to create a testing mechanism that covers the font renderers on all platforms across all text editors on each platform (which I have come to learn can differ within the same platform) and unfortunately it gets released into the wild where testing happens.  All of this feedback is tremendously useful and important.

**Comment by manuel-uberti** [comment]
@chrissimpkins I mainly use the font in Emacs (which is where I spend most of my time anyway), but if you need me to test the font in other applications, feel free to ask.

**Comment by chrissimpkins** [comment]
@manuel-uberti Thanks Manuel.  We are actually actively working on rendering in the bold set based on a problem that was raised on the Debian platform.  There appears to be a hinting problem with the points on the lowercase i and j that showed up on that platform.  It seems to be fixed and we will have a new build out later this week.  Incidentally, the thread was generated to create a new Debian package for the font so that it can be released through your package manager.  If you are interested in helping to test on that platform and optimize it for other Debian users, the thread is #84 and @legovini is the contact.  A new test build is available in that thread if you want to give it a try.  I suspect that we may need to work on diacritics in the expanded character set a bit and haven't looked at the rendering of these characters in detail at this stage.  Definitely test drive it in your use scenarios and let me know about any problems.

Thanks!

**Comment by chrissimpkins** [comment]
The Eclipse and IntelliJ editors are both based on a Java text renderer. I think that this is where the problem lies.

For Eclipse, I can't find much information about how to change the antialiasing settings but there is a set of images in a [bug report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=276682) that replicate what you are seeing with the angled lines here.  

[Antialiasing Not Working Image](https://bugs.eclipse.org/bugs/attachment.cgi?id=137350)

[Antialiasing Working Image](https://bugs.eclipse.org/bugs/attachment.cgi?id=137349)

It looks like you may need to address this with the Eclipse team if you have your text rendering settings set to antialias the fonts.

For IntelliJ, I came across this [Superuser post](http://superuser.com/questions/614960/how-to-fix-font-anti-aliasing-in-intellij-idea-when-using-high-dpi) that may be of use.

I don't believe that Emacs uses Java to render fonts so these issues would not be expected in that editor.

Let me know if you make any progress with this.

**Comment by bremenpl** [comment]
I think notepad++ is written in c++ and it also has this issue. I 
will.however try to get more info about antialias in eclipse.

**Comment by chrissimpkins** [comment]
This help with Notepad++?  Not sure if this is still relevant in Win 10. 

http://superuser.com/questions/183215/how-to-turn-on-off-fonts-anti-aliasing-in-notepad

**Comment by chrissimpkins** [comment]
Here is some more info on Notepad++ if you are not using the current release version: 

https://github.com/notepad-plus-plus/notepad-plus-plus/pull/116#issuecomment-113627796

**Comment by bremenpl** [comment]
Well, the point is that the brackets look the same in all windows 
editors i would say (apart from those which have own rendering engine 
like microsoft word). I have tested this in:

- Eclipse
- Notepad++
- Visual Studio
- Netbeans
- Qt Creator
- MPLAB X IDE
- Atmel Studio

Maybe tighting the brackets is the way out?

**Comment by chrissimpkins** [comment]
Mind looking at some of the other angled strokes in the set?  For example the %.  

I suspect that this is a broader issue for you.

**Comment by bremenpl** [comment]
Yes, "%" is also edgy. "\" and "/" is still fine...

**Comment by alphapapa** [comment]
Just my two cents:

- I use Emacs on Debian and Ubuntu, and I just ran through several fonts (list below), and I would say that Hack's `<>` glyphs render just as clearly as those fonts' do for me.
```
Fantasque Sans Mono
DejaVu Sans Mono
Ubuntu Mono
Droid Sans Mono
Input Mono Narrow
Input Sans Condensed
Consolas
Inconsolata
Anonymous Pro
Liberation Mono
Fira Mono
Hack
```
-  I am happy with the height of the `<>`.  I don't think they need to be made taller.

**Comment by chrissimpkins** [comment]
@alphapapa thank you very much for this feedback.  Any special antialiasing or hinting settings on Debian?

**Comment by bremenpl** [comment]
On a linux system I am using (linux mint) the brackets look as good as you 
are describing. I havent said it doesnt.

**Comment by alphapapa** [comment]
@chrissimpkins And thank you for Hack!  :dancer: 

> Any special antialiasing or hinting settings on Debian?

I'm sorry, it just hit me, I haven't installed Hack on my Debian system yet (too bad it's not packaged in unstable yet), so I've actually been using DejaVu Sans Mono on it.

If it helps, on my Ubuntu system, I'm using KDE4 with "slight" hinting and "RGB" antialiasing.  Looks good here.  :)

**Comment by bremenpl** [comment]
@chrissimpkins here is a screen from Linux Mint. Antialiasing is a lot better there. Only on windows it doesnt look as good:
![zrzut_ekranu-c-c - ovencore-src-ovencore cpp - eclipse](https://cloud.githubusercontent.com/assets/1183500/9927405/a3776216-5d1e-11e5-8153-69ebe4be77db.png)

Here is Windows 8.1 (So its not a windows 7 issue only):
![nowy obraz mapy bitowej](https://cloud.githubusercontent.com/assets/1183500/9927610/719fb606-5d20-11e5-8500-734cb50605c6.jpg)

**Comment by chrissimpkins** [comment]
@bremenpl I completely understand and recognize your issue.  I am not dismissing it.  I just don't know that there is a way to design around it.  Those glyphs must have angled lines and angled lines do not appear to render well on your system.  This is a complex, multifactorial issue that involves your hardware (display - higher pixel density displays will likely render smoother lines for you on your current platform) and your software (choices made in each OS about type rendering - including approaches to hinting and antialiasing, the renderer that is used, and choices that we make in the typeface software itself).   As you can see from a majority of the large number of issue reports, different combinations of these factors that affect the appearance of the typeface lead to different experiences with the face.  If you can show me glyphs from other typefaces that do render without that jagged appearance, I would be happy to take this into consideration with the design but as you've seen in the comments above, every design change involves other potential consequences.  If I change the shape of the glyphs to address a platform/editor/renderer/display/typeface specific combination this can lead to a change in something about the face that others like and that does display well in their own combination of these same factors.  It's a bind that we are in on the screen in the current era of monitors that are in wide use.

**Comment by bremenpl** [comment]
@chrissimpkins I understand.I gues that this font is just optimised for Linux and OS X. If thats the majority of users then I gues thats alright to adress them. About the fonts, here is some comparison on Windows 7:

![fonts](https://cloud.githubusercontent.com/assets/1183500/9933253/2030826c-5d4a-11e5-84df-9f729df2d8c1.png)

Consolas looks best (I was using before Hack, as SourceCode Pro wasnt able to beat it). Second one is Hack and third one is oldschool Courier New.

**Comment by chrissimpkins** [comment]
There is definitely no intent to exclude Windows users and my understanding is that there are Windows users out there who are using it.  We are addressing a number of issues that have come up on the Windows platform in other issue reports.  I don't routinely develop on Windows but I do test font installs and review changes to the face in Sublime Text 3 on Windows 10.  With the `directwrite` setting enabled in Sublime Text, to my eye, it renders well.  I would have to check the font size that I used, but I generally cycle through a range of sizes to confirm that nothing dramatic emerges.  As noted above, it really depends on a number of factors.

**Comment by bremenpl** [comment]
I understand. Well anyways, I will use the font no matter this as its 
still great work. Thank you.

**Comment by chrissimpkins** [comment]
Will close this issue.  Please feel free to reopen if you have further suggestions about how to address this.
