### ISSUE TITLE
Request for 0x1A4 [CAPITAL P WITH HOOK] to be added

### ISSUE THREAD

**Issue by doubleagent** [chrissimpkins/Hack#105]
"Capital P with a hook"

This character is used by Emacs 'clojure-mode' to "fancify" code.  See [here](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/clojure#pretty-symbols) for details.

**Comment by chrissimpkins** [comment]
Noted.  Thanks for the suggestion.  I will work it in.

**Comment by chrissimpkins** [comment]
For my reference: U+01A4

**Comment by chrissimpkins** [comment]
@jublo started work on these glyphs.  Any special spacing issues with this glyph (and its position relative to other glyphs) in emacs?

Will see if we can incorporate this into a development build that you can try soon.  Will update here when available.

**Comment by doubleagent** [comment]
Awesome. I'm not aware of any special issues in Emacs, but I'm also no expert.

**Comment by chrissimpkins** [comment]
Example of the glyph in DejaVu Sans:

![p-hook](https://cloud.githubusercontent.com/assets/4249591/10182406/ca7c371a-66f1-11e5-8280-8f8375b5bf39.png)

**Comment by jublo** [comment]
Suggestion:

<img width="389" alt="bildschirmfoto 2015-10-03 um 20 43 03" src="https://cloud.githubusercontent.com/assets/6348321/10264547/5c6ecea6-6a0f-11e5-9afe-25c156b716bd.png">

**Comment by jublo** [comment]
Oblique suggestion:

<img width="447" alt="bildschirmfoto 2015-10-03 um 20 53 04" src="https://cloud.githubusercontent.com/assets/6348321/10264594/d6401086-6a10-11e5-8330-4893e704eb7a.png">

**Comment by jublo** [comment]
Bold variants:

<img width="377" alt="bildschirmfoto 2015-10-03 um 21 02 30" src="https://cloud.githubusercontent.com/assets/6348321/10264651/abb39c78-6a12-11e5-8fdf-ec0772ed9ffd.png">
<img width="444" alt="bildschirmfoto 2015-10-03 um 21 04 07" src="https://cloud.githubusercontent.com/assets/6348321/10264652/abd63c9c-6a12-11e5-9046-a16bf297f691.png">

**Comment by jublo** [comment]
See https://github.com/jublonet/Hack/commit/dfb17e99d3b40a2b8cf8eda1bb9186c3d2634fdf.

**Comment by chrissimpkins** [comment]
These look great @jublo .  Nice work on them.  @doubleagent Daniel, can you link to the current page that shows how these glyphs are used?  The original link in your post no longer links to an active site.  We will test these characters in the context that they are used before we build them for you to try.

**Comment by doubleagent** [comment]
They restructured the repository a bit.  Page can now be found [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/clojure#pretty-symbols).

**Comment by chrissimpkins** [comment]
This glyph is available for testing in the new v2.016 build.  You can download the files here:

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by doubleagent** [comment]
Awesome! I'll give it a shot first thing tomorrow.

**Comment by chrissimpkins** [comment]
@doubleagent great! let us know if you see any problems.  We intend to include this in the next release

**Comment by doubleagent** [comment]
Looks good so far.  Haven't seen any problems yet.

**Comment by chrissimpkins** [comment]
That's great to hear.  If you have a chance (purely out of my own curiosity) will you post a screenshot that shows how it is being used?  I haven't come across this glyph in the past.

**Comment by doubleagent** [comment]
Here's a snippet from a work project which has a dense grouping of some of these characters.

![image](https://cloud.githubusercontent.com/assets/56522/10431134/f7256aa8-70c8-11e5-9370-4fdd18dababb.png)

**Comment by chrissimpkins** [comment]
OK I see.  The wide side bearings on the parentheses seem to be helping there as well.  Thanks for pushing that.

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release
