### ISSUE TITLE
“Look ma’, it’s animated!” — or why do my dashes move under the cursor?

### ISSUE THREAD

**Issue by alerque** [chrissimpkins/Hack#107]
So here's one for you (OTF, Font version 2.013, Linux, FT 2.6, Termite VTE3-ng based terminal):

![selection_058](https://cloud.githubusercontent.com/assets/173595/9936054/b83a69c0-5d62-11e5-883f-aa92893ee487.png)

Note the two dashes as part of the GNU flavored long option syntax are at different heights. Both are the same font, size etc. But when the (block) cursor passes over it it reverses the foreground color and changes the background. At first I though this was screwing with the anti aliasing and making it appear to move, but it turns out it's switching to italics. This is a subtle change for most letters but when it's a dash and the glyph jumps up and down it's rather jarring.

I can see why italics might render at a different height, but given that this is a source code font I think the dashes need to stay at the same height.

Also notable, the bold variant seems to be the same as the italic an the cursor doesn't produce any motion when going over bolded dashes.

**Comment by chrissimpkins** [comment]
Interesting. There are a few other issue reports about one pixel offsets between sets.  To date, these have been between the regular and bold sets.  Let me look at the actual position of the glyphs in the regular and italic sets to see if it is positioned at a different vertical level.

**Comment by chrissimpkins** [comment]
You win the issue report title of the year award by the way...

**Comment by alphapapa** [comment]
Definitely LWN-worthy.  :D

**Comment by chrissimpkins** [comment]
I am hoping that the new vertical metrics changes in the v2.014 test build will address this issue.  I have not built otf files yet, but if you are interested in trying the ttf files they are available in #111

**Comment by chrissimpkins** [comment]
Identified the problem.  Will try to work a fix in to the upcoming release.

**Comment by chrissimpkins** [comment]
Fixed this today.  Will be included in the next release.

**Comment by chrissimpkins** [comment]
Fixed in v2.015 release.  Available now.  Will close this issue.  Feel free to reopen if you have any problems with it.
