### ISSUE TITLE
New v2.014 Test Build (ttf) Available [Vertical Metrics Changes, Character Updates, Alignment Changes]

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#111]
A new ttf file build is available for testing.  This build addresses a number of issue reports and includes the following changes:

- Updated vertical metrics
    - attempt to address bold vs. regular set vertical offset issues, numerous issue reports about slight, incorrect vertical offsets across various editors
    - tighter line spacing c/w Bitstream Vera Sans Mono, DejaVu Sans Mono, and Menlo vertical metrics
- Changed vertical position of the asterisk (lower, closer to center)
- Updated alignment of dieresis marks (addresses incorrect position of lower case u dieresis)
- New design for the ascii tilde glyph.  Taller glyph with larger curves, should significantly improve legibility at smaller text sizes.
- Slightly wider and taller underscore glyphs that are now properly centered and moved closer to the baseline.
- Improvements to the ttf build instruction sets.  Addresses incorrect lowercase j and i point alignment in bold set at some point sizes (in the commonly used text size range for source)

This build introduces some fairly significant changes in the design.  Comments would be greatly appreciated!

### Download Link

[Hack v2.014 tar.gz archive](https://github.com/chrissimpkins/Hack/blob/vertical-metrics/build/test_builds/2_014/2_014.tar.gz?raw=true)

**Comment by tbrisbane** [comment]
I've just tested this build in both IntelliJ and PyCharm (both set to 12pt, with a line spacing of 1.0), with the following results:

- Underscores are no longer disappearing, as they appear within the correct line in both IDEs (however IntelliJ has them positioned 1px higher than PyCharm)
- PyCharm still has issues with some characters' tails disappearing ('p', 'y', 'g', 'j', etc), however, strangely, these issues are NOT present in IntelliJ

**Comment by theckman** [comment]
The glyphs seem a bit off with this one, also the line height appears to be much tighter. Not sure if the latter is intentional.

![High Arrows 2.0.14](https://cloud.githubusercontent.com/assets/787332/9985524/5097869a-5fe2-11e5-9ffb-05aa6f75ac21.png)

**Comment by lluixhi** [comment]
The problems I had were fixed. The tilde looks much better, as do the underscores.
I don't have the issues @theckman is experiencing, though I agree that the line height is much tighter (which isn't really a problem, IMO. Some people might think it feels cramped though. -- I guess that depends on #28.)

Due to the change in the tilde, the font looks *even closer* to Menlo/Meslo -- I don't know whether this is a good/bad thing. Just pointing it out.

**Comment by Xenopathic** [comment]
I'm not convinced I like the new tilde, but I agree the old one was too line-like. Perhaps there's a reasonable middle ground, where it doesn't quite stick out so much yet is still easily recognisable?

Here are some screenshots from Arch Linux XFCE4 Terminal:

![screenshot_2015-09-21_09-45-51](https://cloud.githubusercontent.com/assets/2016878/9988195/5b27ab6c-6046-11e5-8dfa-958e31768a66.png)
![screenshot_2015-09-21_09-46-10](https://cloud.githubusercontent.com/assets/2016878/9988196/5b284dd8-6046-11e5-809b-73332911dee6.png)

Notice there is still a little bit of upper overhang (but near-invisible), and the Powerline glyphs seem to still be offset from centre, upwards.

**Comment by chrissimpkins** [comment]
@theckman yes, the line height changes are intentional and were an attempt to address a number of vertical alignment issues between sets.  We can address these Powerline issues in the original issue report.

@lluixhi You are correct.  The vertical metrics are now the same as DejaVu Sans Mono, Bitstream Vera Sans Mono, Menlo, and (I believe) Meslo.  This is tighter than the last version of Hack.  Many wanted this change, but the intent was to address a number of one pixel vertical alignment differences that were found between sets.  I took a look at a number of tildes and that shape (wide curves, tall ends) tends to render best at small text sizes.

@Xenopathic thanks for that feedback.  What text size are you using there?

**Comment by Xenopathic** [comment]
@chrissimpkins Oh, that's size 12 font.

**Comment by chrissimpkins** [comment]
@Xenopathic If it's not too much trouble, do you mind taking it down to 8 or 9 and let me know how the tilde looks in those ranges?  I've worked with the new builds on OS X so far and haven't had a chance to play with it on Linux or Windows yet.  It is definitely going to appear more 'curvy' than the old style and I think that this will allow for some additional pixels to differentiate it from a dash at small text sizes.

**Comment by Xenopathic** [comment]
The tilde is still definitely recognisable, which is awesome. Perhaps I just need to get used to it :smile:

Unfortunately, at the smaller font sizes the Powerline symbol misalignment becomes more visible:

![screenshot_2015-09-21_12-01-35](https://cloud.githubusercontent.com/assets/2016878/9990388/bec531a0-6058-11e5-806d-25f63f60ab4b.png)

**Comment by chrissimpkins** [comment]
@Xenopathic we will tackle that issue next.  I wanted to eliminate the vertical metrics issues that were mounting.   There are a several alignment issues that we can address with a stable set of vertical metrics.  I will work with the Powerline patch script this week as noted in that thread.

**Comment by chrissimpkins** [comment]
> PyCharm still has issues with some characters' tails disappearing ('p', 'y', 'g', 'j', etc), however, strangely, these issues are NOT present in IntelliJ

@tbrisbane let's discuss this back in the original thread.  Sorry to hear that.  I thought that this would take care of the problem.

**Comment by chrissimpkins** [comment]
@theckman Thoughts on the current line height?  I believe that you were interested in tighter spacing in the line height variants thread.

**Comment by lrvick** [comment]
This fixed all my urxvt issues. All glyphs line up like I expect now.

**Comment by chrissimpkins** [comment]
@lrvick great! was this in an open issue report?

**Comment by chrissimpkins** [comment]
The changes included in development build v2.014 were included in the latest release build v2.015.  Now available.  Closing this issue report.
