### ISSUE TITLE
UFO source to release build tool chain

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#113]
Work is underway to convert the build process to a scripted tool chain from UFO source to the final release ttf, otf, svg, eot, web-ttf, woff, & woff2 files.  This is in part to ease the build/hinting+instructions/subsetting process and in part to satisfy requests by Linux distro packagers (and other software font redistribution packagers) for redistribution of the fonts as source rather than as release binaries.

**Comment by wxl** [comment]
Contributions to go with it might be nice, too ;)

**Comment by chrissimpkins** [comment]
interested?

**Comment by wxl** [comment]
shoot, sorry, i meant a contribution *guide*. i gather that you guys mostly use fontlab, so perhaps i could add in notes for linux folks. i got a mac laying around, too. i think both run fontforge, so i could base it on that.

**Comment by chrissimpkins** [comment]
using a combination of Glyphs and FontLab Studio.  Interested in discussing further?

**Comment by wxl** [comment]
i am not a windows user, but i'd be happy to help translate to linux XD

**Comment by chrissimpkins** [comment]
shoot me an email at address on repo profile and we can talk about it.

**Comment by chrissimpkins** [comment]
We’re making progress with the build toolchain and font build testing tools.  More news coming soon.
