### ISSUE TITLE
middle dot (interpunct) in ecplise dissapears under some conditions

### ISSUE THREAD

**Issue by alexirger** [chrissimpkins/Hack#115]
Hi,
Thanks for the great font!

I use eclipse and I noticed some troubles with an interpunct (middle dot) sign eclipse uses to visualize whitespace:

Eclipse have a "transparency level" configuration option for whitespace characters. If this option is set to max (255), interpuct renders properly: 
![capture](https://cloud.githubusercontent.com/assets/14805015/10072098/98ac6864-62c7-11e5-9826-8f7ea5e9c282.PNG)
Any other value - interpunct is not renderable:
![capture1](https://cloud.githubusercontent.com/assets/14805015/10072109/abbd080a-62c7-11e5-8ac0-a0a222ebf2d2.PNG)

Problem seems to be present only in regular font, bold renders fine (hovewer didn't check italic):
![capture2](https://cloud.githubusercontent.com/assets/14805015/10072127/c7264f48-62c7-11e5-983d-825bb4ebbc88.PNG)

Problem seems to be not present for other special characters (paragraph glyph and such)

**Comment by chrissimpkins** [comment]
this is with the current release version of Hack (v2.013)?

**Comment by chrissimpkins** [comment]
and can you show me screenshots of other fonts where this feature is working?   I wonder how they are rendering transparency in the text?

**Comment by alexirger** [comment]
Yes, this is current release. As I already mentioned, Hack Bold is fine, and this is for example, Consolas Regular: 
with transparecy: 
![capture3](https://cloud.githubusercontent.com/assets/14805015/10072500/ef86ae30-62ca-11e5-9f3e-e28cf293cf57.PNG)
and without:
![capture4](https://cloud.githubusercontent.com/assets/14805015/10072511/081504c4-62cb-11e5-9ba5-c7a768a148ca.PNG)

Thanks for the quick response.

**Comment by chrissimpkins** [comment]
That's odd.  It looks like all that it is doing is changing the color of the pixels to more closely match the background (as it should do with transparency...).  I do not know why that would prevent display of the glyph.  If you highlight those areas, do you see the middle dot points (are they preserved in Consolas and do they show up in Hack)?

**Comment by alexirger** [comment]
No even with biggest font size possible (72) nothing is visible on Hack Regular. Just set  transparency to  254 - and glyph completely dissapears.  
![capture5](https://cloud.githubusercontent.com/assets/14805015/10075230/51e8e20c-62dd-11e5-8ac5-67b04b4c89f0.PNG)
![capture6](https://cloud.githubusercontent.com/assets/14805015/10075236/53950856-62dd-11e5-9d85-d7d28cfb22a7.PNG)

**Comment by alexirger** [comment]
Consolas: 
![capture7](https://cloud.githubusercontent.com/assets/14805015/10075314/c74e677e-62dd-11e5-972c-4c110cb79e91.PNG)

**Comment by alexirger** [comment]
Hack Bold: 
![capture8](https://cloud.githubusercontent.com/assets/14805015/10075364/feb94404-62dd-11e5-9c67-2e56a6655a11.PNG)

**Comment by chrissimpkins** [comment]
Anyone out there seeing this in other editors?  

We have a number people who have reported space highlighting issues with earlier versions across a number of editors.  These were corrected with the most recent release build.  If we don't hear about this in other editors, would you be willing to submit an issue report with Eclipse so that we can get more information about their font renderer and how this transparency display is being rendered?  I am happy to change anything on my end to fix this, but I honestly don't know where this would originate.  I think we need additional information from the Eclipse team.

**Comment by chrissimpkins** [comment]
Are you willing to submit this as an issue report on the Eclipse issue tracker to see what they have to say about it?
