### ISSUE TITLE
Format for linux console (tty)?

### ISSUE THREAD

**Issue by rfmae** [chrissimpkins/Hack#119]
I am using Hack in Slackware. I like it alot and would also like to use Hack as my console (not X) font. Do you plan to release Hack in a format that is compatible with linux consoles?

**Comment by chrissimpkins** [comment]
Thanks for the feedback about Hack.  I greatly appreciate it. 

We do not currently provide an 'official' release of PSF fonts but they should be relatively straightforward to generate.

The build chain for the Linux console PSF file format is as follows:

OTF to BDF to PSF

and you can use `otf2bdf` + `bdf2psf` with our Hack-*.otf file releases to get there.  I have no experience with how these tools alter the lines and hinting through this translation process.  I would be interested to hear back from you about how they appear in the new build format.

I came across this in the [Arch documentation](https://wiki.archlinux.org/index.php/Fonts#Console_fonts), perhaps something that you already know but it is news to me:

>The Linux console uses UTF-8 encoding by default, but because the standard VGA-compatible framebuffer is used, a console font is limited to either a standard 256, or 512 glyphs. If the font has more than 256 glyphs, the number of colours is reduced from 16 to 8. In order to assign correct symbol to be displayed to the given Unicode value, a special translation map, often called unimap, is needed. Nowadays most of the console fonts have the unimap built-in, historically it had to be loaded separately. 

I do not know how the above tools implement (or if they do) the unicode mapping indicated there.

Also, please note that the license requires a change of font name for translations to new font formats such as this.  If you intend to create a fork for redistribution to other Linux users (which I would highly recommend if this works out for you - I would be happy to point future users to it with similar questions) and I can help in any way, please let me know.
