### ISSUE TITLE
Line height set solid with v2.015

### ISSUE THREAD

**Issue by giorgio-v** [chrissimpkins/Hack#121]
It seems that, starting with v2.015 line height is set solid. I get that you should be able to control this in your editor, but sometimes it is not possible. For example, in Mail.app on Mac OS X, you can choose Hack as a message font, but you cannot set the line height, AFAICS.

**Comment by chrissimpkins** [comment]
> line height is set solid.
What do you mean by this, that you cannot alter the line spacing whereas you could in previous versions?  This should not be the case.  It will rely on an application that supports this.

**Comment by giorgio-v** [comment]
Yeah, but it seems that the previous version was different in this regard. 

Maybe I misremember? 

--
Giorgio Valoti

**Comment by chrissimpkins** [comment]
You are absolutely correct. The line spacing did decrease in the most recent version.  This change addressed a number of issues (both requests for decrease in spacing as well as misalignment issues with vertically aligned glyphs like the box glyphs).  There is an open issue report for different (including wider) line spacing builds if you are interested in following.

**Comment by chrissimpkins** [comment]
#28

**Comment by giorgio-v** [comment]
Thank you! :) I’ll close this.

**Comment by chrissimpkins** [comment]
come join us over in that report and let us know what type of spacing you are after.  if you have an example font that is helpful.

**Comment by chrissimpkins** [comment]
Line spacing shell scripts are now available and automate this within the range 10 - 30% UPM size (in 5 percentage point increments).  Drop the script in a directory with **only** your Hack fonts and execute it.

They are available here:

https://github.com/chrissimpkins/Hack/tree/master/tools/line-spacing
