### ISSUE TITLE
Spacing is way to small

### ISSUE THREAD

**Issue by mhinton** [chrissimpkins/Hack#122]
I was using version 2.010 of Hack and I updated to 2.015 and the character spacing is now way to small. The line height seems like it's just a little to small but the characters seem jammed together horizontally. I have reverted back to version 2.010. I see a lot issues where people are requesting a teeny tiny unreadable font but I think that for reading code the spacing around letters is important.

**Comment by chrissimpkins** [comment]
Can you upload a screenshot?  There should be no change in the horizontal dimensions of the glyphs.  The vertical spacing between lines did change (closer) with the most recent release.  This was in part by request and in part by necessity to address problems with the vertical alignments of glyphs that need to be aligned on separate lines (eg box glyphs).

**Comment by mhinton** [comment]
Maybe the horizontal spacing is fine but I still prefer the older version.

Here is 2.0.15:
![buyer_controller_js____dev_2wav_suzanne_app_client_controllers__-_vim1](https://cloud.githubusercontent.com/assets/23145/10323480/05338e56-6c49-11e5-8adb-157e0c926bd1.png)

Here is 2.010:
![buyer_controller_js____dev_2wav_suzanne_app_client_controllers__-_vim](https://cloud.githubusercontent.com/assets/23145/10323539/59348ba4-6c49-11e5-81e5-de175b2e0c22.png)

**Comment by chrissimpkins** [comment]
Come join us in #28. There is interest in this issue and a previous issue report exists addressing line spacing.  Our current plan is to produce multiple line spacing variants to address it but it will require a big overhaul of the font to allow for proper alignments of the glyphs that I mentioned above.  A short term alternative that we could consider is the creation of a smaller set that does not include these glyphs and build upon this over time.  

If you have interest in helping us develop this, please post information about current fonts that have line spacing that you do like.  This will assist us as we make the decision about the variants that we produce.

Thanks for your feedback.

**Comment by chrissimpkins** [comment]
Line spacing shell scripts are now available and automate this within the range 10 - 30% UPM size (in 5 percentage point increments).  Drop the script in a directory with **only** your Hack fonts and execute it.

They are available here:

https://github.com/chrissimpkins/Hack/tree/master/tools/line-spacing
