### ISSUE TITLE
Powerline support

### ISSUE THREAD

**Issue by corelon** [chrissimpkins/Hack#13]
As this is becoming more and more popular and it is now available outside vim would it be possible to add Powerline support to the font?

**Comment by chrissimpkins** [comment]
Mind giving it a shot in your Powerline setup?  I included the glyphs in the regular set but haven't tested it yet (not a Powerline user...).  It should work and if it doesn't, please let me know what the issues are so that we can fix them and get it submitted to the Powerline fonts GH repo.  Thanks much!

**Comment by corelon** [comment]
Sure thing. I will do it now.

**Comment by corelon** [comment]
Just did. I include screenshots from Hack and Tamzen (a bitmap font with powerline support to see the differences. It seems that the Powerline symbols are very small and difficult to see plus the arrows do not show well.

![hack](https://cloud.githubusercontent.com/assets/49140/8685091/055404c0-2a85-11e5-968e-1da9e44b4825.png)
![tamzen](https://cloud.githubusercontent.com/assets/49140/8685109/3216a4d6-2a85-11e5-824b-4ade92953eaf.png)

**Comment by chrissimpkins** [comment]
I think I see the problem in the source.  I will try to correct it tonight and put another test version up to see if it works

**Comment by corelon** [comment]
Cool! Let me know and I will try it straight away!

**Comment by chrissimpkins** [comment]
OK, I think they should be set.  I have a test build of the regular set in the development branch.  

https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular.otf?raw=true

The Greek characters are included but I haven't made the Hack modifications yet so this should be considered a fully functional non-release build.  It's not quite ready for Greek character testing.  This was a simple merge and I need to do some testing/add some Hack flavor before they are release ready.  The Powerline glyphs were all updated and should (hopefully...) work now based upon the images that you provided.  There are a couple of open arrow Powerline glyphs that I don't see on the images that you linked.  I'm not sure if they should be flush with the left and right side of the box or centered.  If you happen to notice any alignment issues, please let me know.  

I will include these Powerline glyph changes in the next release if they seem to work.  The Powerline stuff is pretty plain.  We could stand out from the crowd by making these pop a bit too...  Not sure how the vim community would feel about that.

**Comment by corelon** [comment]
They seem to be working fine, at least on a general view.. The proportions looks right now.

**Comment by chrissimpkins** [comment]
excellent! let me know if you come across any issues

**Comment by corelon** [comment]
Great job! I will

**Comment by corelon** [comment]
What was the issue just in case I decide to patch other fonts

**Comment by chrissimpkins** [comment]
The metrics of the import glyphs from the Powerline.otf set that is released by the Powerline group differed from the metrics of the current typeface.  I had to adjust this and then correct the size of the glyphs, reposition them.  Let me know if you have any questions when/if you try to patch others and I'd be happy to help.

**Comment by corelon** [comment]
Good to know. I pretty much thought that it would be as easy as to run the patch script that was out there.
But I guess it needs tweaking afterwards. Would fontforge do the job?

**Comment by corelon** [comment]
In general what (free) font editor would you recommend?

**Comment by chrissimpkins** [comment]
Check out FontForge https://fontforge.github.io/en-US/ .  It is the most commonly used free editor.  If you are working on OS X it requires X Quartz which was an issue for me.  The character display looked terrible on a retina screen and I couldn't come up with a good fix.  It produces high quality fonts and is easy to use.  The site that I linked above has detailed documentation on the application and on typeface design in general.  Definitely worth a read.

**Comment by chrissimpkins** [comment]
This script is worth checking out for the Powerline glyph patches on other typefaces as well: 

https://github.com/powerline/fontpatcher/blob/develop/scripts/powerline-fontpatcher 

I haven't used it myself but it claims to automate the patch process.  I am guessing that there is going to be some tinkering necessary after use, but might be worth a try.

**Comment by chrissimpkins** [comment]
sorry didn't see that you referred to the patch script.  I think we are both talking about the same script.

**Comment by corelon** [comment]
Hi,

Thanks a lot for the information. Yes we are talking about the same script. I will check the website you linked to when I get a bit more time as I am very interested in typeface design.

**Comment by chrissimpkins** [comment]
Lots of helpful scripts/command line applications too.  Happy to discuss once you get started.

**Comment by chrissimpkins** [comment]
Lots of scripts/command line applications out there as well. Let me know when you get your software up and running and we can discuss more in detail as you are working through the design/builds/post-build processing on your project.

**Comment by corelon** [comment]
Will do. Will probably take me some time as I am knee deep with work right now, plus I just moved back to my home country (Greece) and I am a bit lost in space (my son probably more so)

**Comment by chrissimpkins** [comment]
feel free to shoot me an email or contact me on Twitter (csimpkins) anytime.  thanks so much for all of your help.  I really do appreciate it.

**Comment by corelon** [comment]
My pleasure. Thanks for providing a very nice quality font for free :)

**Comment by corelon** [comment]
Your work is really appreciated.

**Comment by chrissimpkins** [comment]
My pleasure Nikos. Enjoy!

**Comment by chrissimpkins** [comment]
The Powerline glyphs will be included as a default patch in the upcoming version 2.0 release of the Hack-Regular binary.  You can test/use the Powerline glyphs in the current version of the test build that is released at this URL:

https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular.otf?raw=true

**Comment by chrissimpkins** [comment]
Available for general use in the v2.010 release which has been merged into the master branch of the repository.
