### ISSUE TITLE
No donation support

### ISSUE THREAD

**Issue by mmcco** [chrissimpkins/Hack#135]
I'd like to thank you for your work and I'm probably not the only one. Have you considered putting a donation link on the website and in the README?

**Comment by chrissimpkins** [comment]
Thanks Michael.  It’s not necessary at all.  If you’d like to “compensate" all of those who have contributed their time and efforts here, I’d ask that you donate a bit of your own time to make the project better (as you’ve already done in your other issue report).  It’s how we move forward.

Thanks much for the gesture.
