### ISSUE TITLE
The underscore is too low 

### ISSUE THREAD

**Issue by Grimy** [chrissimpkins/Hack#139]
Hack’s `_` is way too low. This was already mentioned in #103 and is also linked to #100.

As I understand it, the core of the issue is that “Hack is designed such that underscores appear on the top-most pixels of the next line down.” (quote taken from #100). This supports the historical use of underscores as a way to underline text, but looks visually jarring in `snake_case`, and causes issues in many programs.

For example, in xterm, with `faceName: Hack` and all other settings at their default values, non-bold underscores do not render at all. With `faceSize: 15` and `Xft.antialias: 1`, underscores look like extremely thin gray lines. As a workaround, setting `scaleHeight: 1.05` (or greater) makes the underscores visible again.

One could blame xterm for incorrectly assuming that glyphs do not extend beyond the current line, but I believe this is quite a reasonable assumption, and Hack should live up to it (at least for ASCII chars). That’s what other fonts do, that’s what users expect, and it avoids trouble with naïve rendering engines (xterm, IDEA, probably others).

**Comment by burodepeper** [comment]
Hi @Grimy,
We are currently looking into the usability of Hack, especially the ascii-charset, so the underscore will get the love it deserves. Could you post some screenshots of the issues you mention? That would help us a lot. Thanks!

**Comment by Grimy** [comment]
Here is an example of the “thin gray line” behavior, where it looks like only the anti-aliased edge is rendered:

![result](https://cloud.githubusercontent.com/assets/3199732/10729997/76dc9f30-7bed-11e5-9889-c2cea14997cd.png)

This is the text "_p_" with the following xterm config:

    xterm*faceName: Hack
    *faceSize: 15
    *foreground: white
    *background: black
    Xft.antialias:    1
    Xft.autohint:     1
    Xft.hinting:      0
    Xft.hintstyle:    hintfull
    Xft.rgba:         rgb

At face size 11, the undescore is just pure plain black, so there’s no need for a screenshot.

Thanks for your quick reply, it’s good to know that you’re already looking into this kind of issues!

**Comment by burodepeper** [comment]
That indeed is a thin gray line. It isn't even visible in my Chrome, but Photoshop helps. This is indeed unacceptable, but it seems that the character is simply cut off. The underscore itself is positioned fully inside the glyph-box so it should be visible. I am unfamiliar with xterm, but could you see what happens if you define a line-height of 1.25 or greater?

See the picture attached; this is where the underscore is supposed to be...

![schermafbeelding 2015-10-26 om 14 36 03](https://cloud.githubusercontent.com/assets/3703530/10730224/f9472516-7bee-11e5-85ff-e54e8ead7ffb.png)

**Comment by Grimy** [comment]
> could you see what happens if you define a line-height of 1.25 or greater?

In xterm’s config, line-height is called “scaleHeight”. As I said in my opening post, setting “scaleHeight” to 1.05 or greater makes the underscore fully visible, but it is still unpleasantly low. Here’s how it looks:

![_p_](https://cloud.githubusercontent.com/assets/3199732/10730501/a0867b8c-7bf0-11e5-8073-2b559c024295.png)

I just noticed that I am using an old version of Hack: 552df98 (29 Aug). I’ll try updating to see if it changes anything.

**Comment by burodepeper** [comment]
Yes, please update. : )
I believe all vertical metrics have been corrected in one the latest releases.

**Comment by Grimy** [comment]
The problem is not present in Hack-v2_015-ttf. Sorry for the false alert!

I’ll close this issue, thanks for your attention (=

**Comment by burodepeper** [comment]
Not a problem! Have a nice day.
