### ISSUE TITLE
v2.0 Test Builds are Available to Try

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#14]
I am releasing test builds of the upcoming v2.0 release that will include a large number of new character sets and changes to the Hack typeface.  Development is taking place in the `development` branch of the repository.

The new character sets include:

- Powerline symbols (patched by default into the regular set)
- Expanded Latin character set
- Greek character set
- Cyrillic character set
- Expanded math symbols/characters
- Armenian character set
- Georgian character set
- Expanded Vietanamese character set
- Expanded pan-African character set
- Expanded punctuation character set
- Expanded symbol set
- New superscript numerals
- New subscript numerals
- New scientific inferior numerals

This release increases the number of Hack glyphs by nearly 10-fold and should permit much broader, multilingual use of the typeface.

### Current Test Releases (build v2.010)

**Regular Set**: 
- **OTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Regular.otf
- **TTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Regular.ttf

**Bold Set**: 
- **OTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Bold.otf
- **TTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-Bold.ttf

**Oblique Set**: 
- **OTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-RegularOblique.otf
- **TTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-RegularOblique.ttf

**Bold Oblique Set**: 
- **OTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-BoldOblique.otf
- **TTF**: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-BoldOblique.ttf

### Testers 

If you use the test versions and encounter any problems, please provide me with feedback so that we can fix any issues.  Thanks much!

**Comment by corelon** [comment]
Already installed and testing

**Comment by chrissimpkins** [comment]
great!  let me know if you come across any problems. I should have the oblique sets out later this week.

**Comment by corelon** [comment]
I see now that bold glyphs are in proportion to the regular ones. In the previous test build I had the impression that the metrics were slightly off, but this could also be because of the software I was using?

**Comment by chrissimpkins** [comment]
for Greek glyphs in regular set?

**Comment by chrissimpkins** [comment]
New v2.003 test builds available with updates to lowercase i character glyphs in the extended Latin sets and positioning of glyphs in the Greek sets (regular and bold).  I changed the shape of the lowercase i shape in all glyphs that use it and adjusted the positioning.  It was not properly centered and the longer horizontal stem made it look too top heavy, too broad for a lowercase i character.   I think that this fits better with the rest of the typeface.

It also includes alignment modifications in the Greek set.  They are relatively minor, but seem to improve the horizontal orientation of several of the characters.  The long xi and zeta characters in particular seemed left aligned to me.  Now they appear centered between adjacent characters.

**Comment by corelon** [comment]
Thanks a million.. I will try it ASAP

**Comment by chrissimpkins** [comment]
Really appreciate your help Nikos!

**Comment by chrissimpkins** [comment]
A test version of the oblique set is now available: 

https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-RegularOblique.otf

**Comment by corelon** [comment]
I have substituted a custom version of Input Mono (customized through their website) on IntelliJ with Hack so that I can use it full time. The only issue I see is that the oblique version seems too oblique, but I think I heard that this is an issue with java rendering (Intellij is java-based).
Do you intend to create "real" italics at some point? I think that a couple of characters (like lower-case a) would look better with a real italic style, but that is of course a matter of personal preference.

**Comment by chrissimpkins** [comment]
mind pushing a screenshot?

**Comment by corelon** [comment]
![hack_oblique_java](https://cloud.githubusercontent.com/assets/49140/8838155/6602f570-30d3-11e5-88b6-3beeb614a7e6.png)

**Comment by chrissimpkins** [comment]
I think that might be your software creating its own set of obliques for the syntax highlighter.  That slant definitely looks different from the actual design.  The oblique slant is only 10.75 degrees.  Here they are side by side: 

#### Regular
<img width="490" alt="regular" src="https://cloud.githubusercontent.com/assets/4249591/8838544/4212f04e-309b-11e5-8394-5a1d9d885162.png">

#### Oblique
<img width="490" alt="oblique" src="https://cloud.githubusercontent.com/assets/4249591/8838550/47b1abc6-309b-11e5-9dd8-b38709323eb0.png">

May need to dig into the syntax highlighter script or settings in Intellij.  I came across [this documentation](https://confluence.jetbrains.com/display/IntelliJIDEA/Syntax+Highlighter+and+Color+Settings+Page) but don't see how it is defining the italic/oblique vs. bold highlighting.

**Comment by chrissimpkins** [comment]
A bold oblique test build was added: https://github.com/chrissimpkins/Hack/raw/development/build/test_builds/Hack-BoldOblique.otf

**Comment by chrissimpkins** [comment]
> Do you intend to create "real" italics at some point?

I am not a big fan of the true italic cursive style in source.  It might work for comments, but I don't think that it would look good in syntax highlighters that use it in the code itself (like your example above).  Maybe we could come up with something subtle.  Let me have a look through other sans serif faces to see if I can get some ideas.  Many sans serif typefaces use the oblique form rather than true italics.

**Comment by corelon** [comment]
If it is not very intrusive then I think it might even look good. I think Consolas and PragmataPro (and Input Mono?) have true italics. I don't think it is necessary, I just think that it looks good if it is not too much.

**Comment by corelon** [comment]
As for IntelliJ I have no clue how the syntax highlighting works. But I was thinking the same thing, that it synthesizes italics instead of using the provided ones.

**Comment by chrissimpkins** [comment]
I'll take a look at them to see what they modified in their italics.  Thanks!



—
Chris

**Comment by chrissimpkins** [comment]
> As for IntelliJ I have no clue how the syntax highlighting works. But I was thinking the same thing, that it synthesizes italics instead of using the provided ones. 

I use PyCharm.  Let me dig through the settings a bit and see what I can find

**Comment by chrissimpkins** [comment]
New v2.004 test builds added at the links in the first post in this thread.  Includes numerous new vertical and horizontal spacing adjustments, new superscript/subscript numerals, new scientific numerals.  Nearing the end of new features for the release version...

**Comment by chrissimpkins** [comment]
I will be releasing v2.0 of the typeface this week.  Please let me know if you have any final thoughts before release.  Thanks again for all of your help with the testing!

**Comment by corelon** [comment]
Hi. The new features sound very interesting. Unfortunately I am on holiday and do not have regular access to my computer. But will test as soon as I can.
Thanks again.

**Comment by chrissimpkins** [comment]
thank you Nikos! No rush.  We can fix any issues in a new release. Enjoy your vacation.

**Comment by chrissimpkins** [comment]
Received user report of v.2.0.x install failure on Windows.  Looking into this issue.  Issue #17

**Comment by chrissimpkins** [comment]
New build with a new lowercase a and t style, metrics changes.  

![c-mockup](https://cloud.githubusercontent.com/assets/4249591/9155177/10ceecfa-3e7d-11e5-81b0-d44b43b8ae27.png)

**Comment by chrissimpkins** [comment]
@corelon Nikos do you mind having a look at the diacritics in the latest build?  I tightened the spacing between them and the letters.  I wanted to confirm that they look ok in both the upper and lower case to you.   It is pretty tight on the upper case but looking at other fonts, the diacritics on the upper case chars get cut off at smaller text sizes.

**Comment by corelon** [comment]
Hi,
The only problem I see is with upper case Ypsilon and tonos. The tonos seems to appear on the right of the letter instead of the left.
Also diairesis and tonos on upper case Ypsilon and Iota are not working, which I think is fine as I cannot think of any word that would start with either or have the capitalized.

**Comment by chrissimpkins** [comment]
I will take a look at them.  thanks much for the input.   I really appreciate it!

**Comment by chrissimpkins** [comment]
I spaced the upper case upsilon tonos a bit more so that it is visible on the left of the glyph.  I don't believe that we discussed upper case iota tonos as one of the commonly used modern Greek characters so I haven't included it in the set at this point.  I will push new binaries that include these changes.  I am working out some Windows build issues and will move this release to the master branch.  Thanks again for your help with this.  I will let you know when there are a release set of files ready for use.

**Comment by chrissimpkins** [comment]
A release version of the v2.0 updates is now included in the test_builds directory of the development branch.  I will be merging this with the master branch this weekend.

### *For Windows Users*
Based upon my (limited) testing on Windows, Windows users should enable directwrite rendering capabilities in their editors.  For example in Sublime Text, the user settings JSON file should be modified to include:

```json
"font_options":
[
    "directwrite"
]
```

I am looking into how to do this for other commonly used editors on Windows.  Any feedback from developers on Windows would be greatly appreciated.  It is unclear to me why this is not the default. 

I will work on a manually hinted TrueType build to see if there is a significant difference in the screen appearance on Windows boxes.

**Comment by chrissimpkins** [comment]
### Rendering information for IntelliJ / PyCharm / etc users:

Link with additional information that may help with rendering settings on these JavaVM based editors. 

http://superuser.com/questions/614960/how-to-fix-font-anti-aliasing-in-intellij-idea-when-using-high-dpi/623596#623596

**Comment by chrissimpkins** [comment]
New [ttf files with TrueType instructions](https://github.com/chrissimpkins/Hack/tree/development/build/test_builds) are now available in the test builds directory.  Windows users should try these files rather than the otf builds.  The optical sweet spot seems to be in the 8 - 12 pixel range.

**Comment by chrissimpkins** [comment]
The new v2.0x changes are merged into the master branch of the repository and are now available for general use.  

@corelon - thank you very much for all of your help with the Powerline and Greek character set testing in this release.  I apologize for all of the pestering and really do appreciate it.  I added your name to the [contributors list](https://github.com/chrissimpkins/Hack/blob/master/CONTRIBUTORS.md).
