### ISSUE TITLE
Ligatures like monoid, hasklig, fira code (=>, !=, ++,..)

### ISSUE THREAD

**Issue by stefan-kern** [chrissimpkins/Hack#144]
Hasklig: https://github.com/i-tu/Hasklig
Monoid: https://github.com/larsenwork/monoid
FiraCode: https://github.com/tonsky/FiraCode

all of those fonts come with ligatures for the most common programming operators like:
<* <*> <+> <$> *** <|> !! || === ==> <<< >>> <> +++ <- -> => >> << >>= =<< .. ... :: -< >- -<< >>- ++ /= ==

since hack aims to be a code typeface it might be a good idea to include these common ligatures aswell.

**Comment by dkerzig** [comment]
+1

**Comment by chrissimpkins** [comment]
Have a look at issue #35 and drop by to join us for the conversation there.  There are pros and cons to this approach for a face that aims to be a "general purpose" typeface for source code.  We would like to discuss this in more detail with you and are working on a solution that should address this down the road. 

I'll add your comments to the thread and close this issue.

**Comment by chrissimpkins** [comment]
_**New message in #35 that addresses this issue report**_:

We’re tossing around the idea of starting a branch of Hack that includes ligatures and will serve as “working fonts” for development in text editors.  This will be developed in parallel with the main Hack branch, be released under a new font name,  and address the mounting interest that you’ve expressed here.

For those who are interested in this, will you please chime in again with:

- a list of the idioms / adjacent character combinations that should be supported
- a list of programming languages where these are appropriate/inappropriate in your opinion - this will be necessary to create testing tools to support these sets

As you work through the above, I’d ask you to also begin to think about the design of the ligatures that you suggest.  As this materializes, we will plan to create issue reports for the ligatures where the design can be discussed in much more detail.  It will be impossible to meet everyone’s demands / needs, but ideas are extremely helpful and will drive the design as the set matures.

Lastly, it would be helpful to have at least one individual with development experience in each language that we define as our supported target languages (see above) who would be willing to commit to testing these during the early, active development phase.  

Let’s see what we can pull together.

**Comment by thiagolucio** [comment]
I create a repository with Hasklig Family font for windows. That's run very well native for all Editors.
https://github.com/thiagolucio/HaskligFontFamily-Windows

Be Happy :)
