### ISSUE TITLE
Hack hinting for horizontal stems broken when connecting over Remote Desktop connections.

### ISSUE THREAD

**Issue by jpluimers** [chrissimpkins/Hack#145]
Hinting of Hack seems to be broken over Remote Desktop connections.

I'm using https://github.com/chrissimpkins/Hack/releases/download/v2.015/Hack-v2_015-ttf.zip

This is from a Windows 8.1 doing an RDP connection with 32-bit colour depth to my development machine that runs Windows 7 that runs Delphi 2007 but I have similar results in Visual Studio 2013 ([Hack](https://www.dropbox.com/s/9qekxo0pc07w7yb/20151031-VS2013-Hack%4010points.png?dl=0) vs [Lucida Console](https://www.dropbox.com/s/i0q0kn34c11p7dj/20151031-VS2013-LucidaConsole%4010points.png?dl=0):

# Hack @ 10 points

[![Hack @ 10 points](https://www.dropbox.com/s/ey7rzgiuzrwpv9d/20151031-SysUtils-Hack%4010points.png?raw=1)](https://www.dropbox.com/s/ey7rzgiuzrwpv9d/20151031-SysUtils-Hack%4010points.png?dl=0)

# Lucida Console @ 10 points
[![Lucida Console @ 10 points](https://www.dropbox.com/s/9w2nop21070k3dc/20151031-SysUtils-LucidaConsole%4010points.png?raw=1)](https://www.dropbox.com/s/9w2nop21070k3dc/20151031-SysUtils-LucidaConsole%4010points.png?dl=0)

**Comment by chrissimpkins** [comment]
Can you more detail about what you mean by the "hinting for the horizontal stems"?  I agree that the rendering looks awful with this approach in your SS.

I'll admit I have absolutely no knowledge of the rendering process that happens through Windows RDP but a brief search led to these articles.  Have a look and see if they provide a start to this discussion:

http://answers.microsoft.com/en-us/windows/forum/windows_7-desktop/cleartype-setting-is-not-persistent-across-remote/9dd670eb-5e74-4ff6-b26e-54f8a6efb3b3

https://technet.microsoft.com/en-us/library/cc742823.aspx

**Comment by chrissimpkins** [comment]
Closing.  Please reopen if/when you are prepared to work on this issue.  Thanks

**Comment by jpluimers** [comment]
I was presenting sessions and workshops of a conference, so a bit busy. I'll research these settings when back home.

**Comment by chrissimpkins** [comment]
no worries at all.  just doing a bit of cleanup
