### ISSUE TITLE
Hack does not show up in the font list for Windows command-prompt

### ISSUE THREAD

**Issue by jpluimers** [chrissimpkins/Hack#147]
I'm using https://github.com/chrissimpkins/Hack/releases/download/v2.015/Hack-v2_015-ttf.zip

I this Windows playing tricks on my, or a Hack font setting?

Hack is not listed in the Windows command prompt font settings:

[![Windows command prompt font settings](https://www.dropbox.com/s/ojzsi8j7mr00tqy/20151031-Hack-not-in-the-font-options-for-Windows-cmd-prompt.png?raw=1)](https://www.dropbox.com/s/ojzsi8j7mr00tqy/20151031-Hack-not-in-the-font-options-for-Windows-cmd-prompt.png?dl=0)

**Comment by burodepeper** [comment]
Does it show up if you uncheck the 'Bold fonts' option?

**Comment by chrissimpkins** [comment]
It looks like you only have Windows system fonts showing up in that list.  Do you have any other non-system fonts installed?

**Comment by stompychump** [comment]
This interesting explanation from Microsoft dates from 2007, but I believe it's still valid:

"Why are console windows limited to Lucida Console and raster fonts?"
http://blogs.msdn.com/b/oldnewthing/archive/2007/05/16/2659903.aspx

You may be able to add additional typefaces via the registry, but most will not work:

"Necessary criteria for fonts to be available in a command window"
http://support.microsoft.com/kb/247815

**Comment by chrissimpkins** [comment]
@stompychump :+1: thanks

**Comment by jublo** [comment]
@stompychump Thanks for your explanations. The `0`, `00` etc. fix does still work with Windows 10.

![](http://img.schieb.de/wp-content/uploads/2015/10/eingabeaufforderung-schrift-aendern.jpg)

**Comment by chrissimpkins** [comment]
@jpluimers please confirm if the fix mentioned by @jublo above works for you.

**Comment by chrissimpkins** [comment]
Closing.  Please reopen if this is not fixed with the above solution.  Thanks

**Comment by jpluimers** [comment]
Will research this when I've returned from the EKON 2015 conference in Germany where I just taught 3 sessions and a workshop.

**Comment by chrissimpkins** [comment]
no worries!  feel free to reopen anytime.  This was just a repository maintenance/cleanup close, happy to provide any additional help.
