### ISSUE TITLE
[Hack v2.018] Weird fonts with Regular type for both .ttf and .otf files on OSX

### ISSUE THREAD

**Issue by giver** [chrissimpkins/Hack#156]
OS: OS X El Capitan Version 10.11.1 (15B42)
Application: Terminal
Font: Hack v2.018

![hack-font-normal](https://cloud.githubusercontent.com/assets/8775102/11138883/ba3ce7d8-89fa-11e5-8123-135768f24b17.gif)

**Comment by chrissimpkins** [comment]
Are you having problems in any other applications on OS X Tanin?

**Comment by chrissimpkins** [comment]
I can verify that Hack v2.018 is working for me in Terminal Version 2.5.3 on OS X 10.10.5.  Was this an issue that developed after you upgraded your OS to El Capitan or is this a new install of Hack (i.e. did Hack v2.018 ever work on your system in Terminal)?

**Comment by giver** [comment]
@chrissimpkins I have first version of Hack installed v2.010 on my system before and it is working fine. until I upgraded to v2.018. But I'm not sure that I done it before or after upgrade to El Capitan.

> Are you having problems in any other applications on OS X Tanin?

No. It was perfectly worked on my code editor (PHPStorm)

**Comment by chrissimpkins** [comment]
It appears that this is something on the Terminal side.  Would you be willing to investigate the Terminal changelog to see if there are any differences in font rendering between the 10.10 and 10.11 versions of OS X?

**Comment by giver** [comment]
Hi @chrissimpkins. Now it is working fine. I don't know why and the reason behind that. Maybe I had restart my Macbook Pro and the some weird issue gone. So, I will close this issue now. 

Thx for your support.

**Comment by chrissimpkins** [comment]
Good to hear! Thanks
