### ISSUE TITLE
Block character size (U+2588)

### ISSUE THREAD

**Issue by t3rminus** [chrissimpkins/Hack#158]
Noticed this when using the newer version of NPM today, which draws a progress bar using (what I assume is) the "Full Block" character (219?). It looks... very odd.

Here is how it displays using Hack:
![screen shot 2015-11-24 at 9 49 34 am](https://cloud.githubusercontent.com/assets/643473/11375544/b74be008-9290-11e5-9489-779e9c72b214.png)

Compared to DejaVu Sans Mono:
![screen shot 2015-11-24 at 9 49 42 am](https://cloud.githubusercontent.com/assets/643473/11375549/bb387640-9290-11e5-8803-e175ffcb8626.png)

Compared to Bitstream Vera Sans Mono:
![screen shot 2015-11-24 at 9 49 23 am](https://cloud.githubusercontent.com/assets/643473/11375552/be2cb0dc-9290-11e5-9a6f-21c42419786e.png)

Compared to Menlo:
![screen shot 2015-11-24 at 9 49 48 am](https://cloud.githubusercontent.com/assets/643473/11375553/c0002f9c-9290-11e5-9c50-d0c16cf0e285.png)

**Comment by jublo** [comment]
Hi @t3rminus,
thanks for your report about this. In fact, I myself have noticed this as well.

The character in question is `U+2588` `FULL BLOCK`. See here:
https://github.com/iarna/gauge/blob/master/progress-bar.js#L57

**Comment by t3rminus** [comment]
@jublo thanks for confirming!

**Comment by chrissimpkins** [comment]
@t3rminus the box glyphs are next up in the queue.  we will be taking a look at all of these for the next release.  will make sure that this one is included.  can you tell whether it is using the regular or bold set?

**Comment by t3rminus** [comment]
@chrissimpkins Regular, unless there's some way that it's using the bold variant that I'm not aware of.

**Comment by chrissimpkins** [comment]
@t3rminus thanks, we will take a look!

**Comment by chrissimpkins** [comment]
I just finished this update last evening and it should address this problem with U+2588.  Hope to have this out in the v2.019 release later this week.  Will post here when available.

**Comment by chrissimpkins** [comment]
Fixed and now available as part of the v2.019 release.  Thanks for this issue report Kevin.

**Comment by t3rminus** [comment]
Confirmed fixed. Thanks Chris!

**Comment by chrissimpkins** [comment]
Excellent.  Glad to hear that!
