### ISSUE TITLE
Hack Mentions

### ISSUE THREAD

**Issue by corelon** [chrissimpkins/Hack#16]
I already put the font on Slant (here: http://www.slant.co/topics/67/viewpoints/74/~what-are-the-best-programming-fonts~hack)
Please feel free to improve and maybe add it to some more places to gain more traction.

**Comment by chrissimpkins** [comment]
Thank you very much for promoting this Nikos.  I am going to have a new site for the typeface and am planning to add it to some of the design sites for feedback and exposure after this release is pushed.  It will also be submitted to the Powerline fonts repository which will provide exposure to developers.  It is already up on many of the free font sites and those will all be updated with the new binaries.  

This is a great idea and I will definitely followup on it.

**Comment by chrissimpkins** [comment]
And it is on [Codeface](https://github.com/chrissimpkins/codeface)!

**Comment by chrissimpkins** [comment]
New website is coming together.  Once I have this documentation complete, I will push this release and get the word out. 

<img width="1332" alt="hack-site-eg" src="https://cloud.githubusercontent.com/assets/4249591/9054449/851d83c8-3a4f-11e5-9cfb-8a17eb06dbf7.png">

**Comment by corelon** [comment]
Great!

**Comment by chrissimpkins** [comment]
I added additional pros to your comments on the Slant post.  Thanks again for mentioning it there.

**Comment by chrissimpkins** [comment]
It is posted to / available on:

dafont.com - http://www.dafont.com/hack.font
Fontspace - http://www.fontspace.com/chris-simpkins/hack 
Open Font Library - http://openfontlibrary.org/en/font/hack
