### ISSUE TITLE
Create glyph visual comparison/diff tool for testing

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#160]

**Comment by chrissimpkins** [comment]
Work on this is in progress and the project is being developed / maintained by @jorgheymans.  Additional details will be made available when a version of the tool is available for testing.

**Comment by davelab6** [comment]
cc @brawer who has something similar in noto-tools

**Comment by chrissimpkins** [comment]
Thanks @davelab6!

@brawer, meet @jorgheymans, Jorg @brawer 

Perhaps we can discuss where both projects are to avoid duplication of efforts?
