### ISSUE TITLE
Create a Java font rendering test tool to assess rendering issues in editors that use this renderer type (including JetBrains editors)

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#161]
New tool idea from the discussion in #152.

**Goal**: create a tool that can be launched from the command line and display a Java-rendered external text specimen file with any installed Java version.

**Need**: 

- [x]  Java developer(s)
- [x] repository for the tool
- [x]  rendering of a simple Swing text window that supports any external large text specimens with scrolling for text overflow
- [x]  support for local font file and local text specimen file definitions on the command line or in GUI
- [ ]  +/- support for hinting/no hinting settings if this is possible via Java (need to investigate this)

Any and all help is welcomed.

**Comment by fruel** [comment]
I build an initial version of the test tool. You can find it here: https://github.com/fruel/JavaFontRendererTest (binary release included)

**Comment by chrissimpkins** [comment]
Thanks @fruel!  This looks great based upon the description in the README.  I will give it a try later today.  Is it possible to include instructions on how to build the jar file from source?
