### ISSUE TITLE
Glyph add request. U+2116.

### ISSUE THREAD

**Issue by shepelevstas** [chrissimpkins/Hack#163]
Hello! I like your hack font very much =) I use it in sublime for js programming. I miss one glyph. Can you add it, please? =) It’s used in Russian when you type “shift+3”. Dejavu has the glyph, but Hack looks beater in sublime =)
I wrote a letter to you. You suggested to add the request as an issue report, so I did=). Will be waiting for a new glyph!=)

**Comment by chrissimpkins** [comment]
The numero symbol (U+2116) was added in v2.017. [Changelog](https://github.com/chrissimpkins/Hack/blob/master/CHANGELOG.md)

Should be a simple update away for you :)

Enjoy!

**Comment by shepelevstas** [comment]
Oh! Great! Thank You!=) Where can i get it?=) I Downloaded the latest version from http://sourcefoundry.org/hack/. v2.018. When i open it to install, it says Version 2.010.

**Comment by chrissimpkins** [comment]
What platform are you on?  May need to delete the old version of the Hack fonts and then install.

**Comment by chrissimpkins** [comment]
And with Sublime (and many other text editors), close the editor and open it again.  They cache fonts and the new one will not show up until you do this.

**Comment by shepelevstas** [comment]
Thanks. It worked. But i must get back to the old version. Now Russian "C" looks really wrong...=0

**Comment by chrissimpkins** [comment]
That was a change that we made based upon requests from Cyrillic users.  It was not well received and it is changing back in the next release.  Here is a pre-release version that you can use:

https://github.com/chrissimpkins/Hack/tree/development/postbuild_processing/posthinted_builds

This release will be out later this week.

**Comment by chrissimpkins** [comment]
The files above will show up as v2.019

**Comment by shepelevstas** [comment]
WOW! You just saved my day=)))))

**Comment by chrissimpkins** [comment]
Haha! Happy Holidays. Enjoy
