### ISSUE TITLE
[wishlist - granted ;) ] Create tar.xz tarballs for next release

### ISSUE THREAD

**Issue by heliocastro** [chrissimpkins/Hack#168]
At Fedora we do prefer use when available .tar.xz files, due compression rates, and sometimes, in some extreme cases, we even repackage the source code.

So, if is not that complex to you, can you add tar.xz compressed files as well for next release ?

Thanks for your work, Helio

**Comment by chrissimpkins** [comment]
I will get this up for you today with the current release.  Any preferences about the compression level?

**Comment by heliocastro** [comment]
Hey
No worries about compression level. 
I already released .019 with tar.gz, so will be ok for next release.
Thanks

**Comment by chrissimpkins** [comment]
Mind confirming that these have the correct archive font (and CSS) file paths for you?  Looks like you will save a bit of bandwidth with this archive format :+1: :

https://github.com/chrissimpkins/Hack/tree/development/build/archives

If this works for you, I will include these `tar.xz` archives in future releases as attachments to the release as we are currently doing with the `.zip` and `.tar.gz` archives.  You will be able to access them using the same URL syntax.

**Comment by heliocastro** [comment]
Almost there, minor issued:
- The name is different from the original sources: Hack-v2_019-ttf to Hack_v2.019-ttf
- The currnet 2.019 sources doesn't have sub dir:
./Hack-Bold.ttf x ttf/Hack-Bold.ttf

**Comment by chrissimpkins** [comment]
Using this script:

https://github.com/chrissimpkins/Hack/blob/master/postbuild_processing/archive_prep/make_tarxz.sh

Will modify it to try to make the adjustments above.  Can you clarify the second bullet point?

**Comment by heliocastro** [comment]
Directory structure. Current package doesn't have subdirectory ( which i think is better ).

- Current package 
[helio@triceratops hack-fonts]$ tar tvfz Hack-v2_019-ttf.tar.gz 
drwxr-xr-x ces/staff         0 2016-01-18 01:36 ./
-rw-r--r-- ces/staff    396032 2016-01-16 18:50 ./Hack-Bold.ttf
-rw-r--r-- ces/staff    404656 2016-01-16 18:50 ./Hack-BoldItalic.ttf
-rw-r--r-- ces/staff    399648 2016-01-16 18:50 ./Hack-Italic.ttf
-rw-r--r-- ces/staff    394336 2016-01-16 18:50 ./Hack-Regular.ttf

- New xz package
[helio@triceratops hack-fonts]$ tar tvfJ Hack_v2.019-ttf.tar.xz
drwxr-xr-x ces/staff         0 2016-01-18 02:01 ttf/
-rw-r--r-- ces/staff       120 2015-11-05 03:16 ttf/._.DS_Store
-rw-r--r-- ces/staff      6148 2015-11-05 03:16 ttf/.DS_Store
-rw-r--r-- ces/staff    396032 2016-01-18 02:01 ttf/Hack-Bold.ttf
-rw-r--r-- ces/staff    404656 2016-01-18 02:01 ttf/Hack-BoldItalic.ttf
-rw-r--r-- ces/staff    399648 2016-01-18 02:01 ttf/Hack-Italic.ttf
-rw-r--r-- ces/staff    394336 2016-01-18 02:01 ttf/Hack-Regular.ttf

**Comment by chrissimpkins** [comment]
that script doesn't seem to eliminate the .DS_Store files either.  will work on it

**Comment by chrissimpkins** [comment]
Corrected the archive file paths and the release files are in the top level of the directory.

```
Hack/build/archives  development ✗                                23h3m ✖ ⚑ ◒
▶ tar tvfJ Hack_v2_019-ttf.tar.xz
drwxr-xr-x  0 ces    staff       0 Jan 17 20:01 ./
-rw-r--r--  0 ces    staff  396032 Jan 17 20:01 ./Hack-Bold.ttf
-rw-r--r--  0 ces    staff  404656 Jan 17 20:01 ./Hack-BoldItalic.ttf
-rw-r--r--  0 ces    staff  399648 Jan 17 20:01 ./Hack-Italic.ttf
-rw-r--r--  0 ces    staff  394336 Jan 17 20:01 ./Hack-Regular.ttf

Hack/build/archives  development ✗                                23h3m ✖ ⚑ ◒
▶ tar tvfJ Hack_v2_019-otf.tar.xz
drwxr-xr-x  0 ces    staff       0 Jan 17 20:01 ./
-rw-r--r--  0 ces    staff  164388 Jan 17 20:01 ./Hack-Bold.otf
-rw-r--r--  0 ces    staff  165804 Jan 17 20:01 ./Hack-BoldItalic.otf
-rw-r--r--  0 ces    staff  165924 Jan 17 20:01 ./Hack-Italic.otf
-rw-r--r--  0 ces    staff  161056 Jan 17 20:01 ./Hack-Regular.otf
```

I added these files to the current release and they will be included with future releases.  Thanks for all of your help with the redistribution on Fedora Helio.
