### ISSUE TITLE
Homebrew install fails with bad header line

### ISSUE THREAD

**Issue by paultopia** [chrissimpkins/Hack#169]
The recommended OS X installation method via homebrew fails as follows: 

    $ brew cask install caskroom/fonts/font-hack
    ==> Adding new tap 'caskroom/homebrew-fonts'
    ==> Cloning into '/usr/local/Library/Taps/caskroom/homebrew-fonts'...
    ==> Tapping caskroom/fonts
    Tapped 0 formulae (1042 files, 4.4M)
    Cloning into '/usr/local/Library/Taps/caskroom/homebrew-fonts'...
    Error: Cask 'font-hack' definition is invalid: Bad header line: parse failed

**Comment by chrissimpkins** [comment]
Thanks Paul.  These packages are not maintained by the project.  Let's see if the package maintainers have thoughts.

@chrisdaish @alerque any idea why the Homebrew cask might be throwing a bad header line error?

#### [font-hack.rb](https://github.com/caskroom/homebrew-fonts/blob/master/Casks/font-hack.rb)

```ruby
cask 'font-hack' do
  version '2.019'
  sha256 '9e847ad7afb327ca089c4b09d1368091ca0c98e64a2fe284755162e6650bfdd2'

  # github.com is the official download host per the vendor homepage
  url "https://github.com/chrissimpkins/Hack/archive/v#{version}.zip"
  appcast 'https://github.com/chrissimpkins/Hack/releases.atom',
          sha256: '6eef53a835e4dd76231c1c8d58b469669d61cf5db74dde95ec77fb2f17f7cb39'
  name 'Hack'
  homepage 'http://sourcefoundry.org/hack/'
  license :ofl

  font "Hack-#{version}/build/otf/Hack-Regular.otf"
  font "Hack-#{version}/build/otf/Hack-Italic.otf"
  font "Hack-#{version}/build/otf/Hack-Bold.otf"
  font "Hack-#{version}/build/otf/Hack-BoldItalic.otf"
end
```

**Comment by chrissimpkins** [comment]
I can verify that the version number and SHA256 hash changes in the most recent commit both appear to be valid

**Comment by jawshooah** [comment]
Your `brew-cask` is outdated. Check out the [massive, bolded heading](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system) on our readme for the fix :wink:

**Comment by chrissimpkins** [comment]
@jawshooah Thanks Josh.  I am assuming that the install with `brew cask install caskroom/fonts/font-hack` remains the same after he uninstalls `brew-cask`?

@paultopia Paul, let us know if this fixes your issue.  If so, I will update the original Homebrew documentation that @alerque added here so that users know about this change to brew cask.

**Comment by jawshooah** [comment]
@chrissimpkins Yup, the command remains the same. @paultopia just needs to `brew uninstall --force brew-cask` to clear out the old installation, then `brew update`.

**Comment by chrissimpkins** [comment]
@jawshooah :+1: perfect, thanks!

**Comment by jawshooah** [comment]
:beers:

**Comment by paultopia** [comment]
Awesome, thank you! 

--
Paul Gowder
http://paul-gowder.com

**Comment by chrissimpkins** [comment]
The OS X installation documentation was updated with this information.  Thank you very much for submitting this issue report (and to @jawshooah for the fix!).
