### ISSUE TITLE
intellij: highlighted array brackets disappearing partially

### ISSUE THREAD

**Issue by jorgheymans** [chrissimpkins/Hack#170]
Hi,

Using font-size 12 and up, the bottom part of array brackets disappear when highlighted (this is not the same as selected). Hoping the gif will explain all:

![arraybrackets](https://cloud.githubusercontent.com/assets/193792/12413958/d8687cbe-be92-11e5-8052-9f28f09e0b6f.gif)

This was happening in the .18 release already, still there in the .19. 

Changing the line spacing (set to 1.0) does not help.

**Comment by hrach** [comment]
https://github.com/chrissimpkins/Hack/issues/129

**Comment by jorgheymans** [comment]
interesting, so the problem appeared only in intellij 15 ...
