### ISSUE TITLE
Font redistribution package maintainers: tar.xz archives are now available

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#172]
@heliocastro requested tar.xz font archives for future Fedora releases.  These are now available as of the current [v2.019 release](https://github.com/chrissimpkins/Hack/releases/tag/v2.019).  They will be available on all future releases if this is helpful to other package maintainers out there.

cc: @alerque @legovini

**Comment by heliocastro** [comment]
Many thanks

**Comment by chrissimpkins** [comment]
@heliocastro my pleasure Helio.  The improvement in the compression ratio is significant

**Comment by chrissimpkins** [comment]
@heliocastro v2.020 of the Hack fonts is now available.  Please note that I made a slight modification to the tar.xz archive file path c/w the v2.019 release.

**Comment by heliocastro** [comment]
Done deal. I'm applying to put on the fedora mainline too, but for now
still on copr

Many thanks

[]'s

**Comment by chrissimpkins** [comment]
Excellent! Thank you!
