### ISSUE TITLE
Updating font cache... Couldn't determine full name for Khand-ExtraBold.ttf

### ISSUE THREAD

**Issue by anicake** [chrissimpkins/Hack#173]
```shell
[aniketd@skynet tag]$ sudo pacman -S ttf-hack
[sudo] password for aniketd: 
resolving dependencies...
looking for conflicting packages...

Packages (1) ttf-hack-2.018-2

Total Download Size:   0.39 MiB
Total Installed Size:  1.54 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 ttf-hack-2.018-2-any                                                                                                  396.1 KiB  88.0K/s 00:05 [########################################################################################] 100%
(1/1) checking keys in keyring                                                                                                                  [########################################################################################] 100%
(1/1) checking package integrity                                                                                                                [########################################################################################] 100%
(1/1) loading package files                                                                                                                     [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                               [########################################################################################] 100%
(1/1) checking available disk space                                                                                                             [########################################################################################] 100%
(1/1) installing ttf-hack                                                                                                                       [########################################################################################] 100%
Updating font cache... Couldn't determine full name for Khand-ExtraBold.ttf
Couldn't determine full name for Khand-Regular.ttf
Couldn't determine full name for Khand-SemiBold.ttf
Couldn't determine full name for Khand-Bold.ttf
Couldn't determine full name for Khand-ExtraLight.ttf
Couldn't determine full name for Khand-Light.ttf
Couldn't determine full name for Khand-SemiLight.ttf
Couldn't determine full name for Khand-Black.ttf
done.
```

**Comment by chrissimpkins** [comment]
There seems to be an issue with your post-install font cache update.  Here is the [post install work](https://projects.archlinux.org/svntogit/community.git/tree/trunk/ttf-hack.install?h=packages/ttf-hack) that the package is performing:

```
post_install() {
  echo -n "Updating font cache... "
  fc-cache -s
  mkfontscale /usr/share/fonts/TTF
  mkfontdir /usr/share/fonts/TTF
  echo "done."
}
```

While we endorse their use, we do not release or manage these platform specific packages and support questions should be directed to the package maintainer.  Lukas Fleischer appears to be the maintainer on the Arch distro.  Here is the URL for the package:

https://www.archlinux.org/packages/community/any/ttf-hack/

Perhaps this is a problem with fonts contained in a Google fonts package on Arch based upon the comments in [this thread](https://aur.archlinux.org/packages/ttf-google-fonts-git/?comments=all).  See the comment with header `poincare commented on 2014-08-29 23:02`.

It would be helpful if you could provide an update on what you find here in case this is an issue for other users.

**Comment by anicake** [comment]
Hey,

Thanks for pointing me in the right direction.
While trying to get in touch with Lukas Fleischer, I also noticed on

https://www.archlinux.org/packages/community/any/ttf-hack/

that it has been "Flagged out-of-date on 2016-01-18". So I won't be able to raise a bug. Just registered for an account on the bug tracker. :) I'm new to Arch (5 days) coming from 6 years on Ubuntu and Mac before that.

About Google fonts, yes it's the same as what I got, but that one is mentioned on AUR. I haven't dared to enable AUR yet.

Will post an update when I get in touch with him.

Thanks very much.

**Comment by chrissimpkins** [comment]
Let me know what you find.  The packages are fortunately/unfortunately out of my hands.  There are manual install instructions on our README file in the interim.  Sorry for the troubles.

**Comment by anicake** [comment]
Final update:

Lukas wrote back to my email stating in positive that the bug was in the Khand font alone, which is part of the Google fonts pack.

I'm utterly sorry for bothering with this over here. I should have thought a little more about the message on the console without jumping to this conclusion just because I saw it while installing ttf-hack.

Thanks very much for your patience @chrissimpkins . And super thanks for the awesome font! I'm switching over from the famed Source Code Pro.

**Comment by chrissimpkins** [comment]
It's no problem at all Aniket.  I'm glad that it is resolved.  Rest assured there will be others who have a similar problem and now we have a solution.  Poke Lukas to update the Hack fonts package too! ;)
