### ISSUE TITLE
README.md: a typo

### ISSUE THREAD

**Issue by van-de-bugger** [chrissimpkins/Hack#174]
Spellchecker complains on README.md line 34:

    analphabetic -> an alphabetic, an-alphabetic, alphabetical

Looks like a typo... It seems "an" should be dropped.

**Comment by chrissimpkins** [comment]
Thanks for the suggestion (and for the thorough review of the docs!) @van-de-bugger.  Analphabetic characters are those that fall outside of the alphabet set.  They include glyphs like the punctuation.  I will take a look through to confirm that I used the term in the proper context.

**Comment by van-de-bugger** [comment]
Ah, I see. Probably "non-alphabetic" would be better choice? It does not confuse spellchecker and non-native English readers.

**Comment by chrissimpkins** [comment]
The docs need a thorough once over for revisions.  I will include a change.  Thanks for the recommendation!
