### ISSUE TITLE
Hack Regular displaying incorrectly [OS X]

### ISSUE THREAD

**Issue by tjahjono** [chrissimpkins/Hack#175]
I attempted to upgrade to Hack 2.019 on a Mac and this is what happens with Hack Regular. 

![screen shot](https://cloud.githubusercontent.com/assets/756116/12740286/5f3ac8ba-c937-11e5-97ec-0c863e240314.png)

Bold, Italic, and BoldItalic displays correctly. Hack 2.010 was previously installed, and I removed it before installing the current version.

**Comment by chrissimpkins** [comment]
Strange.  Sorry you are having troubles Randy.  Let's see if this is a corrupted font cache issue.  Do you mind uninstalling Hack by right clicking on the Hack name in Font Book and selecting `Remove "Hack" family`, then execute these commands to clear your font caches:

```
$ sudo atsutil databases -remove
$ atsutil server -shutdown
$ atsutil server -ping
```

When you perform the shutdown, you should receive the message `ATSServer shutdown` and when you perform the ping you should receive the message `ATSServer is running`.

Then try the Hack install again.

Let me know if this does the trick.

**Comment by tjahjono** [comment]
That fixed it. Thanks!

**Comment by chrissimpkins** [comment]
Excellent! Glad to hear that.  Let me know if you come across any other problems.
