### ISSUE TITLE
Include a link to OSFontPack in readme.md (section Windows)

### ISSUE THREAD

**Issue by texhex** [chrissimpkins/Hack#177]
Disclaimer: I’m the creator of OSFontPack.

I would like to propose to include a link to [OSFontPack](https://github.com/texhex/OSFontPack) in readme.md, section *Windows*.

OSFontPack is a setup for (currently) four open source fonts. I think “normal” Windows users will prefer a setup over the manual installation which might result in more users to use Hack.

The setup itself:
* Is also open source (MIT licensed)
* Repository is on GitHub
* The installer is written in InnoSetup which can be downloaded for free
* It’s completely generic, it should work from Windows 7 to Windows 10 (Windows 8 and 8.1 weren’t tested so far)
* Does not include any adware
* It features a selection which fonts to install, so the user can select to install only Hack, ignoring the other three fonts

Thank you.

**Comment by chrissimpkins** [comment]
Thanks for this Michael!  Let me give it a try on a Windows box and then let's see if we can work it into the documentation as a resource for Windows users.  Do you intend to keep this project current with Hack releases? 

I really appreciate the inclusion of the typeface in your project.

**Comment by texhex** [comment]
You're welcome. Yes, I intend to keep the project current if I notice a newer release. The creation is rather simple: 
* Download new Hack TTF fonts and add it to a new folder
* Update the setup source to look into this folder and increment the version number 
* Compile. 
* Push
* Add release. 
* Done. 

On the user side, I'm using SHA1 hashes of the file so the new setup will detect that the files are different than the ones installed and copy them (Might require a restart because Windows loves to lock fonts).

**Comment by chrissimpkins** [comment]
@texhex Thanks Michael :+1:

**Comment by texhex** [comment]
In case you didn't test it already, I just released 1.1.2. As I have learned today, there is font "management" software out there that removes a font by deleting its registration, but keeps the font in \windows\fonts. 

The old setup would not have installed this font because the file was already present. The new release also checks if the font registration is valid and if not, installs the font.

**Comment by chrissimpkins** [comment]
@texhex thank you! hope to get to it this weekend

**Comment by chrissimpkins** [comment]
Quick update.  Haven't forgotten.  Still on the list.

**Comment by texhex** [comment]
Thank Chris, no rush. 

After all, we are talking about a project that didn't exists some weeks ago, from a guy you don't know, for an operating system you don't use.

**Comment by chrissimpkins** [comment]
Haha! Still important and greatly appreciated though.

**Comment by texhex** [comment]
I just have released [v1.2.0](https://github.com/texhex/OSFontPack/releases/tag/v1.2.0) mostly because there was a new release of Roboto. 

I also rechecked which problems reported in #152 the setup program can and will solve. The main reason for these problems seems to be that the information inside the registry and the files installed to C:\Windows\Fonts are different. To prevent this, OSFontPack will:

- Use a SHA1 hash to ensure that the files we want to install are there or not. So damaged files (e.g. with one byte difference) will be detected and overwritten
- All FONTNAME_0, 1, 2... .ttf (those created by the Fonts applet when the files are locked) will be deleted on installation. Of course, this will only happen for the fonts the user has selected to install, e.g. Hack_*.ttf when "Hack" is selected
- Any installation of a font file that can't be executed directly because the font file is locked will be replaced upon restart. This ensures that what should be installed is actually installed.
- During the installation, the FontCache service is stopped and later on restarted. This should prevent cache corruption.

Thinking about other defects in terms of fonts, these two scenarios are currently not fixed:

- If, for whatever reason, a the name of a font is changed, the old name will remain in the registry. For example, if "Hack Italic" was once called "Hack Oblique" this old name will remain in the registry and if the filename between Oblique and Italic is different, you have an orphaned font registration. The only way to fix this would be to scan through the \Fonts section of the registry and delete everything starting with "Hack". However, there might be somewhere a font called "Hackfleisch" which we would delete in this case as well. 

- If the cache of the "FontCache" service becomes corrupted, we would need to delete several files it uses. Because Microsoft has not documented any “safe” way to delete this files (that is guaranteed to work), I currently didn’t include it.

**Comment by chrissimpkins** [comment]
> I also rechecked which problems reported in #152 the setup program can and will solve

:+1: Fantastic!

Thanks for this additional information.  This is extremely helpful.  Hack Italic did begin as Hack Oblique so this could be an issue for some early users.  I absolutely positively without fail will make sure that this information makes it to the README this week ;)  Seriously, it is at the top of my TODO list along with the new package.json PR info and some other documentation odds and ends.  

Thanks so much for all of your help.

**Comment by texhex** [comment]
You're welcome Chris!

**Comment by texhex** [comment]
Just a follow up: For the "Oblique became Italic" issue there is already fix in OSFontPack:

```
Delete special files
;Hack: Version 2.10 has used "Oblique" instead of "Italic" so these files should be deleted when hack is selected
Type: files; Name: "{fonts}\Hack-BoldOblique.ttf"; Components: {#hack_component}; 
Type: files; Name: "{fonts}\Hack-RegularOblique.ttf"; Components: {#hack_component}; 
```
This ensure the deletion of the files, but not inside the registry. I assume everybody that uses 2.10 has in the meantime updated to a newer version which already used the "Italic" name.

Finally, the list of "Known Windows font handling issues" (see above) is now also documented in the OSFontPack repository: [FontInstallationIssues.md](https://github.com/texhex/OSFontPack/blob/master/FontInstallationIssues.md)

**Comment by chrissimpkins** [comment]
Thanks so much for doing all of this.  I know that this is an enormous effort.  It is greatly appreciated!!

**Comment by texhex** [comment]
My pleasure Chris, glad if the project will be of use. 

And in terms of "amount of hours spend on an open source project you never receive a single cent for": You are waaayyy ahead of me ;).

**Comment by chrissimpkins** [comment]
I added a new paragraph in the Windows install section about your tool.  Thanks again for developing and maintaining this Michael. This is a great resource for our users.  It's greatly appreciated (and much needed on the Windows platform!!).

https://github.com/chrissimpkins/Hack#windows

**Comment by texhex** [comment]
Thanks Chris, my pleasure!

**Comment by chrissimpkins** [comment]
Added you to our contributors list.  Thanks so much for all of the Windows help.  It is greatly appreciated!
