### ISSUE TITLE
Add Hack to npmjs.com?

### ISSUE THREAD

**Issue by jakubzitny** [chrissimpkins/Hack#179]
Hey, I am not sure you might be interested in this, but if Hack was available from `npmjs.com` people would be able to include it in their `package.json` as a dependency and have it automatically in their Javascript apps.

For example we have an Electron app and now we need to include these fonts in our repository. If available we'd just `install --save` it and it's done.

I can send a Pull request with suggested functionality, with `package.json` if you'd like.

**Comment by chrissimpkins** [comment]
I would be glad to merge such a PR. Fire away.  Thanks!

**Comment by jakubzitny** [comment]
I've linked a PR.

I have pushed it to https://www.npmjs.com/package/hack-font. If you create a account there I will set you as main collaborator so you can `npm publish` everytime you guys have a new release :)

**Comment by philwareham** [comment]
Hi, just a small note that [the version on Packagist](https://www.npmjs.com/package/hack-font) is slightly out of date. Any chance of syncing it up at some point? Cheers!

**Comment by chrissimpkins** [comment]
@philwareham 

We are close to a new major release and an update is definitely on its way via npm.  The previous npm package was a contribution to the project by @jakubzitny and we have not maintained the versioning/releases current with Hack as of v2.020 (as you rightly point out).

See IR https://github.com/source-foundry/Hack/issues/284 for information about the transition.  We are linking the jsDelivr CDN releases of our web fonts to npm as part of this new major release.

I anticipate that this will be ready for release and available on npm in a couple of weeks.  We do intend to participate in the maintenance of the npm releases on our end in the future so you should always have fresh Hack releases down the road.  

cc: @burodepeper

**Comment by philwareham** [comment]
@chrissimpkins that's super news, thanks!

**Comment by chrissimpkins** [comment]
@philwareham stay tuned! lots of changes planned over the v3.x releases.  It will be helpful to have these package managers current with updates.  Thanks for pointing this out.  I didn't realize that v2.020 was not available...
