### ISSUE TITLE
powerline glyphs missing for bold

### ISSUE THREAD

**Issue by colinsullivan** [chrissimpkins/Hack#181]
Using Powerline, iTerm2 is set to display bold text using the bold font.

You can see here, the non-bold LN glyph in the "inactive" vim split is displayed, but the bold one is not.

![screen shot 2016-02-25 at 11 26 52 am](https://cloud.githubusercontent.com/assets/94535/13331523/b67b2ec0-dbb2-11e5-9b8e-1a173593da74.png)

Related to #33.

**Comment by colinsullivan** [comment]
Changed issue, spans more than just this one glyph.  Putting vim into paste mode:

![screen shot 2016-02-25 at 11 40 17 am](https://cloud.githubusercontent.com/assets/94535/13331941/91e575c8-dbb4-11e5-9511-0914e15c19de.png)

This is using a pretty standard setup of [vim-airline](https://github.com/vim-airline/vim-airline)

**Comment by chrissimpkins** [comment]
Mind trying these development build fonts?  I patched the Powerline glyphs into the bold set:

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV02172016

These will show as build v2.020 DEV02172016.

**Comment by colinsullivan** [comment]
Beautiful!  Looks great.

Thank you.

**Comment by chrissimpkins** [comment]
Great!  The set you are using is a completely functional but not finished set of changes in the v2.020 release.  We are working on the box drawing glyphs and will include these changes in all sets (the development set only includes changes in the regular set).  

Should be out reasonably soon'ish :)

**Comment by faceleg** [comment]
Works for me too, thanks all!

**Comment by chrissimpkins** [comment]
@faceleg ty!

**Comment by chrissimpkins** [comment]
Fixed as of v2.020 release which is now available.  Please let us know if you have any further issues.
