### ISSUE TITLE
vim-devicons nerd fonts support

### ISSUE THREAD

**Issue by samadivk** [chrissimpkins/Hack#187]
I would like to suggest adding the [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) icons to Hack.
As a daily user of [vim-devicons](https://github.com/ryanoasis/vim-devicons), Hack and my custom ZSH theme that makes use of the nerd-fonts icons, I can highly recommend them, and think this would make a great addition to the already brilliant Hack.

I am willing to provide patched versions of the fonts if that is necessary.

Thank you for all the amazing work on this wonderful font.

Samadi

**Comment by samadivk** [comment]
Ooops.... I just had a closer look at the nerd-fonts github repo, and they have a pre-patched version of Hack there already. It may still be something to look into integrating directly into Hack, as it reduces the time it takes to get to the end user, however it's not particularly necessary.

Sorry for not doing proper research first.
Samadi

**Comment by chrissimpkins** [comment]
no worries! enjoy
