### ISSUE TITLE
Ubuntu package not found

### ISSUE THREAD

**Issue by rahilwazir** [chrissimpkins/Hack#189]
When trying to install through package manager:

```
$ sudo apt-get install fonts-hack-ttf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fonts-hack-ttf
```

**OS**: Ubuntu 15.10, 64bit

**Solved:**

Add following to `/etc/apt/sources.list`:

```
deb http://us.archive.ubuntu.com/ubuntu xenial main universe
```

Then

```
$ sudo apt-get update
$ sudo apt-get install fonts-hack-ttf
```

Could you please add it to the readme?

**Comment by chrissimpkins** [comment]
Happy to.  Thank you very much for reporting it.  Do you happen to know what Ubuntu releases this applies to?

cc : @alerque

**Comment by rahilwazir** [comment]
Well at least it worked on `15.10`, sorry not sure about the other releases, but it should work

**Comment by chrissimpkins** [comment]
Let's poke the maintainer on Ubuntu to get more comprehensive information.  Can you point to where you found this?

**Comment by rahilwazir** [comment]
I followed the steps from here [xenial/all/fonts-hack-ttf](http://packages.ubuntu.com/xenial/all/fonts-hack-ttf/download) and see the sidebar section for maintainer [here](http://packages.ubuntu.com/xenial/fonts-hack-ttf)

**Comment by chrissimpkins** [comment]
Will have a look.  Thanks @rahilwazir

**Comment by chrissimpkins** [comment]
added to readme along with the previous link to manual install instructions.  Thanks for the report.
