### ISSUE TITLE
Same font style for cyrillic and latin

### ISSUE THREAD

**Issue by rosolko** [chrissimpkins/Hack#192]
Hi, 

Got a question - is it correct that font look like that:

In preview(playground) on site:
![att_63](https://cloud.githubusercontent.com/assets/11458319/14147292/7bec6c2c-f6a3-11e5-89d3-318cc9a2a214.png)

In editor after font installation:
![att_62](https://cloud.githubusercontent.com/assets/11458319/14147297/83c8f050-f6a3-11e5-8d59-bcfbeeca92f2.png)

Thanks.

**Comment by chrissimpkins** [comment]
Those webfont characters are definitely not from the Cyrillic set in the first screenshot.  Let me confirm that we are using the webfonts with the full character set on the Font Playground site.

**Comment by rosolko** [comment]
![1](https://cloud.githubusercontent.com/assets/11458319/14151806/77d7bf14-f6b8-11e5-81cb-743e8c7bb71d.png)
![2](https://cloud.githubusercontent.com/assets/11458319/14151809/7a861f76-f6b8-11e5-8c98-27dd32ee42ca.png)

**Comment by rosolko** [comment]
Additional: I create simple page and use `rel="stylesheet" href="//cdn.jsdelivr.net/font-hack/2.019/css/hack-extended.min.css">` for load font and here a results (regular, monospace):
![2](https://cloud.githubusercontent.com/assets/11458319/14152161/5e2ce3e4-f6ba-11e5-8890-119e6a77148d.png)

![1](https://cloud.githubusercontent.com/assets/11458319/14152156/59cd01c6-f6ba-11e5-9b73-65e740b26872.png)

**Comment by chrissimpkins** [comment]
Thanks for reporting it and for all of the additional data.  I will take a look into it. I'm not certain why our glyphs are not appearing.

**Comment by chrissimpkins** [comment]
Do you mind confirming whether you see this with the following as well:

`href="//cdn.jsdelivr.net/font-hack/2.01/css/hack-extended.min.css"`

**Comment by rosolko** [comment]
@chrissimpkins Yes, confirmed. Same behavior.

**Comment by chrissimpkins** [comment]
Bizarre.  Let me take a look at them to see if the Cyrillic glyphs were removed during the conversion to web fonts for some reason.  Shouldn't be the case for the extended set.  They should have the same character set as our desktop releases.

**Comment by chrissimpkins** [comment]
I can verify that the Cyrillic glyphs are included in our v2.019 release of our webfonts.  I'm not certain why you are seeing this behavior.  I will be pushing the v2.020 release in the next week and we will test with these new builds.

**Comment by chrissimpkins** [comment]
v2.020 release will be live this week.  Let’s take a look at this again once we have a new set of web fonts.

**Comment by rosolko** [comment]
@chrissimpkins Test it. Looks well now. Thanks. I think we can close this issue, if no one doen't have this problem after upgrade. Are we?

**Comment by chrissimpkins** [comment]
Strange. I don't know what the issue was but we will always take a point in the win column!

Will close.  Feel free to reopen if any new issues.
