### ISSUE TITLE
Windows redistribution packages vs dedicated font installer/upgrader

### ISSUE THREAD

**Issue by salarmehr** [chrissimpkins/Hack#194]
May you add this to choco so make updating automatic. similar to https://chocolatey.org/packages/EnvyCodeR

Thanks.

**Comment by chrissimpkins** [comment]
Interesting that you submit this Reza.  @texhex @burodepeper @davelab6 and I have been discussing our approach to Windows redistribution over the last day and are actively engaged in a conversation now.  Do you mind if I change your issue report to "Windows redistribution packages" or something like this?  We would like to obtain feedback from you and other Windows users (as well as users of package managers for fonts on other platforms) about your needs and the best approach?  

At the moment we are anywhere from a WIndows specific compiled executable installer to a typeface manager tool (any typeface) that works cross-platform.  Thanks for the thread to get this conversation started!

**Comment by texhex** [comment]
As a side note: There is an choco package already (not created by the Hack team): https://chocolatey.org/packages/hackfont

**Comment by chrissimpkins** [comment]
@salarmehr Reza can you confirm that the existing chocolatey package that @texhex linked works for you?

**Comment by salarmehr** [comment]
Yes, it works well.

**Comment by chrissimpkins** [comment]
@salarmehr Reza (and the general Windows user community), what is your thought about a dedicated compiled Windows installer for our fonts?  There are a number of problematic technical issues with font upgrades on Windows that can be addressed in this fashion and we are debating whether this is the best approach to address it.

**Comment by salarmehr** [comment]
Personally, I think installing a program to keep a font up to date is somehow over-killing. Before finding choco, I was thinking of developing a tool to update local fonts similar to what bower do. Unfortunately I am too busy right now. I suggest extending your idea and develop a font package manager. It can be cross-platform.

**Comment by davelab6** [comment]
It seems bower is widely used for managing self-hosted web fonts. Having a desktop GUI for bower font packages would kill 2 birds with 1 stone :)

**Comment by chrissimpkins** [comment]
These are helpful suggestions.  I know of bower but don't know details about how it manages packages.  A broad solution would need to address both: (1) distribution of the physical files (because its simply onerous and outdated to manually download and install); (2) provide the capacity to manipulate the system in order to address OS font caching and cleanup of prior installs.  The former is simple.  The latter will prove more challenging to achieve with any cross-platform approach.

We've done some digging and there doesn't appear to have been much developed to address this and I am guessing that this is because either (1) fonts aren't frequently updated and do not commonly warrant upgrades and/or (2) users don't frequently update fonts irrespective of availability.  Thoughts about these issues?  We like to think that there is some marginal benefit to our new releases, and perhaps that is the case for some out there, but maybe this is not important to the general libre typeface user.

**Comment by chrissimpkins** [comment]
> maybe this is not important to the general libre typeface user

I believe that we need the answer to this issue before we invest time in a general purpose tool.

**Comment by davelab6** [comment]
I think of libre fonts like libre software was for me in the late 90s....
kind of a new way of doing things, so not fitting very well into the
standard practices that made sense for proprietary software. Eg, Debian had
apt-get in the 90s, long before Windows Update and the App Store.

Most libre fonts are updated much more frequently than proprietary ones.

**Comment by burodepeper** [comment]
> Most libre fonts are updated much more frequently than proprietary ones.

@davelab6 Do you have any idea what the adoption rate of font updates is? (I know @chrissimpkins is looking for some stats considering Hack)

As a naive user, I've always _assumed_ that typefaces are thoroughly tested before release (I mean, they are one of the few design-related things that can be objectively measured for okayness), and don't need updates. Besides Hack, I've never even updated a typeface, which is primarily because I am not even aware of there being updates. I have no desire to _follow_ typefaces via Twitter for instance.

@chrissimpkins Updates to Hack have been either character set extensions or bug fixes. Could you approximate the balance between those two? Just curious about this.

**Comment by davelab6** [comment]
No, but I get a lot of bug reports for things that have already been fxied.

Libre fonts testing is a lot less stringent than proprietary fonts; that's
why they get updated more.

**Comment by burodepeper** [comment]
> No, but I get a lot of bug reports for things that have already been fxied.
I'm almost naive enough to assume nobody updates their fonts solely based on that quote.

**Comment by salarmehr** [comment]
@burodepeper Fonts are generally updated similar to softwares and code libraries but in a longer period. 
For years there were no bower, if bower creator thought this is due to uselessness of such tool no bower would be created. 

I my system almost 500 font is installed, manually updating them is onerous, even I do not know if there is newer version available to updated them manually, at the same time most of them has newer version. 

Unicode is huge. most font creator add new glyphs progressively that needs a tool for distribution. 

bower code is open so only some simple modification should be required to create a font manager tool.

**Comment by chrissimpkins** [comment]
@burodepeper 

With respect to the font file only updates in the repository, they have involved character set extensions, glyph curve modifications (shape, position, size), OpenType table changes (e.g. vertical metrics changes), and hinting modifications.  Some are to address what would properly be considered a bug, some have been aesthetic changes, and some have been an attempt to design/tune the font to the intended text body (source code), display location (screen), and commonly used size (much smaller than for reading text display for most users).    Of these, adjustments to existing glyphs have been a much greater proportion of all changes than extension of character sets in the typeface.

Outside of the fonts themselves, releases also include developer (e.g. autohinting scripts) and user (e.g. line spacing adjustment scripts) utilities.  These are added and modified over time as well.

**Comment by burodepeper** [comment]
> This statement is not entirely correct.

I over-simplified things a bit, but I think we're on the same page.

> Of these, adjustments to existing glyphs have been a much greater proportion of all changes than extension of character sets in the typeface over the release cycle.

Okay, so updates are more about refinement than about expansion. That's simply good to know.

**Comment by chrissimpkins** [comment]
@salarmehr :

> On my system, almost 500 fonts are installed, manually updating them is onerous, even I do not know if there is newer version available to updated them manually, at the same time most of them has newer version. 

This is a perfect example of why a package manager is essential if you intend to update fonts.  Would you update all 500 if a tool followed the package manager style and permitted a simple workflow like:

`fonter update && fonter upgrade all`

?

**Comment by chrissimpkins** [comment]
Work on a Windows installer for Hack is underway.  Development is being led by @texhex.  We will let you know when it is ready for use.  Here is the repository if you would like to follow the progress or comment on the tool.

https://github.com/source-foundry/Hack-windows-installer

**Comment by chrissimpkins** [comment]
@salarmehr Reza, as we've researched this issue, we found that there is a Nuget package for Hack on Windows as well.

**Comment by texhex** [comment]
@salarmehr: [Version 1.0.2](https://github.com/source-foundry/Hack-windows-installer/releases/tag/v1.0.2) of *Hack Windows Installer* is finished. It would be great if you could have a look.

**Comment by chrissimpkins** [comment]
@texhex does this include v2.019 or the new v2.020 releases?

**Comment by texhex** [comment]
@chrissimpkins These are still the v2.019 because this is still your "official" release version. But I will create version 1.1.0 as soon as v2.020 is out.

**Comment by chrissimpkins** [comment]
@texhex perfect thanks!  Will let you know when we are ready to release v2.020.  Coming in the next day or two.

**Comment by chrissimpkins** [comment]
v2.020 builds are ready and available in Releases

**Comment by chrissimpkins** [comment]
Would greatly appreciate any / all feedback on the Windows installer approach.  Please give it a shot and let us know what you think.

https://github.com/source-foundry/Hack-windows-installer

**Comment by texhex** [comment]
[Hack Windows Installer](https://github.com/source-foundry/Hack-windows-installer/releases/latest) has been updated and will now install Hack v2.020.

**Comment by chrissimpkins** [comment]
@texhex Tex, we are at a release version, recommend this tool by default to Windows users, and have it linked from releases, main README, and INSTALLATION docs.  Anything else that we need this thread to address?

**Comment by texhex** [comment]
@chrissimpkins No, I think we are good. The tool @salarmehr proposed is on our todo list (Project "displaj").

**Comment by chrissimpkins** [comment]
:+1:
