### ISSUE TITLE
Hack v2.020 release

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#197]
The Hack v2.020 release is in progress.  [Changelog](https://github.com/chrissimpkins/Hack/blob/master/CHANGELOG.md)

- [X] create hinted ttf builds
- [X] create hinted otf builds 
- [X] submit web font PR to jsDelivr (https://github.com/jsdelivr/jsdelivr/pull/11285)
- [x] push release files to release build directories
- [x] build release archives
- [x] push release archives to v2.020 tagged release
- [x] update README with v2.020 links (desktop files)
- [x] update README with v2.020 web font jsDelivr CDN link
- [x] update type specimen with new web font builds
- [x] update sourcefoundry.org website with v2.020 links
- [x] update [Windows installer](https://github.com/source-foundry/Hack-windows-installer) with v2.020 release files
- [x] review new Windows installer documentation
- [X] update README documentation to include new Windows installer as Windows default install approach
- [x] update sourcefoundry.org website documentation with new Windows installer as default for Win users

Please poke your friendly platform package manager so that they are aware.  

Enjoy!

**Comment by chrissimpkins** [comment]
@texhex v2.020 ttf release builds are now available for the Windows installer update.

**Comment by gergelypolonkai** [comment]
The otf release contains some MAC-related files. Is that really needed, or just left there?

**Comment by chrissimpkins** [comment]
what kind of files and which archive?

**Comment by texhex** [comment]
@chrissimpkins 
[Hack Windows installer](https://github.com/source-foundry/Hack-windows-installer/releases) has been updated to install Hack v2.020.

**Comment by chrissimpkins** [comment]
@texhex 👍  Will try to update the documentation tonight.  Thanks for all of your work on this Tex.

**Comment by texhex** [comment]
@chrissimpkins My pleasure.

**Comment by chrissimpkins** [comment]
@texhex Do you mind having a look at the new Windows installer documentation section when you have a chance in order to confirm that it is accurate.  I pushed this to a documentation branch linked here:

https://github.com/chrissimpkins/Hack/tree/documentation#windows

Will merge once you've had the chance to review this.  

For future reference, the link to the installer will require a manual update on the README here each time you push a new release.

**Comment by texhex** [comment]
I checked the documentation and did some changes, feel free to change them again if it made the flow worst. PR: https://github.com/chrissimpkins/Hack/pull/198

**Comment by chrissimpkins** [comment]
README updated with documentation about new Windows installer.

**Comment by chrissimpkins** [comment]
The v2.020 release is now complete.  Thanks to all for the issue reports and hard work to make this release happen.
