### ISSUE TITLE
Fedora 23: Only bold and bold italics version available

### ISSUE THREAD

**Issue by uajain** [chrissimpkins/Hack#202]
I really liked the hack font when I tried the font here: http://sourcefoundry.org/hack/playground.html

I went ahead and installed on my Fedora 23 machine as instructed on the readme file but I get only "bold" and "bold italics" flavors of the font. Why not regular?
![screenshot from 2016-04-28 19-34-54](https://cloud.githubusercontent.com/assets/8775041/14888648/f9954450-0d78-11e6-8f25-87d277fd0143.png)

**Comment by chrissimpkins** [comment]
How did you install? Did you use the Fedora package manager?

**Comment by uajain** [comment]
@chrissimpkins As stated in the Readme file here: https://github.com/chrissimpkins/Hack#linux--bsd

i.e. 
$ dnf install dnf-plugins-core
$ dnf copr enable heliocastro/hack-fonts
$ dnf install hack-fonts

**Comment by chrissimpkins** [comment]
@heliocastro maintains that package.  Can I put the two of you in touch to look into the problem?  

In the interim, try to manual install approach for Linux listed on the README.  Sorry for the troubles.  Will do what I can to help but the project doesn't maintain the packages on Linux distros.

**Comment by uajain** [comment]
Sure.
Let me try the manual install and see if that works for me.

**Comment by uajain** [comment]
I took a peek at /usr/share/fonts/hack directory and  Hack-Regular.ttf was present there. 
I ran sudo fc-cache -f -v which refreshes the font's cache. Now the regular flavor worked as expected.
![screenshot from 2016-04-29 00-33-22](https://cloud.githubusercontent.com/assets/8775041/14897964/03b60a5e-0da2-11e6-835c-eb3d8c9bfdec.png)

**Comment by chrissimpkins** [comment]
@uajain interesting the package manager should take care of this for you.  @heliocastro can you verify that it does? if not I will update docs with this information.

**Comment by chrissimpkins** [comment]
@uajain Umang, can you confirm that the Fedora package installed the fonts and that you only needed to perform 

```
sudo fc-cache -f -v 
```

in order to make all font variants visible?  I will add this information to the Fedora installation instructions if this manual task is necessary.

Thanks much for the report.

**Comment by chrissimpkins** [comment]
Looks like we are not going to receive a response here.  Will close this issue as resolved and will point users to the font cache clean command if it arises again.  Thanks for the report.

**Comment by Paviluf** [comment]
I just tried Hack from this [copr](https://copr.fedorainfracloud.org/coprs/heliocastro/hack-fonts/) repo and I needed to use `sudo fc-cache -f -v` to have access to the regular variant in Sublime text.
