### ISSUE TITLE
Simplify the README

### ISSUE THREAD

**Issue by burodepeper** [chrissimpkins/Hack#203]
As discussed on Slack, I suggest to simplify the main `README.md` by splitting it up into several documents, and focus on clarity in the main document, opposed to the current inclusion of practically everything.

### Goal
Create a `README.md` that covers the basics and directs users to more in-depth documentation if they want to know more. Ideally, the document shouldn't need an index.

#### Current "issues"
- The focus on showcasing the typeface is rather large; there's already a proper website for that.
- There are a lot of download and installation instructions that are rather specific. The most common forms of installation (and mishaps) should be included; all advanced instructions can be moved to separate documents.

#### Additional ideas
- Add a section that links to common and/or current issues

**Comment by chrissimpkins** [comment]
Working branch: https://github.com/chrissimpkins/Hack/tree/readme

👍

**Comment by burodepeper** [comment]
See #204 for my current work in progress.

**Comment by chrissimpkins** [comment]
@burodepeper This looks great David.  The fat is trimmed and appropriately stored away in the INSTALLATION.md document.  Some of the links are not working and we will fix those.

**Comment by chrissimpkins** [comment]
merged to `readme` branch.

**Comment by chrissimpkins** [comment]
We will need to cleanup the package manager info in the current version of the README file.  Users will need the package names for each platform (which differ on each platform).

**Comment by chrissimpkins** [comment]
Pushed some minor modifications to the README file in the readme branch.  We will need to discuss how best to include the information on the Fedora/CentOS package managers.  I like the concise list style, but on these distros it is necessary to use multiple commands.  I think semicolon delimited commands are going to be too long to fit on the page in one line.  Thoughts?

**Comment by chrissimpkins** [comment]
Also, it looks like you removed the image for the Font Playground.  I think that it is helpful to provide a way for users to jump to the FP in order to try it before they commit to a download.  We could add this as a text link along with the others in the paragraph prior to the specimen image.

**Comment by burodepeper** [comment]
> Also, it looks like you removed the image for the Font Playground. I think that it is helpful to provide a way for users to jump to the FP in order to try it before they commit to a download. We could add this as a text link along with the others in the paragraph prior to the specimen image.

Yep, removed with the ultimate purpose of more clearly separating the README from the website. I'm not opposed to including a text link. I think it would be overall a good idea to very clearly point users that want to _see_ Hack to the website, and imagine the README as the _technical_ portal.

**Comment by chrissimpkins** [comment]
:+1:

**Comment by chrissimpkins** [comment]
@burodepeper @texhex added line comments to the @texhex PR https://github.com/chrissimpkins/Hack/pull/207 .

**Comment by chrissimpkins** [comment]
@texhex PR #207 was merged to `readme` branch.  I will have a detailed look through the new files this week and we will merge to master.  Feel free to weigh in on any other outstanding issues over the course of the week.  We can continue to modify for additional clarity over time.  Thanks to both of you for all of your work on this.

**Comment by chrissimpkins** [comment]
@heliocastro we are updating the README docs and moving some of the details about the packagers to a separate doc page.  Can we assume that the instructions for Fedora > 23 is appropriate for most Fedora users at this stage?  I am going to modify the README to only include the package manager name and the package name.  @burodepeper moved the detailed instructions (which will remain) to a separate INSTALLATION.md file under the docs directory in the repository.  This is all in the readme branch if you happen to have any feedback for Fedora and CentOS user instructions.  Thanks in advance.

**Comment by chrissimpkins** [comment]
@burodepeper @texhex pushed edits to master branch.  I think that we can safely close this unless you have further edits.  Please reopen if you want to continue work in this thread.
