### ISSUE TITLE
Letter "a" Size 14 bold, windows JetBrains products

### ISSUE THREAD

**Issue by aplab** [chrissimpkins/Hack#208]
![clip2net_160511151225](https://cloud.githubusercontent.com/assets/4007240/15177848/b48b1a52-178b-11e6-9d8f-e0cbdda46d6d.png)

I do not know how to explain, see the attachment

**Comment by chrissimpkins** [comment]
Thanks much for the report.  Looks like a hinting problem.  Can you verify that you don't see this at other sizes?

**Comment by chrissimpkins** [comment]
and also to confirm, you are using the ttf files?

**Comment by aplab** [comment]
I use ttf
windows "cleartype" included

**Comment by chrissimpkins** [comment]
thanks! I will look into it

**Comment by jorgheymans** [comment]
try adding -Dsun.java2d.font.scaler=t2k to your intellij startup options, it solved another windows specific issue (#129) for me .

**Comment by chrissimpkins** [comment]
@aplab can you confirm whether @jorgheymans recommendation above corrected this issue?
