### ISSUE TITLE
Small font sizes on high-DPI display

### ISSUE THREAD

**Issue by PlaidPhantom** [chrissimpkins/Hack#213]
Hi, I'm having an odd issue using Hack in Visual Studio on a high-res (24" 4K) monitor.  I prefer a smaller font size (about 8pt), but in VS the font seems to be distorted (vertically stretched, mostly).  It actually looks better (more like Hack, to me) if I set my font preference to 12pt and zoom my edit window down to 66%.

![fontdifferences](https://cloud.githubusercontent.com/assets/678150/16025246/d75a0542-318b-11e6-9e21-fb814159a98e.png)

**Comment by PlaidPhantom** [comment]
Okay, the latest windows updates seem to have fixed the issue.  Never mind!

**Comment by chrissimpkins** [comment]
Any idea what the problem was?

**Comment by PlaidPhantom** [comment]
Not really, sorry.  Since it seems to have been fixed by a Windows Update, I'm guessing it was some sort of Windows scaling or font rendering bug.  At the same time some (unrelated) scaling issues were fixed in SQL Server Management Studio, which is what initially prompted me to try it again.

**Comment by chrissimpkins** [comment]
No problem! Thanks for the feedback.
