### ISSUE TITLE
support for linux console

### ISSUE THREAD

**Issue by fommil** [chrissimpkins/Hack#218]
apologies if this is a total font-n00b question, would it be possible to get Hack as a bitmap console font (i.e. non-X). The bigger the better since today's laptop screens are ludicrously high resolution.

**Comment by davelab6** [comment]
> The bigger the better since today's laptop screens are ludicrously high resolution

I suspect that controlling the optical size of the font is outside the scope of the font; you need to set your framebuffer resolution to use pseudo pixels...

**Comment by fommil** [comment]
@davelab6 with console fonts, you have to generate them with the size baked in. e.g. Terminus.

**Comment by chrissimpkins** [comment]
There is unfortunately no simple conversion to a bitmap font.  This requires a complete redesign.  Sorry...

**Comment by fommil** [comment]
Interesting. No way to just render at a given resolution and then convert into the required format?

**Comment by chrissimpkins** [comment]
@davelab6 are you aware of any bitmap 'converter' style software?
