### ISSUE TITLE
Deja Vu Sans Mono for Powerline - Font Awesome icons skewed.

### ISSUE THREAD

**Issue by kaibacorp** [chrissimpkins/Hack#219]
Tried both Complete and Font Awesome patched versions of Deja Vu Sans Mono for Powerline, but both result in icons appearing squished/skewed.

Here is an example of fa-dashboard:

![fa-squished-icon](https://cloud.githubusercontent.com/assets/5510071/16909268/3e1159f4-4c97-11e6-913a-1d69d167b5ef.png)

**Comment by chrissimpkins** [comment]
Can you expand on the issue here?

**Comment by kaibacorp** [comment]
If it helps, this is in mate-terminal in neovim. Setting terminal font to Deja Vu Sans Mono for Poweline Nerd Font makes the Font Awesome icons appear as above. Setting font to regular Font Awesome makes the icons appear with the right width.

**Comment by chrissimpkins** [comment]
This sounds as though you need to submit the issue to the Nerd Fonts or Powerline repository.  I don't manage DejaVu Sans Mono with or without Powerline, nor do I manage a Font Awesome patched version of DJVSM.

**Comment by kaibacorp** [comment]
Ah my apologies, I submitted the issue to the wrong repo. Sorry!

**Comment by chrissimpkins** [comment]
No worries! good luck
