### ISSUE TITLE
Cyrillic set feedback wanted

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#22]
If there are any native speakers/writers out there using it, any input that you can provide on the character shapes, positioning, and appearance would be very helpful.

**Comment by retgoat** [comment]
Hey!
I'll try it

**Comment by chrissimpkins** [comment]
Great!  Let me know if there are any glyphs that appear incorrect. Thanks for your help.

**Comment by istarkov** [comment]
I've used this font, and cyrillic (i'm russian) look's nice and well.
But where is one typical error for Russian programmers - 
latin symbol "c" and russian "с" are placed on one keyboard button, and looks the same. 
Is it possible to change russian c glyph on something different?

**Comment by chrissimpkins** [comment]
@istarkov Thanks for the feedback.  

To clarify, you would like the Cyrillic c mapped to a different unicode position in the set so that you can use it on keyboards with Cyrillic key mapping? I'm not sure that I completely grasp the request.

**Comment by istarkov** [comment]
It's easy to make a mistake in Russian like
```javascript
let csomeVar = 'blabla';
console.log(сsomeVar);
```
Here second сsomeVar is has cyrillic `с` at the beginning.
And this is very often mistake because on keyboard latin `с` and russian `с` is on one button.
IMHO cyrillic `с` must be different like 0-o-O (zero - о - O) as you have in hack.

**Comment by chrissimpkins** [comment]
I see.  I am educating myself on Cyrillic key mapping and will get back to you on this one.  Let me see what I can come up with.

**Comment by retgoat** [comment]
@chrissimpkins,
I completely agreed with @istarkov. Difference between `c` (latin) and `с` (cyrillic) not an extremely important, but would be very helpful for russian users.

**Comment by chrissimpkins** [comment]
I re-read your question and I think that I misunderstood you the first time.  Are you asking to have the shape of the Cyrillic c glyph changed?  I thought you were asking to map it to a different unicode position.

**Comment by retgoat** [comment]
@chrissimpkins,
exactly. We'd like to see changed shape of Cyrillic glyph `c` like with `o` and `0` (zero). 
Thanks in advance.

**Comment by chrissimpkins** [comment]
I see.  Yes, that is definitely possible.  I added a new issue (#29) to address this and will leave this thread open for additional Cyrillic set suggestions.  

Thank you very much for the feedback @retgoat & @istarkov.

**Comment by retgoat** [comment]
Welcome! :)

**Comment by chrissimpkins** [comment]
I'll let you know when there is a build ready with this change.

**Comment by softkot** [comment]
Installs Hack as primary Intelij IDEA editor font and it looks great, found no issies with cyrillic set.

Thanks for your work.

**Comment by retgoat** [comment]
Btw, I'm using it with Sublime 3. No issues found as @softkot said. But if Cyrillic `c` will look differ than Latin `c` it would be just awesome! :)
Many thanks for your work and attention to details. This is always appreciated.

**Comment by chrissimpkins** [comment]
@softkot Thank you very much Alexei.  That is very helpful feedback.  If you are on OS X you may notice that the oblique slant is quite large in the JetBrains editors.  This is a known Java rendering issue that has occurred with many (but not all interestingly) typefaces.  There is an issue report for it (#26) if you have any interest in following the issue.  Thanks again.

**Comment by chrissimpkins** [comment]
@retgoat my pleasure Roman.  Let's see if we can find something that looks different enough but still like a 'c' :)

**Comment by softkot** [comment]
@chrissimpkins i am running Linux and did not find any issues with large oblique slant.

**Comment by chrissimpkins** [comment]
@softkot Excellent, it seems to be isolated to OS X systems.  Glad to hear that.

**Comment by retgoat** [comment]
@chrissimpkins,
I'm using OS X and Sublime. 
Just FYI in Sublime oblique slant is looks fine.

**Comment by chrissimpkins** [comment]
Thank you very much @retgoat!

**Comment by achkasov** [comment]
Why would not you just add a serif to the Cyrillic Сс like it is done in Courier font?
Here’s a mockup, how might it look in Hack:
![Носок vs Hack](http://i.imgur.com/2l9yzve.png)

**Comment by softkot** [comment]
@achkasov nice idea.

**Comment by chrissimpkins** [comment]
@achkasov thanks, let me see what I can come up with.  I will try to include this change soon.

**Comment by daimor** [comment]
And problem with numero sign "№", it is not present here

**Comment by chrissimpkins** [comment]
@daimor I will confirm but I do not believe that I included this glyph in the current release.  In what context are you using this character?

**Comment by daimor** [comment]
We have this character on a russian localized keyboards

вт, 8 сен 2015 г., 20:40, Chris Simpkins <notifications@github.com>:

> @daimor <https://github.com/daimor> I will confirm but I do not believe
> that I included this glyph in the current release. In what context are you
> using this character?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrissimpkins/Hack/issues/22#issuecomment-138644708>.
>
-- 
*Dmitry Maslennikov*
Lead Programmer at LETOGRAF <http://letograf.com/>
Maintainer of NBStudio <http://daimor.github.io/NBStudio/>
Skype: DAiMor <http://skypedaimor.blogspot.com/>
about.me/dmitry.maslennikov

**Comment by chrissimpkins** [comment]
@daimor I see.  We can add this to the set.  I'd like to make the recommended change to the `c` soon too.

**Comment by chrissimpkins** [comment]
Quick update.  Seeking some feedback from the type design community about the lowercase c issue.  I'd like to get some creative input to see how we can address this at small screen text sizes where many features in fonts tend to fade with hinting/instruction sets that force the glyph shapes into the pixel grids.  Wanted to confirm that this is not forgotten.  I just want to come up with a good approach that will work for you.

**Comment by chrissimpkins** [comment]
Work is underway on the Cyrillic `c` glyph and the numero glyph.  Please see issue report #29 for the Cyrillic `c` and issue report #114 for the numero glyph. 

The next release is going to include a number of expansions to the current character set.  If there is anything else that you need in the Cyrillic character set, please submit this as a new issue report.  I will close this issue report given the lack of additional recommendations over the last month.  Look forward to your feedback as these new glyphs are developed.

**Comment by chrissimpkins** [comment]
Any thoughts on this design for the Cyrillic C?  We could do the same thing for the lower case letter.  It is similar to the Euro symbol.

<img width="259" alt="cyrillic-c" src="https://cloud.githubusercontent.com/assets/4249591/10328171/12494a1e-6c7f-11e5-94cd-7d535b53be2c.png">

**Comment by achkasov** [comment]
@chrissimpkins as a Russian i find it looking very weird. It is also easily confused with Cyrillic letter Єє.

**Comment by chrissimpkins** [comment]
OK back to the drawing board....

**Comment by chrissimpkins** [comment]
How about the shape of the Greek sigma final as the `c` in the Cyrillic set?  

<img width="336" alt="sigma-final" src="https://cloud.githubusercontent.com/assets/4249591/10385309/f0ec84c0-6e14-11e5-860a-0442085fee0a.png">

**Comment by retgoat** [comment]
@chrissimpkins, I don't want to dissapoint you, but it looks very weird too. Only people involved into this discussion will recognize that glyph as cyrillic "C", others will think that font ligatures are broken.

**Comment by chrissimpkins** [comment]
Ok, no worries.  Just trying different things.  I'm open to suggestions.  Not really sure what to do with a `c` that does not make it look like something other than a `c`.  It will need to be dramatic enough that it will be apparent at small text sizes when fit to the pixel grid.

There was a suggestion of a serif on the top of the letter above.  

Thoughts?

**Comment by chrissimpkins** [comment]
By the way, I have looked through dozens of typefaces that include Cyrillic glyphs and they all just maintain the Latin c shape...

**Comment by retgoat** [comment]
I think adding serif clear enough, because many russians had used Courier :)
Yes, many fonts just copy existing shape, and that's a real pain for all of us.
If somebody of us working on localized software — mix those glyphs is piece a cake. But find it out and fix takes a lot of time.

**Comment by chrissimpkins** [comment]
Here are a couple more in line with the Courier New style:

<img width="254" alt="cyrillic-c-overunder-serif" src="https://cloud.githubusercontent.com/assets/4249591/10385671/2d9a9ff6-6e1a-11e5-9574-cd8ab06464dc.png">
<img width="269" alt="cyrillic-c-upper-serif" src="https://cloud.githubusercontent.com/assets/4249591/10385673/2f16c8d2-6e1a-11e5-9412-e471fc333767.png">

**Comment by retgoat** [comment]
Both of them are pretty clear, I think.
The last one looks more nicely IMHO. Let's wait what other participants will say.
Many thanks for your work! :+1:

**Comment by chrissimpkins** [comment]
Sounds good. Thanks for your input.  It has been helpful.

**Comment by achkasov** [comment]
Both look nice. Another option you can consider is adding a "drop" instead of a serif, like in Baskerville, but I have not idea if it fits the Hack font style. 

![image](https://cloud.githubusercontent.com/assets/14052589/10387034/047aa302-6e5e-11e5-9268-26d984000745.png)

**Comment by softkot** [comment]
@chrissimpkins  bottom c looks better.

**Comment by chrissimpkins** [comment]
@achkasov That tends to be a serifed font design.  Looks nice though.

@softkot Thanks Alexei.

**Comment by chrissimpkins** [comment]
Gave the stroke some very slight curves and here is where we are, Latin vs. Cyrillic:

<img width="350" alt="latin-c" src="https://cloud.githubusercontent.com/assets/4249591/10405730/ee80edb8-6ea8-11e5-9ba4-c4514a5f31bd.png">

<img width="364" alt="cyrillic-c" src="https://cloud.githubusercontent.com/assets/4249591/10405731/f15a632a-6ea8-11e5-8257-045948f56067.png">

Will build these in the upcoming test build and push them for you to try.  We will need to see how much of the stem is maintained at small text sizes.

**Comment by chrissimpkins** [comment]
The new Cyrillic C/c glyphs and the numero symbol were added to the v2.016 test build.  You can give them a try with these files:

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

Please let us know how they look in your editors.

**Comment by retgoat** [comment]
Hey @chrissimpkins,
it seems  all is fine: cyrillyc symbols are differs from the latin ones, and numero sign looks good.
Have a look:
![2015-10-12 11-40-08 lorem ipsum dolor sit amet consectetur adipisicin forvetbet-br3](https://cloud.githubusercontent.com/assets/1287915/10422029/d775975a-70cd-11e5-8a36-287c049f4661.png)

Great job! :+1:

**Comment by achkasov** [comment]
@chrissimpkins it looks differently to Latin Cc while not being too disturbing, good compromise, great job! Thanks.

**Comment by chrissimpkins** [comment]
@retgoat @achkasov thank you both for your feedback.  I'm glad to hear that things seem ok on first glance.  Please let me know if you notice problems as you use them.

**Comment by chrissimpkins** [comment]
For all in this thread: 

For future testing purposes, are you aware of any good text string that adequately represents commonly used Cyrillic characters and any associated problems that commonly occur in text that uses these glyphs?  If not,  would you be willing to help pull one together that we could use for testing our Cyrillic set in this project.   This might help us to identify other areas for improvements, possibly at text sizes outside of which you are using in your editors.

**Comment by Bfgeshka** [comment]
Pretty common pangram: ```Съешь же ещё этих мягких французских булок да выпей чаю.```

**Comment by chrissimpkins** [comment]
@Bjgeshka excellent!  Includes upper and lowercase?

Are there any problems that you face with diacritics adjacent to each other or capital letters adjacent to other caps, adjacent to lowercase?  There are some very wide glyphs in the Cyrillic set.  Do you see crowding of characters in monospaced fonts?

**Comment by chrissimpkins** [comment]
Have any of you viewed these on Windows or Linux?

**Comment by Bfgeshka** [comment]
Just checked it on linux, new "с" seems fine for me.

**Comment by xstee** [comment]
I agree that latin C and cyrillic C must have some difference, but now I see ... don't know a good word in English. Small stroke in cyrillic C scratch my eyes =)
![2015-10-13 14-01-04 small example beautychel ld - sublime text unregistered](https://cloud.githubusercontent.com/assets/8166186/10450307/46f84ba2-71bb-11e5-90dc-8ba4b2adfd31.png)
It's just my opinion.
May be the solution is to add some very small stroke for cyrillic C, which will be clear on big scale. Usecase: I see a text and don't know is this C or Es. I increase scale and see (or not) a small stroke. Let me explain with image
![2015-10-13 14-08-57 coreldraw x7 - -1](https://cloud.githubusercontent.com/assets/8166186/10450479/588699cc-71bc-11e5-9d89-46b8e68372cf.png)
In text I will not see stroke. What do you think?

**Comment by chrissimpkins** [comment]
> scratch my eyes

Sorry... :)

> solution is to add some very small stroke for cyrillic C, which will be clear on big scale.

I know it looks unusual.  We went through a number of iterations with the c.  It's a difficult character to modify and achieve something that looks like a c.  The changes that you propose will not be visible in text at the size that is used in text editors for source code.  Once that gets aligned to the pixel grid, this nuance will be gone and it will look like the Latin c.  My understanding of the goal here was to create an obvious visual distinction between Latin and Cyrillic glyphs *without the need to modify the text* because this leads to confusion for users of the Cyrillic character set.   

Anyone else have thoughts about this?  This is a test build and it has not made its way into the release set yet.  The goal is to allow you to work with it in your code and see how things look before we release it for general use.

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release

**Comment by bofm** [comment]
Well, I'm Russian and this kind of c hurts my eyes. I asked around people at my office and they have the same opinion.

**Comment by bofm** [comment]
I'm Russian and this kind of c hurts my eyes. I asked around people at my office and they have the same opinion.

I understand the point of distinguishing Latin and non-Latin "C" letters. But text looks like a foreing language text with "C" from v2.018. For me Hack is not usable with it.

**Comment by bofm** [comment]
@retgoat @chrissimpkins just why only "C"? 

There are still many letters that look exactly the same in English and Russian layouts in v2.018
![en-ru](https://raw.githubusercontent.com/bofm/tmp/master/HackEngRu.png)

Hey Russians! Do you really want all the letters to be redesigned like this? Would you like to invent a new alphabet just to not confuse some letters with other languages?
![en-ru](https://raw.githubusercontent.com/bofm/tmp/master/HackEngRu2.png)

I believe those changes of "C" were a mistake and the creators of this great font should revert "C" to it's friendly native look.

**Comment by softkot** [comment]
This c letter is particular, cause it shares the same button on the phisical keyboard. And thus this font is for coders it'a good point to separate it visually.
@bofm if you are not a coder/hacker just do not use this font.

**Comment by xstee** [comment]
@bofm, I'm Russian and I do believe that changes with C are not useful. Agree with your opinion.
@softkot, I'm software developer since 2002, and I would like to use this font =)

Lets explain the situation for our non-russian collegues. There are beginners in software development area. And when they write a code, they can make a mistake: instead latin c they write cyrillic c (because it shares the same button on keyboard). Than they start a program and it crashes with error. Look at example, please: http://jsbin.com/feyapudeci/edit?js,console
I see a variable defenition "var c_var", and in console I see: "с_var is not defined". Hm.. May be I'd mistype something? Yeap. I should copy a name of var and paste in right place. What's the problem? And this kind of problem are belong **only** for beginners.

I wouldn't like to see eyes-scratching C in cyrillic.

**Comment by bofm** [comment]
@softkot 
> @bofm if you are not a coder/hacker just do not use this font.

EULA?
A am coder. This font looks great in Sublime Text.

@softkot @xstee I have never had that kind of problems.

> and in console I see: "с_var is not defined". Hm.. May be I'd mistype something?

Maybe that was "a"? We need it with stroke too.

**Comment by istarkov** [comment]
There is no need in cyrillic symbols for coding,
So it does not matter how `c` looks in editor, it must be different to prevent possibility to set Russian `с` symbol. 

So guys who wants a normal `c`  - are you coders? 
And if yes, where Russian `с` symbols are presented in your programs? 

For me the only way for cyrillic `c` symbol can come into my program is mistake and nothing more.

**Comment by bofm** [comment]
@istarkov 
> And if yes, where Russian с symbols are presented in your programs?

In docstrings.

**Comment by bofm** [comment]
I created the version I need with git. How to build this font?

**Comment by jublo** [comment]
@bofm We will have some build process in place soon, working on this currently. :)

**Comment by chrissimpkins** [comment]
@bofm you could build this with FontForge but would need to hint the fonts yourself.  I would recommend that you use our builds for now.  As @jublo mentioned we are working on a scripted build approach for those who are interested in building the fonts on their own.  There is a separate open issue report for this if you want to follow along with the progress.

**Comment by MaxKh** [comment]
I'm totally agree with @bofm and @xstee - I prefer to see normal Cyrrilic symbols.

I can undersand @istarkov 's comments but I do not think that it is a valuable reason for such "vandalsm" action.

PS: I use Russian language in Sublime to prepare my weekly report.

**Comment by vladimir-novoseltsev** [comment]
Well, this is just ugly. I certainly see little point in creating separate look and feel for cyrillic glyphs.
On top of that additional strokes break clean feel of the font.

**Comment by chrissimpkins** [comment]
Clearly a divisive issue.  Thoughts about a way to achieve a balance in the design that still allows visual distinction?

**Comment by bofm** [comment]
@chrissimpkins impossible for "c" letter, unless it is borrowed from Times New Roman and font size is >16 pt.

**Comment by vladimir-novoseltsev** [comment]
Just checked a dozen of different fonts - and I think I've found only one font which had distinct glyphs for cyrillic symbols (beside ones which are really different like 'k' and 'к'). And this one font were not monospace.

**Comment by chrissimpkins** [comment]
We have been closely following your conversation here and I think that we will be able to address both ends of this spectrum at some stage.

There is not presently a plan to remove the distinct lowercase `c` shape from our font sets and replace this with the Latin lowercase `c` shape.  We would be happy to attempt to modify the current shape to something more visually appealing and are more than willing to discuss any suggestions that you have.  Please post images of illustrations with your ideas or examples from other typefaces and continue to discuss these here.

For those who prefer to view the Latin `c` glyph shape in the Cyrillic set, there is an immediate workaround using the Copy/Paste feature in FontForge to replace the Cyrillic glyph with the Latin glyph.  You can use our ttfautohint hinting script to generate new hints on ttf builds or the autohinting capabilities of FontForge if you intend to build otf files.  This modification requires a change in the name of the fonts. The sets that you create should not be redistributed with the name "Hack".  Please see the license in the top level of the repository for more details.

Our intermediate term plan is to release a tool that will allow you to replace any glyph in the set with alternates or add new glyphs to the set.  This is something that we have been discussing for the last several weeks and it is in the planning stage at this point.  This will be our solution to the lack of OpenType feature support for alternate glyphs in most source code text editors and the plan is to create an automated approach outside of font editors to make these changes.  The current plan includes an associated repository of alternate glyphs that are developed by the project team and user contributions.  For those who do not use the font editor approach above and prefer the Latin lowercase c style, please check back in the next few months as we will be interested in your thoughts about the utility of this tool.

**Comment by ngleb** [comment]
Very bad that that such sily case is the reason to find new font. Why not just create a classic version and "improved" version?

**Comment by jublo** [comment]
@ngleb Gleb, please see my comment in #155.

**Comment by chrissimpkins** [comment]
All, if you take an interest in the Cyrillic lowercase `c` glyph modifications that were made based upon your recommendations here I ask that you please join us in #155 to discuss this change further.  For those who recommended the initial change, I request that you provide us with additional details about:

(1) where the Cyrillic `c` is being used in your source code
(2) examples of how this is leading to confusion, improper linting, source code errors

Based upon this discussion, we will decide whether it is important to maintain this change or revert to the original appearance of the glyph.  We have mounting concern that this is not a problem for many Cyrillic users and the distinct appearance of the glyph is cause for concern among many.

We have the option to modify the design and maintain a distinct appearance; however, we will need our Cyrillic users to reach a consensus about the importance of this issue **in source code**.  As you hold this discussion, please use visuals (screenshots are good) that demonstrate your problem and the type of source code that you are viewing the glyphs in.

Thanks much.

**Comment by ngleb** [comment]
Well, I can say add that the origin of this issue might be a keyboard layout. Cyrillic Es and C are on the same button. For more than 15 years of using PC and writing the code I never had issues with Es and C. Only as example, I once had similar issue with 1, l (lowercase L) and I (lowercase i) and never with confusing Cyrillic and Latin symbols (it was Courier font, btw).

I think that two versions would be very good, with all classic symbols and with modified. I understand that it can be difficult so I this is only my recommendadtion. My eyes just doesn't accept such changes, it looks so unnatural for me.

I understand that such apperance can be useful when two sets of characters are mixed (some programming things). But this looks awful in Russian text (for example, I use emacs org-mode to organize my notes and all texts use Hack font because it it default for Emacs, so if I have some paragraph in Russian, modified Es (C) looks bad).

I will try to follow this case and comment on some your proposals.

**Comment by chrissimpkins** [comment]
@ngleb I apologize Gleb.  We will move the conversation about the Cyrillic c to #155.  I am hoping to have the users here who initially commented about the change join us in that thread.  This thread (#22) is where the original Cyrillic c change originated based upon comments above.
