### ISSUE TITLE
Hack not working on latest Android Studio (Canary Channel)

### ISSUE THREAD

**Issue by timothyjc** [chrissimpkins/Hack#220]
![screenshot 6](https://cloud.githubusercontent.com/assets/674710/17271944/704282e2-5681-11e6-939f-06bbafb7fba4.png)

Android Studio 2.2 Preview 6, Hack v2_020-ttf

**Comment by chrissimpkins** [comment]
What platform?

**Comment by timothyjc** [comment]
Windows 10

**Comment by chrissimpkins** [comment]
@texhex

**Comment by timothyjc** [comment]
Same problem with installer...

**Comment by chrissimpkins** [comment]
Thanks much for trying it.  @texhex any thoughts here?

**Comment by texhex** [comment]
@timothyjc Sorry to hear the installer wasn't able to fix this. Could you please:

1) Install Notepad++, select Hack as the default font and check if it displays in Notepad++ correctly. Or does it look strange there also?

2) Change the font in Android Studio to be something else than Hack, then restart Windows and select Hack again. Does it come back normally or broken again?

3) Could you please post the contents of C:\Program Files\Hack Windows Installer\Log-FontData.txt here? It's where we log important information during the installation. There are no personal data in it, just system stuff. 

Thanks in advance!

/cc @chrissimpkins

**Comment by jorgheymans** [comment]
@timothyjc what jdk are you using to start android studio ? Note this is different from the jdk set in the ide to compile your project.

**Comment by timothyjc** [comment]
@jorgheymans 1.8.0_92

**Comment by timothyjc** [comment]
@texhex 

1) Works fine in Notepad++
2) Still broken:
![screenshot 7](https://cloud.githubusercontent.com/assets/674710/17307003/d7d589d6-582a-11e6-84eb-a543ed6c978d.png)
3)

---BeforeInstallAction START---
Setup version: 1.2.0
Font version.: 2.020
Local time...: 2016-30-07 20:16
Fonts folder.: C:\WINDOWS\Fonts
Dest folder..: C:\Program Files\Hack Windows Installer
---HASH CALCULATION---
Calculating hash for Hack-Bold.ttf
   File from setup: a7bb6faacd609145b55ed15ca238755544c03af5
   File in \fonts : -NOT FOUND-
Calculating hash for Hack-BoldItalic.ttf
   File from setup: c428004a2fe3570450c6d03442052b1a9989c58b
   File in \fonts : -NOT FOUND-
Calculating hash for Hack-Regular.ttf
   File from setup: 664cfe2a64de1486c0ace8073ceeb6d9281e8b78
   File in \fonts : -NOT FOUND-
Calculating hash for Hack-Italic.ttf
   File from setup: efdae4b94858b98eab6dcf2cb8e3cc3d28263cc2
   File in \fonts : -NOT FOUND-
----------------------
Checking for differences between fonts in setup and this system
IsSetupFontSameAsInstalledFont(): Hack-Bold.ttf
   Checking for font name in registry: Hack Bold (TrueType)
   Font not found in registry!
   Found difference for file Hack-Bold.ttf
   Installation required.
---BeforeInstallAction END---
IsSetupFontSameAsInstalledFont(): Hack-Bold.ttf
   Checking for font name in registry: Hack Bold (TrueType)
   Font not found in registry!
IsSetupFontSameAsInstalledFont(): Hack-BoldItalic.ttf
   Checking for font name in registry: Hack Bold Italic (TrueType)
   Font not found in registry!
IsSetupFontSameAsInstalledFont(): Hack-Regular.ttf
   Checking for font name in registry: Hack (TrueType)
   Font name found
   Checking for file name in registry. Expected: Hack-Regular.ttf
   File name matches
   Hash values (Setup/Windows): 664cfe2a64de1486c0ace8073ceeb6d9281e8b78 / -NOT FOUND-
   File hash is different!
IsSetupFontSameAsInstalledFont(): Hack-Italic.ttf
   Checking for font name in registry: Hack Italic (TrueType)
   Font not found in registry!
IsSetupFontSameAsInstalledFont(): Hack-Bold.ttf
   Checking for font name in registry: Hack Bold (TrueType)
   Font not found in registry!
IsSetupFontSameAsInstalledFont(): Hack-BoldItalic.ttf
   Checking for font name in registry: Hack Bold Italic (TrueType)
   Font not found in registry!
IsSetupFontSameAsInstalledFont(): Hack-Regular.ttf
   Checking for font name in registry: Hack (TrueType)
   Font name found
   Checking for file name in registry. Expected: Hack-Regular.ttf
   File name matches
   Hash values (Setup/Windows): 664cfe2a64de1486c0ace8073ceeb6d9281e8b78 / -NOT FOUND-
   File hash is different!
IsSetupFontSameAsInstalledFont(): Hack-Italic.ttf
   Checking for font name in registry: Hack Italic (TrueType)
   Font not found in registry!
  Changes detected, require reboot

**Comment by timothyjc** [comment]
@jorgheymans

This is the bundled version with Android Studio which it is using:
 
openjdk version "1.8.0_76-release"
OpenJDK Runtime Environment (build 1.8.0_76-release-b03)
OpenJDK 64-Bit Server VM (build 25.76-b03, mixed mode)

**Comment by jorgheymans** [comment]
@timothyjc would you mind running a test using https://github.com/source-foundry/java-glyph-tester ? Basically download the zip release and execute below command, pointing to the location of the ttf you unzipped somewhere. Again make sure that "java" below points to the jdk used to start android studio.

`
java -jar java-glyphtester-0.1.zip --fontfile C:\Users\jorgheymans\Downloads\Hack-v2_020-ttf\Hack-Regular.ttf --fontsize 14 --fontstyle regular --outputdirectory c:\tmp ABC
`

It should generate an image with "ABC", i am just wondering if the font corruption occurs here as well. Note that i have never tested with openjdk. If it's easy for you to do so it might be worthwhile testing if you get the same problematic behaviour with the latest oracle jdk.

**Comment by timothyjc** [comment]
@jorgheymans 

```
C:\Users\timothyjc\Desktop\nf>C:\Android\android-studio-ide-145.3070098-windows\android-studio\jre\bin\java -jar java-glyphtester-0.1-SNAPSHOT.jar --fontfile C:\Users\timothyjc\Desktop\nf\Hack-Regular.ttf --fontsize 14 --fontstyle regular --outputdirectory C:\Users\timothyjc\Desktop\nf\tmp ABC
Parsing font C:\Users\timothyjc\Desktop\nf\Hack-Regular.ttf
[-465.8203,-279.78516,661.6211,977.0508]
Detected font Hack (Regular) version 2.0200043
Total number of glyphs : 1561
Glyph ids that cannot be rendered : 0,606,607,608,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1529
took 703 ms
```

**Comment by jorgheymans** [comment]
@timothyjc thanks! so this tells me that at least the openjdk is able to render the hack font fine. So the problem must be with the font install or android studio itself. Is there an option to invalidate all caches like IntelliJ Idea has : https://www.jetbrains.com/help/idea/2016.2/cleaning-system-cache.html . Could be worth a try.. (but i'm really just guessing now)

**Comment by timothyjc** [comment]
@jorgheymans Aren't a few of them not rendering correctly: 0_LCD HRGB antialiasing text mode.jpg and 0_LCD HBGR antialiasing text mode.jpg?

Invalidating the caches and restarting does not fix it...

**Comment by jorgheymans** [comment]
@timothyjc yes you are absolutely right, my diagonal glance failed me. So it's a problem with the anti-aliasing in openjdk. Are you able to install oracle jdk and rerun the test ? Thanks for helping us troubleshoot this. Unfortunately font rendering in java is not clear-cut at all, big differences across jvm versions and even platforms (looking at you Apple). Supposedly the harfbuzz font engine in jdk9 is going to fix all this... but intellij does not support it yet as runtime for its platform.

**Comment by timothyjc** [comment]
@jorgheymans Oracle JDK has similar problems:

```
C:\Users\timothyjc\Desktop\nf>java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

![screenshot 10](https://cloud.githubusercontent.com/assets/674710/17341492/c0c92ca8-58ec-11e6-8b12-e0586d5034bd.png)

**Comment by chrissimpkins** [comment]
:+1: thanks all for your efforts here.  Sorry to hear that we are running into another JVM issue here.  I will continue to probe in order to see if I can figure out what is causing it on our end.  Unclear.

**Comment by jorgheymans** [comment]
@timothyjc meh that's not what i expected ... can you try adding -Dsun.java2d.font.scaler=t2k to the startup options of android studio ? For intellij the options are defined in a .vmoptions file in the installation directory https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties , i suspect android studio will be similar.

... if that doesn't work you should seriously consider moving to iOS development :-P

**Comment by texhex** [comment]
@timothyjc @jorgheymans Thanks. Based on the data, Hack should be registered correctly in Windows (as Notepad++ is able to use it). What is odd is that "Hack-Regular.ttf" was registered in Windows, while the other styles were not. None of them were found in C:\Windows\Fonts before using the installer. 

I don't think this will help you anything with this JDK issue, but just for your information.

**Comment by timothyjc** [comment]
@jorgheymans
-Dsun.java2d.font.scaler=t2k makes Hack render correctly again... so I have a valid work-around now. I know nothing about font rendering but fwiw, I don't have any issues with the other fonts on Android Studio.

**Comment by chrissimpkins** [comment]
@timothyjc can you provide the names of one or two typefaces that do work in Android Studio without modifications of the default JVM settings?  will take a look at their OpenType tables vs our own to see if this points to a source of the problem.  Not clear what causes this.

**Comment by timothyjc** [comment]
@chrissimpkins 
Source Code Pro
Consolas
Inconsolata

**Comment by chrissimpkins** [comment]
@timothyjc thank you! will have a look

**Comment by chrissimpkins** [comment]
> will have a look

This clearly has not happened yet.  If you are still using Hack, can you provide an update on whether this has changed with releases of Android Studio since the original report?
