### ISSUE TITLE
"Heavy" check mark very light

### ISSUE THREAD

**Issue by alerque** [chrissimpkins/Hack#224]
`U+2714 HEAVY CHECK MARK` (✔) is just an outline and barely visible in the terminal, it should probably be a filled shape to match its name and cousin `U+2718 HEAVY BALLOT X` (✘) which actually shows up as a heavy mark.

**Comment by chrissimpkins** [comment]
Neither of these glyphs are included in the Hack sets.  Feel free to reopen as a request to add them if you have a use source code use case where this would be helpful.
