### ISSUE TITLE
Opensuse support

### ISSUE THREAD

**Issue by Arjoni** [chrissimpkins/Hack#225]
Can you add opensuse support? You could use build.opensuse.org for all distros.

**Comment by chrissimpkins** [comment]
We don't release any of the existing packages on package managers.  These are released and maintained by users.  I am more than willing to support this.   Are you interested in maintaining it?

**Comment by Arjoni** [comment]
I have no idea how to do it. I am not a dev.

**Comment by chrissimpkins** [comment]
Will take a look at their package manager.

**Comment by mtelesha** [comment]
https://software.opensuse.org/download.html?project=M17N%3Afonts&package=hack-fonts 

It already is there.

Also you can simply copy any font to /usr/share/fonts/

**Comment by fcrozat** [comment]
I suggest to close this bug report, the package is now directly integrated in openSUSE Tumbleweed and openSUSE Leap 42.2.

**Comment by chrissimpkins** [comment]
:+1:  thanks!
