### ISSUE TITLE
Glyph "hitbox" is not wide enough -> ⋊

### ISSUE THREAD

**Issue by eikooc** [chrissimpkins/Hack#226]
When using Hack the "⋊" glyph doesn't have enough padding to the right
![image](https://cloud.githubusercontent.com/assets/1305015/18540374/8a459726-7b1e-11e6-8afa-0e6283e6bcf0.png)
![image](https://cloud.githubusercontent.com/assets/1305015/18540383/9f315eb8-7b1e-11e6-82b4-b833f43ade06.png)

**Comment by chrissimpkins** [comment]
U22CA is not included in the Hack sets.  This must be a replacement glyph using a fallback system font that includes it.  The fallback font likely has wider horizontal spacing.  Thanks for pointing it out though!
