### ISSUE TITLE
Hack with Atom Editor

### ISSUE THREAD

**Issue by pdxwolfy** [chrissimpkins/Hack#228]
I'm not sure if this is a Hack problem or an Atom problem, so I've reported it in both places...

I'm trying to use Hack with the [Atom editor](https://atom.io), but when I change the font to Hack, Atom ends up treating leading spaces oddly. For instance, here is what a bit of ruby code looks like using Input Mono as the font:

<img src="http://www.well.com/user/phanson/image1.jpg" width="690" height="338">

Notice the invisible spaces, and the consistent indentation of 2 spaces. Here is the same block when using Hack:

<img src="http://www.well.com/user/phanson/image2.jpg" width="690" height="301">

The invisible spaces are no longer displayed, and the spacing is actually about 2.5 characters intead of 2 spaces - actually, it's almost 3 spaces.

Any ideas on what may be happening here and how to fix it?

**Comment by pdxwolfy** [comment]
Closing this. It turned out to be some sort of installation problem. I think I had an older version of Hack installed when I installed the latest update, and somehow it didn't get replaced.

**Comment by chrissimpkins** [comment]
You beat me to a solution! Let me know if you have any further problems.
