### ISSUE TITLE
Difference of Cyrillic "с"/"С" and Latin "c"/"C"

### ISSUE THREAD

**Issue by eisaev** [chrissimpkins/Hack#229]
Please return difference of Cyrillic "с"/"С" and Latin "c"/"C", reverted on 2.019. Without this difference, "Hack" is meaningless as a font for Russian-speaking programmers.

**Comment by mike-zueff** [comment]
Yes, these glyphs explicitly must differ. "Hack" is a font for software developers, not designers.

**Comment by Defman21** [comment]
There were a poll about this change and most of Russian users voted for the version without any differences.

**Comment by eisaev** [comment]
Where can we see this poll? Who are these Russian users? Web-designers?

**Comment by Defman21** [comment]
Not sure why do you hate (?) web designers that much, I do find the lack of difference between these characters useful for me (however, I'm not a web-designer).

The whole discussion is here:
https://github.com/chrissimpkins/Hack/issues/155

**Comment by chrissimpkins** [comment]
Thanks for responding to this @Defman21.  This is correct information.  There was a great deal of discussion about this prior to the changes, the changes were not well received and then there was a great deal of discussion about how to fix them in a way that led to differences in the appearance of the glyphs and no one had good ideas about this so we dropped all changes and made them appear how they are 'expected' to look.   I agree it would be useful to differentiate the glyphs in a manner that is aesthetically pleasing but the main issue boiled down to the fact that these glyphs are only used in comment blocks and strings where they are not likely to lead to significant problems in one's code.  This is why we reverted.  

If you want to access the previous fonts they are still available under the previous tagged version.

**Comment by eisaev** [comment]
I have nothing against designers. Just practicality vs appearance. If Hack font is one of a dozen fonts "for code", the different style of these characters is necessary. If Hack is one in a million fonts "for design", appearance has a higher priority. Unfortunately now I can't use the current version of the font from the system repositories, and forced to use an outdated version 2.018.

**Comment by chrissimpkins** [comment]
Grab a copy of Font Forge and I would be happy to show you how to replace them with the old ones
