### ISSUE TITLE
BSOD with Windows installer (win 10)

### ISSUE THREAD

**Issue by Ovelny** [chrissimpkins/Hack#232]
While installing Hack with the latest Windows installer (Hack v.2.020), I encountered a BSOD at reboot, with error message "CRITICAL PROCESS DIED".

Explorer.exe freezes right after session login, and the BSOD happens 1 min or so after that. Everything else remains usable during that moment, but the BSOD happens at every reboot, no matter what.
 
Here is what I tried, after rebooting in safe mode: 
- Restoring Win 10 to a previous point: BSOD still persists, to my surprise
- Cleaning the registry and fonts folder to remove Hack entirely, as described [here](https://github.com/chrissimpkins/Hack/issues/152#issuecomment-199369021): no effect 
- Removing font cache, as described [here](https://github.com/source-foundry/Hack-windows-installer/blob/master/FontInstallationIssues.md#not-fixed-the-cache-files-of-the-fontcache-service-can-be-corrupted) : no effect 
- Performing clean boot, by removing startup items and disabling all non-Microsoft services in msconfig: the BSOD finally disappear. 

I don't know where to go from there to identify the source of the problem, and use a normal boot like before. 

I'm almost certain that the problem doesn't come from another software, as nothing else has been installed on this laptop for a week and everything remained stable. No viruses either, according to Malwarebytes.

Huge fan of the font despite this problem! Can't wait to install it on this laptop.

**Comment by chrissimpkins** [comment]
@texhex thoughts?

**Comment by texhex** [comment]
Sorry to hear that @Ovelny, but I do not have slightest idea what could have cause this. We only stop two font-related services, install the font and request a reboot. That's it. 

There is no service running or installed from either the Hack installer or the setup tool (InnoSetup) itself. There is no active component remaining on your device once setup.exe has finished. I really can't explain how this could happen. 

You might want to try to [WhoCrashed](http://www.resplendence.com/whocrashed) - it's very good for driver related crashes, but I don't know how good it works with this error. 

What is somewhat "interesting", is that it worked again once you disabled all Non-MS services and that it took one minute to occur. I could only think of a rather strange side effect of an non-MS service that crashes as soon as it sees Hack and is also considered "critical" by Windows. 

Do you have any chance to check the services you have disabled to see if some of them have the startup type "Automatic (Delayed Start)". Maybe this will reveal which service is causing this. 

And just to be sure: You didn't disabled your AV software by disabling all non-MS services?

**Comment by Ovelny** [comment]
@texhex Thank you for your reply, and sorry for the delay. I can confirm that my AV (Windows Defender) wasn't disabled while doing a clean boot, so it wasn't related.
I used WhoCrashed as mentioned (nice tool by the way!) and it revealed that it was likely a driver error, or a kernel error (!)
Here is what I did afterwards: 

- sfc /scannow to check for errors : none found
- Dism /Online /Cleanup-Image /RestoreHealth : no problems found either
- Tested normal boot : BSOD occurs again. I noticed that it crashed right after Dell Update started (bloatware that wasn't uninstalled yet 😓... brand new laptop).
- Updated graphical driver just in case, and removed all Dell related softwares while performing a clean boot.
- No more BSOD!

i'm still confused about the whole issue (I highly suspect Dell Update to be the culprit, but I can't be 100% sure about it), but at least the problem is solved.

Feel free to ask more details about the BSOD logs or anything, I'd be happy to provide more infos.

**Comment by chrissimpkins** [comment]
:+1:

**Comment by texhex** [comment]
@Ovelny Hmm, to be honest: I still have no idea what the issue is here. Since it didn't occurred before installing Hack, this seems to be some sort of "snooker" issue where A causes B which causes C and then the computer ends up in non-responsive bye-bye land. 

But I have no idea which driver would load all mono spaced fonts, does something with them and fails when there is a condition that somehow hack triggers. 

In case you have some time, it would be great if you could uninstall Hack, install Dell Update and check if the BSOD returns the moment you have installed hack again. I know this is much to ask, but I really have no other idea how to reveal what is going on.

**Comment by Taiger** [comment]
I experienced a similar issue on my Windows 7 machine. The installer freezes.
However, I was able to kill the process and restart without a problem.

I am definitely installing this font via the traditional route now.

**Comment by chrissimpkins** [comment]
@Taiger sorry for the troubles.  The impetus for this was that the font cache on Windows is a problem.  Recommend that you use a different tool to clean the font cache before you try a new Hack install over a previous one (if that applies to you).  Let us know if you have any problems.

**Comment by Taiger** [comment]
Thanks @chrissimpkins, when I update the font I will look into how to clear the font cache first.

**Comment by chrissimpkins** [comment]
:+1:
