### ISSUE TITLE
Hack not recognized as a fixed-width font by KDE5's Konsole

### ISSUE THREAD

**Issue by kaleissin** [chrissimpkins/Hack#233]
Konsole only allows choosing fonts that it recognizes as fixed-width, I have not found out **how** it determines that a font is fixed-width.

**Comment by chrissimpkins** [comment]
Can you provide me with a couple of font names that it does recognize as fixed width?  I will take a look at the OpenType tables.

**Comment by kaleissin** [comment]
Complete list as of today (Ubuntu xenial and yaketty):

Andale Mono
Courier 10 Pitch
Courier New
DejaVu Sans Mono
FreeMono
Liberation Mono
Monospace
Nimbus Mono L
Noto Mono
Oxygen Mono
Tlwg Mono
Tlwg Typo
Ubuntu Mono

Note that it doesn't list Misc Fixed or Terminus either...

**Comment by chrissimpkins** [comment]
Great thank you very much.  I will take a look and see if we can sort out why this is the case.

**Comment by xelra** [comment]
Maybe this has something to do with Qt. I'm seeing the error `Warning: Font Hack reports bad fixed pitch metrics` using Neovim-Qt on Windows.

**Comment by davelab6** [comment]
Fontbakery should tell you if it's set up correctly as a monospace

**Comment by chrissimpkins** [comment]
Font Bakery analysis includes the following:

_ERROR: OS/2 fsType is a legacy DRM-related field from the 80's and must be zero (disabled) in all fonts. Changes that must be applied to this font: OS/2 fsType from 8 to 0

ERROR: OS/2 usWinAscent & usWinDescent Changes that must be applied to this font: OS/2 usWinAscent from 1901 to 2001 | OS/2 usWinDescent from 483 to 573

ERROR: OS/2 sTypoAscender and hhea ascent must be equal

Warning: This is a monospaced font, so advanceWidth value should be the same across all glyphs, but 0.45 % of them have a different value. Double-width and/or zero-width glyphs were detected. These glyphs should be set to the same width as all others and then add GPOS single pos lookups that zeros/doubles the widths as needed._

I am guessing that perhaps the last of those could be used to "detect" fixed width fonts on Konsole?  @davelab6 do you happen to know of an automated approach to detect the (small) number of glyphs in each of the sets where this advanceWidth value issue is problematic?

**Comment by chrissimpkins** [comment]
@davelab6 side issue, there appears to be a problem with Font Bakery's appspot application and the italic set of our fonts.  All others report results but italic seems to cause problems.  Reported here:

https://github.com/googlefonts/fontbakery/issues/1406

**Comment by davelab6** [comment]
@chrissimpkins use the command line at the last release please :) 

I don't know what KDE Konsole uses to determine if a font is fixedwidth...

**Comment by chrissimpkins** [comment]
@davelab6 thanks Dave.  I appreciate your help!

**Comment by chrissimpkins** [comment]
Closing for lack of response from OP.  Clearly my own fault for lack of response not theirs.  Please feel free to reopen if this is still an issue.
