### ISSUE TITLE
Rendering issue for the letter "u" on Arch linux

### ISSUE THREAD

**Issue by Pacane** [chrissimpkins/Hack#238]
The rendering of the letter "u" seems to be broken using specific settings. Specifically, the height of the letter seems to be wrong.

Using:
- xfce4-terminal (tried other terminals too like URxvt)
- Hack regular size 10
- Antialiasing on
- Hinting enabled (slight)
- Sub-pixel geometry: RGB

See the "u" in "runcoms" as an example:
![image](https://cloud.githubusercontent.com/assets/2762440/22029211/d69f2f84-dca7-11e6-934a-5f04a3fc9d7e.png)

Same issue happening on size 11, but less visible.
![image](https://cloud.githubusercontent.com/assets/2762440/22029246/f18a8578-dca7-11e6-91f3-e8ee6a724be6.png)

but disappears on size 12
![image](https://cloud.githubusercontent.com/assets/2762440/22029268/01bbe392-dca8-11e6-8ed6-5465d22faa7a.png)

Issue also seems to disappear with hinting disabled.
![image](https://cloud.githubusercontent.com/assets/2762440/22029398/6fa96460-dca8-11e6-8763-a2021d59492b.png)

Also tried with Hinting : hintfull, but the issue is also there.
![image](https://cloud.githubusercontent.com/assets/2762440/22029428/880c600c-dca8-11e6-9c28-973a32e79700.png)

I was wondering if I had to add any entry in font-config to solve this issue.

If you need more information, I'd be glad to give you more.

Thanks.

**Comment by chrissimpkins** [comment]
Sorry for the (extended) delay in response.  If you are still using Hack and want to discuss this issue, please let me know.
