### ISSUE TITLE
Can't install font on Windows 10 Home

### ISSUE THREAD

**Issue by Frexuz** [chrissimpkins/Hack#24]
![image](https://cloud.githubusercontent.com/assets/49692/9463040/29f2c41e-4b1a-11e5-859a-5422eb20e110.png)

**Comment by Frexuz** [comment]
This accepted answer did solve the issue: http://superuser.com/questions/957907/unable-to-install-fonts-on-windows-10

> Firewall must be turned on

**Comment by chrissimpkins** [comment]
Thanks I will update the documentation to reflect that.

**Comment by chrissimpkins** [comment]
Added to the FAQ. Thanks for reporting it and including the fix!
