### ISSUE TITLE
Only bold and bold italics version available on Fedora copr repo

### ISSUE THREAD

**Issue by Paviluf** [chrissimpkins/Hack#243]
Hello,

I just tried Hack from this [copr](https://copr.fedorainfracloud.org/coprs/heliocastro/hack-fonts/) repo on Fedora 24 and I needed to use `sudo fc-cache -f -v` to have access to the regular variant in Sublime text.

This issue had already been reported but not fixed https://github.com/chrissimpkins/Hack/issues/202

Thanks !

**Comment by chrissimpkins** [comment]
Any updates on this?  I do not manage the Fedora releases of Hack.  This is managed by the Fedora community.

**Comment by Paviluf** [comment]
I didn't try on Fedora 25 but the repo has not been updated in 8 months. Seem not maintained anymore...

**Comment by chrissimpkins** [comment]
OK thanks for your feedback.  @spstarr is building a new package for Fedora and we will update the README when it is available.

**Comment by Paviluf** [comment]
By the way, if a new package is made for Fedora, I hope it will be integrated in Fedora official repo. There is a  Review Request open :

https://bugzilla.redhat.com/show_bug.cgi?id=1258542

**Comment by chrissimpkins** [comment]
I believe this is what they are working on. @spstarr is driving this and will be able to fill you in.
