### ISSUE TITLE
TruFont error "Unknown glyph class aalt3"

### ISSUE THREAD

**Issue by jeffmcneill** [chrissimpkins/Hack#244]
Trying to add some Thai glyphs, but get an error exporting with TruFont:

unknown glyph class @aalt3

I see this as the collection of numbers 0-9 (in the Groups window). Unclear what to do so TruFont can deal with this.

**Comment by jeffmcneill** [comment]
If I just take the .otf from the build directory, there is no problem importing, then exporting it. It is only in opening from the source that the error happens.

Also posted an issue over at TruFont https://github.com/trufont/trufont/issues/376

**Comment by jeffmcneill** [comment]
Hi, it is working for me now, no errors.

**Comment by jeffmcneill** [comment]
Still same problem

**Comment by chrissimpkins** [comment]
Resolved in Trufont repo IR thread https://github.com/trufont/trufont/issues/376.  

Will open a new IR in the Hack repo to address the UFO source files based upon this issue.
