### ISSUE TITLE
Web font subsetter script

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#25]
Goal is to create a script that allows users to subset the files with *only* character sets that they need.  Working on it.  If anyone has experience with this / interest in pitching in, let me know.

**Comment by chrissimpkins** [comment]
This is already a thing.  Just van Rossum's [FontTools](https://github.com/behdad/fonttools) project (now maintained and extended by Behdad Esfahbod) includes the subset.py Python script.  I included [a copy in the tools directory of this repository](https://github.com/chrissimpkins/Hack/blob/master/tools/subset.py). 

The FontTools license is available [here](https://github.com/behdad/fonttools/blob/master/LICENSE.txt).

**Comment by chrissimpkins** [comment]
Added a [list of Unicode block ranges](https://github.com/chrissimpkins/Hack/blob/master/tools/unicode_blocks/unicode_blocks.txt) released by Unicode, Inc. 

The license is available [here](https://github.com/chrissimpkins/Hack/blob/master/tools/unicode_blocks/LICENSE).

**Comment by edent** [comment]
I've done this before - see https://shkspr.mobi/blog/2013/05/subsetting-chinese-fonts/

Several open source tools to do it. Most complex thing is ensuring it copes with cases properly.

**Comment by chrissimpkins** [comment]
Thanks for the link Terence.  I'll check it out.  Be in touch with questions.

**Comment by chrissimpkins** [comment]
Thanks again for the link Terence.  That was very useful.  Any idea if that perl script that you used maintains the TrueType instructions in the subset file?

**Comment by edent** [comment]
I'll confess my ignorance to that. But if you send me a TTF, I can subset it & you can see whether it preserves all the relevant data.
