### ISSUE TITLE
Whitespace rendering issue in Sublime Text 3 (OS X)

### ISSUE THREAD

**Issue by xavier** [chrissimpkins/Hack#251]
Following up on a [Twitter discussion](https://twitter.com/xavierdefrang/status/877783892605911041).

The apparent problem: whitespaces are not rendered with a fixed width of 1 character.

![hack-whitespace-bug](https://monosnap.com/file/hOR8XMiB5ZYtLXpMdUQ4qi5zAXpsXT.png)

The regression happened a few builds ago, would not be able to pinpoint exactly which one but at time of writing, It's occurring with ST3 Dev Channel Build 3139, running on macOS Sierra 10.12.5

Any other font I've tried (Inconsolata, Source Code Pro, Mononoki, Monaco) renders the same text properly in the same build of ST3:
 
![reference-inconsolata](https://monosnap.com/file/vDq1acExNF8t9O2gh62LkZYsvT1mKD.png)

The problem is definitely linked to ST3 because the same text renders just fine using Hack in TextEdit.app for instance.

It might be a hint that ST3 with settings `"draw_white_space": "all"` does not render whitespace with a dot as it does for Inconsolata in the screenshot above. The problem remains with `draw_white_space` is disabled.

Comparing indentation with tabs vs spaces:

![tabs-vs-spaces](https://monosnap.com/file/HEImpxuklbXCoqlJChMPLOosPCbix4.png)

I've deleted and reinstalled Hack from the latest archive (Font Book version info says `Version 2.020; ttfautohint (v1.5) -l 4 -r 80 -G 350 -x 0 -H 181 -D latn -f latn -m "Hack-Regular-TA.txt" -w G -W -t -X ""`)

This is not a problem only on my system, others have reported the issue: 
https://forum.sublimetext.com/t/dev-build-3132/28529/50

Let me know if I can be of any help.

**Comment by chrissimpkins** [comment]
Can you confirm that you are using (or seeing this in) a default theme for ST so that we can start without any interference from outside packages?

**Comment by chrissimpkins** [comment]
Reported in linked thread above re: same issue in Win 10:

> So from the changelog it seems the "draw_white_space": "all" regression should be fixed, yet nothing changed at all using the Hack font on windows 10 and spaces as indentation do not show up at all, tabs do and work fine also the indentation is off still (as described by planet), as if my fixed-width font is not fixed-width at all

> errr, after reinstalling the latest hack font and rebooting, it now works fine, including indentation

It sounds as though the changes included in ST3 dev builds in the last ~ 1.5 months introduced some new white space problems.

Digging through the changelogs to see if we can identify any potential issues.  The fact that it is rendering something other than the middle dot for spaces with Hack and is rendering middle dot for other fonts suggests to me that ST3 dev may be substituting another font's character for something that is missing in Hack (or being perceived as missing, we do include the middle dot).

**Comment by chrissimpkins** [comment]
Whitespace Changes in ST3 dev builds since 3/2017:

**3132**

- Improved visible whitespace rendering on HiDPI displays

**3133**

- Fixed a visible whitespace regression in 3132

Only changes in that timeframe that I can find.  These builds were in late May/early June and seem to jive with the timeframe that you reported.  Do you know how we might be able to dig into the actual changes that were made in these builds?

**Comment by xavier** [comment]
I have the same problem if I use the default theme (for the record, I was using `Soda Light 3.sublime-theme` when I took the screenshots).

**Comment by chrissimpkins** [comment]
> I have the same problem if I use the default theme (for the record, I was using Soda Light 3.sublime-theme when I took the screenshots).

👍 

Unfortunately with a closed source application, I don't know how far we are going to get with this.  I don't know how they are rendering the spacing / glyph selection for spaces.  Dev responsive to questions on the forum?

**Comment by xavier** [comment]
I don't know how responsive the developers are on the forum but I [have posted a link to the issue](https://forum.sublimetext.com/t/spacing-in-dev-build-3139/29351) in a thread about this regression which was started less than 24h ago. Lots of Hack users out there! 😄

**Comment by chrissimpkins** [comment]
Added a comment to that thread.  Will you please update here if any additional information emerges that might highlight the cause of the problem and/or workaround/fixes?

**Comment by xavier** [comment]
I'll surely do. I can't wait to be able to reuse Hack with ST3.

**Comment by chrissimpkins** [comment]
A couple of initial things that you can test:

- Remove Hack files
- Clear font cache 
    - http://osxdaily.com/2015/01/08/clear-font-caches-databases-mac-os-x/
    - http://help.fontshop.com/hc/en-us/articles/202693885-Clearing-your-Font-Cache-in-Mac-OS-X
- Reinstall Hack files

If that doesn't work, can repeat the above process but try the otf builds instead of ttf.

**Comment by wbond** [comment]
I've had multiple reports that installing the latest version of Hack solves the problem. @xavier have you tried that? I posted more details on our implementation change at https://forum.sublimetext.com/t/spacing-in-dev-build-3139/29351/9.

**Comment by chrissimpkins** [comment]
Thanks @wbond 

It sounds like he is using our latest release version:

> I've deleted and reinstalled Hack from the latest archive (Font Book version info says Version 2.020; ttfautohint (v1.5) -l 4 -r 80 -G 350 -x 0 -H 181 -D latn -f latn -m "Hack-Regular-TA.txt" -w G -W -t -X "")

**Comment by chrissimpkins** [comment]
Perhaps a font caching issue either on the OS X platform or in ST3 if you are caching fonts there?

For OS X font caching issues, you can use the clear font cache instructions in the links above ([here](https://github.com/chrissimpkins/Hack/issues/251#issuecomment-311702917)).

@wbond if ST3 caches fonts, is there a way to manually clear the cache after new font installs?

**Comment by wbond** [comment]
No, we don't cache fonts, but we do cache the glyph in memory for better drawing performance. A restart of Sublime Text would clear that out.

**Comment by chrissimpkins** [comment]
@wbond that is helpful! Thanks!

@xavier if you are willing to try the OS X font cache clear / reinstall approach above and then reboot your system, we can see if this addresses the problem.

**Comment by chrissimpkins** [comment]
As a side (but related note since similar issues on Windows were reported in the ST forum thread) font caching problems are notorious on the Win platform.  It is the main reason that we released the Win installer for the fonts because there were numerous issue reports of problems that ended up being the result of conflicts between previous cached versions and newer installs.  The Win installer font installer developed by @texhex addresses this.

Link for any Win users who wander through this thread:  https://github.com/source-foundry/Hack-windows-installer

**Comment by xavier** [comment]
@chrissimpkins Removing Hack, clearing the macOS font cache, reinstalling Hack and restarting ST3 did the trick. I can now enjoy my favorite programming typeface again. Thank you so much! 👍

**Comment by chrissimpkins** [comment]
@xavier fantastic!  enjoy!
