### ISSUE TITLE
Hack UFO source file conversion update

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#252]
Issue identified in UFO source by @jeffmcneill and discussed in https://github.com/trufont/trufont/issues/376 

_ToDo_:

1. Identify UFO source verification software to determine source validity issues
2. Identify FontLab Studio to UFO conversion script that generates valid UFO source (previously have used vfb2ufo)
3. Is XFO (an extended UFO style text format for font source) going to become a new standard?
     - http://help.fontlab.com/fontlab-vi/Font-formats/#extended-font-object-xfo

- [x] 1. Identify UFO source verification software to determine source validity issues
- [x] 2. Identify FontLab Studio to UFO conversion script that generates valid UFO source (previously have used vfb2ufo)
- [X]  3. Is XFO (an extended UFO style text format for font source) going to become a new standard? Supported by OS font editors?
     - http://help.fontlab.com/fontlab-vi/Font-formats/#extended-font-object-xfo
     - Response: https://github.com/chrissimpkins/Hack/issues/252#issuecomment-311868425

**Comment by chrissimpkins** [comment]
@davelab6 @adrientetar 

I see that FontLab Studio VI allows for XFO source in addition to UFO.  Is there a move underway to move towards a new extended UFO format standard?  Is this format currently supported in Trufont, FontForge, or other open source editors?

**Comment by chrissimpkins** [comment]
_ToDo 1_

From https://github.com/trufont/trufont/issues/376#issuecomment-311742528

> You can test the UFO source by compiling with ufo2ft or the fontmake wrapper and checking that there's no crash and diffing against expected output.

**Comment by adrientetar** [comment]
XFO is Fontlab only.

**Comment by chrissimpkins** [comment]
@adrientetar Thank you very much Adrien.  I appreciate it.

**Comment by chrissimpkins** [comment]
Converted with FontLab VI from vfb (v2.020 changes) to new .ufo/.vfb/.vfc files with intent to eliminate all FontLab Studio specific source and transition to UFO as our build source as of v3.0
