### ISSUE TITLE
"u" glyph rendering in terminal with size=14 is incorrect

### ISSUE THREAD

**Issue by cglogic** [chrissimpkins/Hack#256]
On rxvt-unicode and xterm terminal emulators. It seems to 'u' glyph with size=14 be smaller than other 14 glyphs.

I have this setting in .Xdefaults:
`URxvt*font: xft:Hack:size=14`
If I replace this string with:
`URxvt*font: xft:Hack:pixelsize=19` 
'u' glyph is normal.

Size 12:
![12](https://user-images.githubusercontent.com/14204812/28513165-aed056a0-705d-11e7-8123-b8aa2c750e90.png)
Size 13:
![13](https://user-images.githubusercontent.com/14204812/28513169-aed233d0-705d-11e7-81f0-089d860ac7a0.png)
_Size 14:_
![14](https://user-images.githubusercontent.com/14204812/28513168-aed214e0-705d-11e7-875a-f4846b1991e5.png)
Size 15:
![15](https://user-images.githubusercontent.com/14204812/28513166-aed0cc70-705d-11e7-9381-9ebb910381c1.png)
Size 16:
![16](https://user-images.githubusercontent.com/14204812/28513167-aed18fe8-705d-11e7-860a-92c9f1c01115.png)

**Comment by chrissimpkins** [comment]
Thanks for the report!  I believe that we have seen a report on this for our OTF releases in the past.  Can you confirm the version of Hack and the build extension (otf/ttf) that you are using along with your current platform?

**Comment by cglogic** [comment]
Thank you for quick answer and your work on this font.

You are right, I am using version 2.020 and otf extension.

**Comment by chrissimpkins** [comment]
Mind attempting a switch to the ttf releases with a clear of your font cache?  This should fix it.  Our hints are not ideal in the otf versions.  We are planning to drop them altogether and release ttf only as of the upcoming v3.0 release.

**Comment by cglogic** [comment]
Switching to ttf release fixed this. Thanks!

**Comment by chrissimpkins** [comment]
Great!
