### ISSUE TITLE
[OS X] Oblique slant does not display properly in Intellij IDEA/WebStorm/PyCharm

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#26]
This is a known issue with the Java font renderer on OS X platforms for these JetBrains editors.  It renders a pseudo-oblique with a larger slant angle (of the regular font) instead of the installed oblique font.  I have confirmed that this occurs with other typefaces and verified this is in a known issue in the JetBrains issue reports.  The issue has been reported on multiple occasions over the last year in their issue tracking system.  I added my own 2 cents and will update with any information that I receive.  Sorry for the troubles.

**Comment by chrissimpkins** [comment]
Tentatively have a fix for this issue in this test build.  Please let me know if it works on your platform.

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by jalaziz** [comment]
OSX 10.10.5
IntelliJ IDEA 14.1.4

Oblique backslash looks much better.  Thanks!!!

**Comment by chrissimpkins** [comment]
great!

**Comment by iamklutch** [comment]
Windows 10 Android Studio 1.3.2 Oblique looks awesome as well! Thank you so
much for this fix.

**Comment by chrissimpkins** [comment]
@iamklutch Excellent, thank you very much for the feedback.

**Comment by chrissimpkins** [comment]
Thanks for your feedback on this issue.  This fix is now live in release version 2.013.  I really appreciate your help!  Closing this issue as fixed.
