### ISSUE TITLE
Larger and smaller vertical spacing variants

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#28]
By request.  Will add these to the development branch for anyone who wants to give them a try.

**Comment by Palid** [comment]
Count me in, will test narrower vertical spacing.

**Comment by txtsd** [comment]
I would like narrower vertical spacing too!
My PS1 has a vertical gap, and irc in terminal looks too spaced out between lines.
![DejaVu Sans Mono](https://i.imgur.com/HOfUCXY.png) - DejaVu Sans Mono 7pt 
![Hack](https://i.imgur.com/bagTMkf.png) - Hack 7pt

**Comment by chrissimpkins** [comment]
Mind giving this test build a try to see what you think of the spacing?  The font name was changed to 'Hack Tight' so that you can install it with the current release of Hack and compare the two.

https://github.com/chrissimpkins/Hack/blob/vertical-spacing/build/test_builds/HackTight-Regular-h.ttf 

*Changes*:
TypoLineGap decreased to 75 units
LineGap decreased to 75 units

**Comment by theckman** [comment]
I think it looks nice.

Hack:
![Hack](https://cloud.githubusercontent.com/assets/787332/9572478/31bf46a0-4f65-11e5-8e69-0da69a794b3e.png)

Hack Tight:
![Hack Tight](https://cloud.githubusercontent.com/assets/787332/9572483/3ba6ca12-4f65-11e5-888a-20cebc699864.png)

**Comment by chrissimpkins** [comment]
worth going even tighter?  we could release a range.  the diacritics are still visible with this spacing.  

any interest in wider spacing for any layout issues out there?

**Comment by theckman** [comment]
It is an improvement, but I think it could go a bit tighter, yes. This is what I came from:

![Menlo for Powerline](https://cloud.githubusercontent.com/assets/787332/9572762/4b337cac-4f68-11e5-94a8-14546be63016.png)

**Comment by hrj** [comment]
Check out the ASCII art in the following screenshot, comparing [Fantasque](https://github.com/belluzj/fantasque-sans) with Hack and Hack Tight. The gap between the vertical bars is the same between Hack and Hack Tight. In Fantasque, the vertical line doesn't have a gap.

![hackfont](https://cloud.githubusercontent.com/assets/345879/9574280/d1e94c2a-4fe2-11e5-8a71-e9b6c1a32fac.png)

**Comment by hrj** [comment]
Oh btw, here's the ASCII if you need to reproduce the issue:
```
  -2600.00   Expenses        
   -200.00    ├╴Bank_Charges 
   -400.00    ├╴Consumables  
  -2000.00    └╴Salaries     
```

**Comment by txtsd** [comment]
Not sure what's going on, but my Hack OTF v2.010 shows as thinner than Hack TTF v2.010, and the Hack Tight TTF is not different from Hack TTF.

![Hack gif](http://i.imgur.com/ka4Lq5x.gif)

**Comment by txtsd** [comment]
fc-match reports correctly (I uninstalled the otf)

```
┌[txtsd@dungeon-of-data]─[~] 
└─▶ fc-match "Hack Tight"
HackTight-Regular-h.ttf: "Hack Tight" "Regular"

┌[txtsd@dungeon-of-data]─[~] 
└─▶ fc-match "Hack"      
Hack-Regular.ttf: "Hack" "Regular"
```

**Comment by chethankumar** [comment]
I also would prefer if it was a little bit more tighter. As tight as, say Monaco.

**Comment by chrissimpkins** [comment]
@hrj it looks like this is a glyph alignment issue.  This was reported for box glyphs in #41 as well and the `Hack Tight` build didn't help there either. I will tackle the spacing with these glyphs that require alignment with each other once we hammer out a final set of vertical metrics.

**Comment by rdlugosz** [comment]
I'd also submit Menlo as a good example of a tight line height. For relative comparison, with Menlo 12pt I can see 96 lines in MacVim. Using Hack at 12pt that drops to just 78, a full **18 fewer lines**.

**Comment by chrissimpkins** [comment]
> clown-car tight... 

I think that you just named it :)

I am going to try to push a few more builds with some adjustments to the vertical metrics later today.  I will take a look at Menlo's metrics and see how close we can get without taking out the diacritics.

**Comment by rdlugosz** [comment]
:+1:

**Comment by Binarytales** [comment]
There's been a lot of discussion of of tight line spacing here but I was wondering if there are still plans for wider line spacing variants as mentioned in the title?

I currently use Meslo on the cmd line (a variant of Menlo with variable line heights) https://github.com/andreberg/Meslo-Font

I'm a big fan of the largest spacing. Terminal.app and iTerm2 on OSX (which probably account for 90% of cmd line use on OSX allow for increasing line height in preferences. I don't know if other platforms have such features. But the problem with relying on this is that the Powerline icons (mainly the section separators) start to look bad and stop lining up as intended when line height is adjusted in this way.

**Comment by chrissimpkins** [comment]
@Binarytales most have requested tighter spacing but I planned to create looser spacing as well.  I began working on this last night.  Stay tuned.

**Comment by Binarytales** [comment]
@chrissimpkins I shall indeed stay tuned. More than happy to test things out when you have something ready.

**Comment by rdlugosz** [comment]
@chrissimpkins - check out the detail the creator of the "Input" font goes into wrt variants, size, heights, etc. Much of this is beyond my understanding of font creation, but might be helpful to you. Seems like they have incorporated a wide variety of options here. http://input.fontbureau.com/info/

**Comment by chrissimpkins** [comment]
@rdlugosz Input is a fantastic typeface and hard act to follow.  They've put a tremendous amount of thought and effort into it.  Thanks for linking the information on their design considerations.

**Comment by chrissimpkins** [comment]
It's become apparent that this will be a bit larger project than I initially thought because we will need to address spacing issues in all of the glyphs that require exact alignment/orientation with each other (eg the box glyphs).

**Comment by rdlugosz** [comment]
Ah that's a bummer. Well, if someone out there is motivated to have tighter
lines and has the skills + time to spare perhaps they'll contribute. Thanks
for looking into it!

**Comment by chrissimpkins** [comment]
Not writing it off at all. It's in the queue.  We will just need to be prepared to address issues with all of these glyphs to make a version that contains the current character set support happen.  

One approach would be to start with narrower character set support and expand this over time.  This would initially exclude glyphs that require exact vertical alignment with each other.  Anyone in favor of this?  Anyone forsee other problems that I am overlooking with the vertical spacing?

**Comment by chrissimpkins** [comment]
The version 2.014 test build has tighter line spacing, in line with the line spacing in DejaVu Sans Mono and Menlo.  I get the same number of lines as are displayed with these two fonts now.  We've had a number of issue reports about very slight vertical alignment issues between sets that prompted this vertical metrics update.  For those who like it tight, you will likely find this build to your liking.  I am waiting for more general feedback to decide if this will be the new default.  I anticipate that this is going to address some of our Powerline and other alignment dependent spacing issues so this may well stick.  

Files are available in #111 

For those looking for looser builds, this is still planned.

**Comment by rdlugosz** [comment]
Thx! Playing with it now. Looking good so far.

**Comment by chrissimpkins** [comment]
@rdlugosz :+1:  Let me know if you see any problems

**Comment by Palid** [comment]
@chrissimpkins It looks great! Same vertical spaces as Menlo and looks so much better!

**Comment by chrissimpkins** [comment]
@Palid Glad to hear that you like the changes Dariusz.  The new test build changes will be the default for Hack so I am interested in a bit more feedback to make sure that I didn't go too far to the tight end of the line height spectrum.  It seems that there was much more interest in this than looser spacing, but we do have requests for this.  

My thought would be to create new fonts for the line height variants and name them "Hack [something that indicates spacing here]" so that they can be installed side by side.  It might be useful to use different versions in different editors where either rendering differs or you have the option to further adjust line spacing.  I'm not certain that there is a standard for naming this metric in fonts and I suppose that we can come up with our own. 

@rdlugosz Ryan do you have an Input font license?  If so, would you be willing to help me explore how they manipulate their vertical metrics with their line spacing selector (image below)?
<img width="500" alt="input-line-spacing" src="https://cloud.githubusercontent.com/assets/4249591/9994704/84d86bbc-604c-11e5-9988-cdb9f1ac4aeb.png">

**Comment by chrissimpkins** [comment]
Is anyone seeing problems with diacritic marks on any platforms / at any text sizes?

**Comment by Palid** [comment]
Nothing yet, I'll give more feedback in a few days. Ending my today's coding session. ;)

**Comment by rdlugosz** [comment]
@chrissimpkins sorry, I don't have a license. I'm not actively using that font, btw... something about the feel that just isn't right for me. I just happened across it around the same time that I posted in this thread.

**Comment by chrissimpkins** [comment]
@rdlugosz no worries.  Thanks for letting me know.  Did you have thoughts on the line spacing in the new version?  I think you were one of the people requesting tighter spacing.

**Comment by chrissimpkins** [comment]
Tighter vertical spacing is now available in the v2.015 release that was pushed today.  Leaving this issue open to address looser spacing variants in the future.

**Comment by chrissimpkins** [comment]
@hrj does this address your alignment issues?  If not, let's split this off into a different issue report.

**Comment by hrj** [comment]
@chrissimpkins Yes, it works perfectly. Thanks!

**Comment by chrissimpkins** [comment]
@hrj great! thank you for the feedback.

**Comment by rdlugosz** [comment]
Thanks for all the hard work on this font, @chrissimpkins ! Using it as my daily driver right now and really enjoying it.

**Comment by chrissimpkins** [comment]
@rdlugosz Great to hear that.  There's been a tremendous amount of work by a large number of people here.  It's good to hear that it shows.

**Comment by chrissimpkins** [comment]
Started work on an application to address this.  It will allow you to easily modify the spacing yourself.  Hope to have a version that you can try in the next several days.  Will post here when available.

**Comment by chrissimpkins** [comment]
Long overdue and now available for testing by the "clown car tight" and "loosey goosey" crowds...

The initial release of the new line spacing adjustment tool is now available.  Feel free to give it a try and please provide feedback on the tool repository if you encounter any issues.

More details in this new issue report: https://github.com/chrissimpkins/Hack/issues/191

**Comment by chrissimpkins** [comment]
I’d be interested in feedback about this line spacing adjustment tool (https://github.com/chrissimpkins/Hack/issues/28#issuecomment-201744618) if you have time to give it a try.  I am looking into the metrics that influence line spacing on different platforms x different editors.  There may be a bit of tinkering with the tool to achieve cross-platform consistency in line spacing across Linux, OS X, and Windows.

Please let me know what you think.  Thanks much.

**Comment by chrissimpkins** [comment]
Closing issue report now that the line spacing tool is available.  We do not intend to modify the default line spacing or release other spacing variants at this point. Please reopen if you need and submit any issues with the tool on that repository.

**Comment by chrissimpkins** [comment]
Line spacing shell scripts are now available and automate this within the range 10 - 30% UPM size (in 5 percentage point increments).  Drop the script in a directory with **only** your Hack fonts and execute it.

They are available here:

https://github.com/chrissimpkins/Hack/tree/master/tools/line-spacing
