### ISSUE TITLE
Modify Cyrillic c to differentiate from Latin c

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#29]
Request from #22 

Problem: the Cyrillic and Latin c characters have the same shape and it is not possible to distinguish them in text.

Goal is to create visually distinct glyphs for these characters that have the same shape but different Unicode positions (and therefore can cause errors in code).

**Comment by chrissimpkins** [comment]
Queued for next release

**Comment by jublo** [comment]
Suggestion for `cyrillic capital letter es`:

![capital](https://cloud.githubusercontent.com/assets/6348321/10267510/9762031a-6a97-11e5-860d-8145cdb6eacf.png)

**Comment by jublo** [comment]
Suggestion for `cyrillic small letter es U+0441`:

![small](https://cloud.githubusercontent.com/assets/6348321/10267550/d9e23ba0-6a98-11e5-8c0c-e2795dca19f2.png)

**Comment by jublo** [comment]
Note how the shorter top arm is visible even with small font size, and how the end angle takes up the appearance of the `t` angle.

**Comment by chrissimpkins** [comment]
I like the nuances but I think that they are going to be washed out at smaller text sizes.   When these are fit to the pixel grid, I suspect that they are going to look pretty similar.  I'm stuck on this one as well.   I don't know how to modify a c and continue to have it appear like a c.  A short stroke directly through the middle of the glyph?  Short serif at an angle across the upper terminal?  One of the commenters in the original Cyrillic character set issue report thread (#22) recommended the latter.   Here is a mockup image that they linked:

https://camo.githubusercontent.com/61ca464a14bb824d6646e787fd41f29c69bea849/687474703a2f2f692e696d6775722e636f6d2f326c39797a76652e706e67

**Comment by chrissimpkins** [comment]
Changes that will be included in the v2.016 release are displayed in #22

**Comment by chrissimpkins** [comment]
Available in v2.016 test builds:

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release
