### ISSUE TITLE
[Linux, OS X, Windows] Bold baseline differs from Regular baseline

### ISSUE THREAD

**Issue by ptomato** [chrissimpkins/Hack#32]
Perhaps best illustrated by a screenshot:
![screen shot 2015-08-30 at 12 38 11 am](https://cloud.githubusercontent.com/assets/459371/9566199/2b1e86a4-4eb0-11e5-9af6-3b31f45483b3.png)
(those are two different windows side by side, Sublime Text and Gnome Terminal)

The baseline of Bold text is one pixel higher than that of Regular text. This happens at 8, 9, and 10 point, and does not happen with Bold Italic.

It also probably has to do with the font rendering stack on Gnome because I've seen it on Debian 8.1 (Gnome desktop) but not on Mac OSX 10.10.

**Comment by chrissimpkins** [comment]
Looking into this.  Let me check the actual positions in the font editor and play in a few text editors.  I haven't noticed this and (thought that) I confirmed that all sets were properly aligned to the baseline.  Thanks for reporting it.

**Comment by ghost23** [comment]
This also happens on sublime on windows.

**Comment by johnfraney** [comment]
I'm also finding this in `gnome-terminal` and `terminator` (Arch Linux, 4.1.6-1 x86_64, Gnome Shell 3.16.3). >=11 pt looks as expected.

**Comment by chrissimpkins** [comment]
I can confirm that the glyph position is properly oriented on the baseline in the bold and regular sets.  Can you confirm that you are using the ttf and not the otf files (both Windows and Linux users)?

**Comment by pmoroney** [comment]
I have this issue and I am using the web font from the CDN with the Secure Shell extension for Chrome on my Chromebook Pixel at size 9. Here is a screenshot. You can see that the bold fonts are a different size and hang down over the command bar in Vim. Let me know if there is anything I can do to help test.
![screenshot 2015-08-31 at 22 05 35](https://cloud.githubusercontent.com/assets/8905568/9596047/87847584-502c-11e5-9a3b-0e1fc0d94c8e.png)

**Comment by ptomato** [comment]
I'm using the TTF files on Linux.

**Comment by ghost23** [comment]
yes, using ttf on Windows.

**Comment by johnfraney** [comment]
TTF here, too.

**Comment by fernandaparisi** [comment]
Using TTF on Mac OSx 10.10.4, found the same issue using Sublime text 2:

![screen shot 2015-09-01 at 15 48 25](https://cloud.githubusercontent.com/assets/1117355/9613319/fd003318-50c0-11e5-98ca-e420bc72e938.png)

**Comment by chrissimpkins** [comment]
@ptomato what editor are you using on OS X 10.10?  I thought that this was going to be a hinting issue until @fernandaparisi reported this on OS X.  Let me dig into the vertical metrics.  The problem may lie there.  

It doesn't show up on my system (OS X 10.10.5) in Sublime Text 3.  Here are images at 12px and 8px.  I tested 10px and can confirm that I am not seeing it there either.

<img width="408" alt="screen shot 2015-09-01 at 3 04 34 pm" src="https://cloud.githubusercontent.com/assets/4249591/9613700/077e104a-50bb-11e5-9f41-bd4510b31cb0.png">

<img width="416" alt="screen shot 2015-09-01 at 3 11 47 pm" src="https://cloud.githubusercontent.com/assets/4249591/9613851/ee6f8524-50bb-11e5-9b72-ff27457b50fe.png">

**Comment by fernandaparisi** [comment]
@chrissimpkins I was using 14px for size. Tried 12px and 10px and the line height difference was gone.

12px
![screen shot 2015-09-01 at 16 17 01](https://cloud.githubusercontent.com/assets/1117355/9613966/15619916-50c5-11e5-8412-5b02364be6ad.png)

10px
![screen shot 2015-09-01 at 16 17 28](https://cloud.githubusercontent.com/assets/1117355/9613967/156312b4-50c5-11e5-82e3-d72df02d20e1.png)

**Comment by chrissimpkins** [comment]
@fernandaparisi  hmmm... I am stumped.  OK let me give this a bit of thought. Thanks for sharing this.  That is helpful.

**Comment by ptomato** [comment]
@chrissimpkins I'm using Sublime Text 3 on OSX 10.10.5, but with the OTF, not TTF, fonts. I did not previously see the problem there because until I read @fernandaparisi's message above, I had not tried 14pt. (Thanks @fernandaparisi!) I can confirm that I also have the problem at 14pt size.

**Comment by chrissimpkins** [comment]
I can confirm that the bold set is aligned to the baseline.  The baseline is shaded in the images below and I confirmed that the characters are positioned at 0 units (i.e. right on the baseline) where there are no bowls that overhang.  The latter is an intentional design issue to make these curved lower areas of the glyphs appear to align on the baseline.  If you don't provide this overhang, they appear to high relative to other glyphs.

Here are the bold upper case:
<img width="958" alt="caps" src="https://cloud.githubusercontent.com/assets/4249591/9905284/1de8a2d0-5c52-11e5-86d8-9bd8a8183383.png">

And the bold lower case:
<img width="950" alt="lower" src="https://cloud.githubusercontent.com/assets/4249591/9905293/23b20dd2-5c52-11e5-945b-4a9f5825a3fb.png">

Let's check one thing before I dig into the hints.  Do you mind setting the bold characters in your editor to **only** those that do not have an overhang past the baseline.  Use only glyphs like the `Ff`, `Hh`, or `Tt`.  I'd like to confirm that this isn't causing these to snap up by a pixel for some reason.

**Comment by ptomato** [comment]
@chrissimpkins Here's a screenshot of what that looks like (OSX 10.10, Sublime Text 3, OTF fonts at 14pt size); the baseline is still different between the bold and regular characters.
![screen shot 2015-09-16 at 10 13 52 am](https://cloud.githubusercontent.com/assets/459371/9912405/4e6fc942-5c5c-11e5-85c5-2a4e84fccc35.png)

**Comment by chrissimpkins** [comment]
OK that's great.  Just a thought.  Let me look at the hinting at those larger point sizes.  To confirm this goes away below 14px too?

**Comment by ptomato** [comment]
@chrissimpkins That's right, below 14px everything is normal. For comparison here's the same text at 32pt:
![screen shot 2015-09-16 at 10 31 53 am](https://cloud.githubusercontent.com/assets/459371/9912800/40044aa2-5c5e-11e5-9a45-9b9c813bc0f2.png)

**Comment by chrissimpkins** [comment]
Thanks for the new image.  Will update when I have more information.

**Comment by chrissimpkins** [comment]
So I checked the hints with the freetype grid viewer and this does not appear to be the source of the problem.  Here are the hinted freetype2 renders on the grid at 8pt and 18pt.  I looked at all text sizes from 6 - 32pt in both the regular and bold set.  The bold glyphs never get nudged off of the baseline.  

#### Regular
<img width="316" alt="lower-a-8" src="https://cloud.githubusercontent.com/assets/4249591/9919602/0d4464a6-5c9c-11e5-8be8-adc28c1402b3.png">

<img width="319" alt="lower-a-18" src="https://cloud.githubusercontent.com/assets/4249591/9919603/10699fac-5c9c-11e5-8436-4a345ed17ab9.png">

#### Bold
<img width="321" alt="lower-a-bold-8" src="https://cloud.githubusercontent.com/assets/4249591/9919607/145a4d32-5c9c-11e5-9cd8-9efbd6cb33d4.png">


<img width="318" alt="lower-a-bold-18" src="https://cloud.githubusercontent.com/assets/4249591/9919610/195dd330-5c9c-11e5-80df-dff71f46bd54.png">

Let me look at the vertical metrics tonight.  I may generate a few test builds with different vertical metrics if you are willing to try them.

**Comment by chrissimpkins** [comment]
New test build with updated vertical metrics is now available in #111.  Please give these builds a try and let me know what you are seeing on your platforms.  I think (hope) that this should take care of this problem.

Thanks

**Comment by ptomato** [comment]
Yes, that build seems to fix things for me; I tried on OS X / Sublime Text 3 and Fedora Linux / Sublime Text 3 and Terminal (Gnome desktop).

**Comment by ghost23** [comment]
Tested on Windows 10, Sublime 3, works. Nice!

**Comment by chrissimpkins** [comment]
@ptomato @ghost23 Excellent, good to hear.  How do the line height changes render on Linux and Win 10?  Any thoughts about the tighter spacing?  I'd be interested in hearing whether you feel that this is an improvement.

**Comment by fernandaparisi** [comment]
@chrissimpkins I still got the baseline difference on OS X, using Sublime Text 2, at 14px, ttf version. 

![screen shot 2015-09-21 at 08 08 03](https://cloud.githubusercontent.com/assets/1117355/9990636/3bd8c988-6039-11e5-912e-22bdc7581359.png)

![z4l5uv](https://cloud.githubusercontent.com/assets/1117355/9990626/21a2096c-6039-11e5-98f2-0d1369577a81.gif)


But on Text Edit, using rich text mode, it seems OK:

![screen shot 2015-09-21 at 08 18 10](https://cloud.githubusercontent.com/assets/1117355/9990656/56941b60-6039-11e5-8bff-5d1a7017eca3.png)

Also on Terminal:

![screen shot 2015-09-21 at 08 24 37](https://cloud.githubusercontent.com/assets/1117355/9990771/3f6b5150-603a-11e5-906e-e9c7b87b70cb.png)

Maybe the issue is with Sublime Text autocomplete tooltip?
I manually removed the previous font version and installed the new test build.
If you need me to run any additional tests, let me know.

**Comment by chrissimpkins** [comment]
@fernandaparisi did Sublime Text happen to stay open between font installs?  it seems to cache font files for me (in version 3 series).  If so, will you close and reopen it to see if that works?

**Comment by fernandaparisi** [comment]
@chrissimpkins It was closed. I'll need to restart my computer soon, and I'll run the test again.

**Comment by fernandaparisi** [comment]
@chrissimpkins ha, a good old restart was all it needed :)

![screen shot 2015-09-21 at 08 54 48](https://cloud.githubusercontent.com/assets/1117355/9991217/7fe64c7c-603e-11e5-9dd5-7c4741c6ac07.png)

**Comment by chrissimpkins** [comment]
@fernandaparisi Excellent!  Thank you very much for testing it Fernanda.  Glad to hear that this addressed it.

Thanks to all of you for your help with this.  I believe that this was the first report of this problem and it was causing a number of subtle associated issues.  I will leave this thread open until we push it with the next release build.

**Comment by chrissimpkins** [comment]
@fernandaparisi Is that a cloud in your PS1 by the way?  Icon font?

**Comment by fernandaparisi** [comment]
@chrissimpkins it's from an oh-my-zshell theme called Cloud - https://github.com/robbyrussell/oh-my-zsh/wiki/themes#cloud

I don't know how they pulled off the cloud icon, tho :)

**Comment by chrissimpkins** [comment]
It looks like [they are using a Unicode symbol character](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/cloud.zsh-theme#L2) (U+2601, `☁`).

It must be from a fallback font.  Thanks!

**Comment by chrissimpkins** [comment]
These changes are now included in the v2.015 release.  Thanks to all for your contributions with this issue report and all of the testing that you performed on this issue.  This led to a change that affected a large number of users.  I greatly appreciate all of your help.
