### ISSUE TITLE
Feature Request: Center asterisk glyph

### ISSUE THREAD

**Issue by theckman** [chrissimpkins/Hack#34]
This may just be an opinion thing, but I find that the asterisk looks better when centered on the line instead of being elevated:

Menlo for Powerline:
![Menlo for Powerline](https://cloud.githubusercontent.com/assets/787332/9566496/80c6a1ca-4ebc-11e5-987a-3bd9bd49f81a.png)

Hack:
![Hack](https://cloud.githubusercontent.com/assets/787332/9566501/8a083b9a-4ebc-11e5-8968-49deb0b84d90.png)

I know this may not be a possibility, but thought I'd throw up an issue for consideration as it is an opinion thing.

**Comment by chrissimpkins** [comment]
This is definitely a style issue.  I have always been partial to an asterisk set higher in the box and to me it is more appealing for an idiom such as a C pointer definition.  I've seen the comments about the asterisk as a multiplication operator which, in retrospect, I do feel would be better positioned lower.  I'll leave this open and see what we can do with some alternate builds.  You are not alone in this opinion.

Thanks for the feedback.  This is very helpful.

**Comment by chrissimpkins** [comment]
Addressed this (partially) in test build v2.014.  The asterisk is now closer (but not at) center.  Hope that this is a good compromise.  Let me know what you think.

Available in #111

**Comment by chrissimpkins** [comment]
No further feedback here so going with the current asterisk design change that took place as the result of this issue report.
