### ISSUE TITLE
Tilde at 8pt look like a minus sign.

### ISSUE THREAD

**Issue by ScuzzyEye** [chrissimpkins/Hack#37]
The tilde at 9pt looks fine, but when going down to 8pt it becomes indistinguishable from a minus sign.

![hack tilde](https://cloud.githubusercontent.com/assets/14045149/9569526/42ec8c86-4f3c-11e5-83ef-3a09b1c6b03e.png)

**Comment by chrissimpkins** [comment]
Platform and editor?

**Comment by ScuzzyEye** [comment]
Windows, Visual Studio 2013.

**Comment by F30** [comment]
They're hard for me to distinguish even at 12 pt. I'm using Hack in the OS X terminal on retina as well as non-retina screens.

**Comment by chrissimpkins** [comment]
Thanks for reporting this. I will take a look and see if I can make it render better in these size ranges.  Will let you know when there is a new build that addresses this.

**Comment by nobe4** [comment]
+1 for this issue, I experience the same 
![screen shot 2015-09-03 at 11 06 35](https://cloud.githubusercontent.com/assets/2452791/9654545/c26c1840-522b-11e5-8aff-97d5ea2729fc.png)

Config : OS X Yosemity,MacVim, Iterm2, Tmux

**Comment by chrissimpkins** [comment]
Are you using the ttf or otf builds?

**Comment by ScuzzyEye** [comment]
I'm using the OTF.

**Comment by chrissimpkins** [comment]
Do you mind trying the new ttf files to see if the glyph renders better with those?  I'm guessing that this will work better on Windows.  +/- on Linux.  Probably not on OS X but I would be interested in hearing either way.  May need a glyph re-design to make it more apparent at smaller sizes.

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by ScuzzyEye** [comment]
The TTF is definitely better on Windows. But I think I'd still prefer a little more height to the symbol.

![hack ttf tilde](https://cloud.githubusercontent.com/assets/14045149/9655444/fd8bd668-51fe-11e5-8820-30a251dca97c.png)

**Comment by chrissimpkins** [comment]
@F30 here is how they render for me on an OS X Retina display in 

Sublime Text at 12px

<img width="135" alt="tilde" src="https://cloud.githubusercontent.com/assets/4249591/9655311/3e6a9f12-51fe-11e5-811e-4cdc6773c580.png">

iTerm2 at 12px

<img width="52" alt="tilde-iterm2" src="https://cloud.githubusercontent.com/assets/4249591/9655316/43e9434e-51fe-11e5-8cb8-5f96e768465b.png">

Are you scaling your Retina monitor so that the glyphs are smaller?

I think that we need to extend the tails of the glyph a bit and perhaps give it a bit more of a wave appearance to make this more apparent across systems.

**Comment by chrissimpkins** [comment]
@ScuzzyEye I would definitely stick with the TrueType files on Windows.   I think that you will see better rendering at smaller sizes across the board.  Point well taken though.  I will see what I can do with this glyph.  Thanks much for pointing this out.

**Comment by F30** [comment]
@chrissimpkins I'm runnning my retina display in the middle mode between "Default" and "More Space", this means 1440 x 900 space on a 2560 x 1600 display. However, I don't think it's an issue of resolution for me.

Here's a screenshot from a non-retina display, as it much closer resembles the impression I get when viewing it from a normal working distance:

![tilde](https://cloud.githubusercontent.com/assets/2017238/9655726/82e5f8e6-5233-11e5-8196-277fcd165513.png)

It's not that the tilde isn't distinguishable, but I always have to take a closer look; especially without direct comparison. I'd definitely appreciate a refinement of this glyph.

**Comment by chrissimpkins** [comment]
@F30 understand.  we will fix it.

**Comment by lluixhi** [comment]
I have the same problem on Linux in NeoVim. I'm using the OTF font.

![tilde](https://cloud.githubusercontent.com/assets/3643824/9829731/d2d9aaac-58c6-11e5-80f1-8ff8e4ea26d5.png)

**Comment by chrissimpkins** [comment]
@lluixhi thank you.  I hope to have a round of these glyph fixes included in the next release.

**Comment by chrissimpkins** [comment]
Addressed this in the new test build (v2.014).  Brand new glyph with increased height, wider curves. This should be much more legible at smaller text sizes.  Please let me know how it renders on your systems.

Files available in #111

**Comment by ScuzzyEye** [comment]
The shape looks good now.
![hack tilde 2_014](https://cloud.githubusercontent.com/assets/14045149/9986293/d20b8746-6008-11e5-8393-a391d7bd94af.png)

It looks like it sits a little low. I'd prefer it to be even with the midline, but now I'm just picking nits. The shape is completely usable.

**Comment by chrissimpkins** [comment]
@ScuzzyEye No, I agree with you.  It was centered (approximately) on lowercase glyphs and as I've worked with it a bit, I think that it will look better a bit higher in the box as well.  This is helpful.  Will push it a bit higher in the next build.

**Comment by chrissimpkins** [comment]
otf files with the new tilde glyph are now available as of v2.015 (a general release build) for those who would like to give them a try.

Leaving this open to reposition the tilde slightly higher in the box.  Didn't get it into this one

**Comment by jublo** [comment]
This one has been moved up somewhat, what do you think?

![asciitilde](https://cloud.githubusercontent.com/assets/6348321/10267610/169abec6-6a9b-11e5-8766-74757fcf4956.png)

**Comment by ScuzzyEye** [comment]
I just had to see where there hyphen hits against the : and =. Yeah, that should be good.

**Comment by chrissimpkins** [comment]
@jublo looks great.  Is this change included in one of your builds in your fork?

**Comment by chrissimpkins** [comment]
These changes are now included in the vfb source of the development branch and will be included in the next build.

**Comment by chrissimpkins** [comment]
A new test build is available that includes a change in the position of the tilde glyph.  Please let us know what you think.


[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by ScuzzyEye** [comment]
Looks good now. Matches up with the equals nicely. Here's my usual screen shot.
![mid-line tilde](https://cloud.githubusercontent.com/assets/14045149/10422019/3c4fd6fa-7082-11e5-805c-330e8acb7078.png)

**Comment by chrissimpkins** [comment]
@ScuzzyEye: great!  thank you very much for checking.  We will include this in the next release.  I appreciate the issue report.

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release
