### ISSUE TITLE
[Linux] Increased font spacing in Emacs

### ISSUE THREAD

**Issue by mjgiarlo** [chrissimpkins/Hack#38]
Is anyone successfully using Hack in Emacs?  I'm using it in Prelude (Emacs 24) and I see odd spacing when I set my font to Hack-Regular (have tried different sizes, from 9 to 12, with the same behavior).  Interestingly, I don't see the same with either Hack-Bold or Hack-RegularOblique. See screenshots below.

First, with the oblique font (looks purty, if slanty):

![screenshot from 2015-08-30 17 36 01](https://cloud.githubusercontent.com/assets/131982/9570341/adc47428-4f3d-11e5-9fcb-013771fa4175.png)

Now, with the regular font (wat):

![screenshot from 2015-08-30 17 35 36](https://cloud.githubusercontent.com/assets/131982/9570342/afc7090c-4f3d-11e5-91b5-585dca75643a.png)

Any ideas?  I downloaded the Hack-v2_010-ttf.zip as the README suggests for Linux installations, and tossed the .ttf files in my `~/.fonts` folder.  I'm using the same font w/ the same face just fine in Byobu/Tmux.

**Comment by abramhindle** [comment]
I have the same problem with TTF: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7), Ubuntu 14.04.3 LTS, Gnome-Shell. Oblique doesn't have this problem.

**Comment by chrissimpkins** [comment]
Stumped on this one.  First report I have seen with a spacing issue like this.  It looks like it is increasing the em box size for every glyph so that the glyph size stays the same but the sidebearings get really wide.  Let me look into Emacs rendering/spacing.  I'm not familiar with it.

Mind giving the otf files a try to see if the same issue occurs?

**Comment by abramhindle** [comment]
I think I have successfully installed the .OTF files, but it seems to have the same response. I wish I had a virtualized ubuntu handy to be completely sure.

**Comment by mbunkus** [comment]
I have the very same spacing problem with Hack 2.010, GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.2) on Arch Linux with the TTF. The OTF, however, looks just fine.

**Comment by Paethon** [comment]
Yes, I can confirm this. Spacing in emacs is totally off (GNU Emacs 24.4.1)

**Comment by mjgiarlo** [comment]
The OTF font works A-OK for me too. That suggests two courses of action to me:

1. Change the README to recommend using OTF fonts (#worksforme)
1. "Fix" the TTF fonts to render as expected in Emacs and Emacs-like environments.

Pls advise on whether I should close this issue or not. (I'm satisfied now, FWIW.  Thanks, all! :clap: )

**Comment by XANi** [comment]
OTF one still have weird vertical spacing issue, compare (dejavu)
![zaznaczenie_2015-08-31_002](https://cloud.githubusercontent.com/assets/147394/9582809/eb55157a-5007-11e5-8771-a7f9e4b8f51b.png)

to (hack otf, but it is same for ttf)
![zaznaczenie_2015-08-31_001](https://cloud.githubusercontent.com/assets/147394/9582821/fb1c9668-5007-11e5-94cf-9496b1583704.png)

**Comment by eneq** [comment]
Same issue but otf works fine.

I am coming from a DejaVu Sans Mono and I would switch if it weren't for the _ spacing, as a C developer I really dislike it.

**Comment by ndegruchy** [comment]
:+1: for the OTF fix. I actually came here because I couldn't figure out why Emacs was behaving so weird after seeing this font in it.

**Comment by chrissimpkins** [comment]
Are you noticing any rendering issues on Linux with the otf files?  The difference in the PostScript hinting and TrueType instruction sets are bound to raise different rendering issues on different platforms.  In general, the TT instructions render better on the screen.  Let's leave this issue open and I will probe in more detail so that I can determine what the problem was with the ttf files.

**Comment by chrissimpkins** [comment]
and thanks for sharing the fix!

**Comment by mjgiarlo** [comment]
I'm perfectly happy with the OTF files, so far.

**Comment by ndegruchy** [comment]
@chrissimpkins Not that I can tell, anyway. I am running Arch Linux with the Infinality patches to fontconf, etc.

Here's a screenshot of a test page:
![screenshot_20150831_151902](https://cloud.githubusercontent.com/assets/306013/9588034/d70515ca-4ff3-11e5-98de-d29ef4efd67f.png)

Not really sure what I'd be looking for, to be honest.

**Comment by schauveau** [comment]
I am not a font expert but I noticed something interesting. 
When dumped with fc-query there is no spacing value in the output for Hack-Regular.ttf like in other monospace fonts:
# fc-query Hack-Regular.ttf | grep spacing

VeraMono has spacing
# fc-query VeraMono.ttf | grep spacing
        spacing: 100(i)(s)

But regular Vera does not
# fc-query Vera.ttf | grep spacing

The Hack-Bold.ttf file has spacing and works fine in Emacs
# fc-query Hack-Bold.ttf | grep spacing
            spacing: 100(i)(s)

**Comment by schauveau** [comment]
For the OTF fix, there is an annoying issue: The 'u' characters is significantly higher than other characters. 

That does not happen with all fontconfig setting. I noticed it with no autohinting and with full hinting.

**Comment by eneq** [comment]
I do have some issues with Hack (otf) in Emacs, particularly in C-mode and font-lock. There are some blurring issues that's not evident when using DejaVu Sans Mono or TTF in Windows.

I uploaded a few snapshots to give some visuals to what I see...

![hack-win](https://cloud.githubusercontent.com/assets/208105/9589253/f927fbca-4fe1-11e5-817c-11b7b9f43b76.png)
![dejavu](https://cloud.githubusercontent.com/assets/208105/9589256/fddb7822-4fe1-11e5-9bfa-c0d5016d4576.png)
![hack](https://cloud.githubusercontent.com/assets/208105/9589257/ffde7a16-4fe1-11e5-9433-4647d3ffed88.png)

**Comment by fommil** [comment]
:+1: seeing same thing with TTF font in Debian Jessie Emacs 24.5

**Comment by schauveau** [comment]
Have a look to the https://github.com/chrissimpkins/Hack/issues/56
The TTF for build v2.011 mentioned in one of the later comments seems to solve the spacing problem

**Comment by mjgiarlo** [comment]
I'm not seeing any issues with the v2.010 OTF fonts, FWIW.

**Comment by jimvanm** [comment]
I have the exact same issue, in Windows, using UltraEdit (currently 21.30.0.1010, but earlier versions too). Only the 'regular' Hack font has the issue. The rest line up OK. The problem manifests itself as the cursor ending up in the wrong place. It's as if the cursor knows it's a fixed-width font, but the render of the font adds a few points to the spaces, so the cursor does not line up visually with the font it's affecting. I've attached a gif that attempts to demonstrate.
![ezgif-3568225737](https://cloud.githubusercontent.com/assets/14045300/10239621/4b44e3f8-689e-11e5-9374-1f1874e5e0f2.gif)

**Comment by chrissimpkins** [comment]
is this with the most recent version of Hack? v2.015

**Comment by jimvanm** [comment]
I did install the 2.015 version, but it didn't take. I uninstalled Hack completely, rebooted, and tried again. It appears to be working correctly now. Thanks for the reply.

**Comment by chrissimpkins** [comment]
excellent, possibly just a font caching issue then.  let me know if you see any other issues.

**Comment by jimvanm** [comment]
It's looking good.

Thanks so much for creating and releasing this font. It is such a pleasure
to view code with it!

Regards,

Jim

**Comment by chrissimpkins** [comment]
It's great to hear that!  Thank you very much for the feedback.  I really appreciate it.  Please let me know if you run into any other issues.

**Comment by ronilaukkarinen** [comment]
Removing all traces of Hack and reinstalling OTF fixed this for me as well. I'm on OS X and Sublime Text 3 ([related tweet](https://twitter.com/rolle/status/868821437892755456)).

OTF version is slightly sharper for some reason. Better, actually.
