### ISSUE TITLE
Too tall line height when compared to Andale Mono, whether at 9 or 8 points

### ISSUE THREAD

**Issue by verec** [chrissimpkins/Hack#39]
As the screenshots show, on a standard Apple header file. (font name and point size in the top right, font selector).

<img width="857" alt="screen shot 2015-08-31 at 01 39 32" src="https://cloud.githubusercontent.com/assets/25551/9570392/2821b5ca-4f82-11e5-98e7-c9dfda639db8.png">
<img width="859" alt="screen shot 2015-08-31 at 01 40 44" src="https://cloud.githubusercontent.com/assets/25551/9570393/284766b2-4f82-11e5-91de-987e13306248.png">
<img width="859" alt="screen shot 2015-08-31 at 01 41 11" src="https://cloud.githubusercontent.com/assets/25551/9570394/28479196-4f82-11e5-940b-9f928f4d0774.png">
<img width="860" alt="screen shot 2015-08-31 at 01 41 50" src="https://cloud.githubusercontent.com/assets/25551/9570395/28481dd2-4f82-11e5-8702-37bfad048ad1.png">

**Comment by theckman** [comment]
See #28

**Comment by chrissimpkins** [comment]
^^ I am working on tighter (and looser) vertical spaced versions to address these issues.  Thanks for reporting it.

**Comment by chrissimpkins** [comment]
Test version of the regular set is now available with tighter vertical spacing.

https://github.com/chrissimpkins/Hack/blob/vertical-spacing/build/test_builds/HackTight-Regular-h.ttf

Let's discuss in #28 where this was initially reported.

**Comment by chrissimpkins** [comment]
You are going to like the new test build.  Went tighter with the line spacing and I am looking for feedback on this.  Let me know what you think.

Available in #111

**Comment by chrissimpkins** [comment]
Line spacing shell scripts are now available and automate this within the range 10 - 30% UPM size (in 5 percentage point increments).  Drop the script in a directory with **only** your Hack fonts and execute it.

They are available here:

https://github.com/chrissimpkins/Hack/tree/master/tools/line-spacing
