### ISSUE TITLE
Submit to Google Fonts

### ISSUE THREAD

**Issue by Rowno** [chrissimpkins/Hack#40]
Consider submitting Hack to Google Fonts: https://github.com/google/fonts

**Comment by chrissimpkins** [comment]
I looked into this.  My read of their current inclusion policy is that they do not accept typefaces with reserved font names.  I would be happy to remove 'Hack' to get it in there, but Bitstream and Vera are reserved as well and that cannot be modified (Bitstream license).

**Comment by Rowno** [comment]
Thats unfortunate, Google Fonts does some clever things to optimise webfont delivery using unicode-range subsetting etc.

**Comment by chrissimpkins** [comment]
I can approach them about it to see how strict that policy is.

**Comment by n7s** [comment]
You will very likely have to streamline your licensing story beforehand. 
See http://scripts.sil.org/OFL-FAQ_web#96ba5916 for requirements about making derivatives of the OFL (using a different non-ambiguous name, dropping the preamble). Making your own incompatible licensing silo is less than ideal...

**Comment by chrissimpkins** [comment]
@n7s Thanks Nicolas.  I'd like to speak with someone at SIL about the licensing issues.  Are you an appropriate representative or can you recommend a contact?

**Comment by n7s** [comment]
yes, I'm happy to help with this, although I won't be available much over the next few days/weeks (and yes, you can probably see my name officially attached to the research and work around font licensing with SIL). BTW reading through the OFL FAQ should give you pretty good insights into these issues if you haven't thought through this already.

**Comment by chrissimpkins** [comment]
> BTW reading through the OFL FAQ should give you pretty good insights into these issues if you haven't thought through this already. 

Will read the document this evening and be in touch.  I appreciate your help.  Should I submit questions through the SIL contact form?

**Comment by n7s** [comment]
you can use my firstname.lastname @ sil org

**Comment by chrissimpkins** [comment]
Thank you very much.  I really appreciate it.  I will be in touch to discuss this with you.

**Comment by chrissimpkins** [comment]
Sent.


—
Chris

**Comment by markwoon** [comment]
Just curious: is this really not an option, or just dependent on #209?

**Comment by davelab6** [comment]
@markwoon I'm responsible for onboarding fonts to Google Fonts, and indeed, the licensing of Hack is a blocker - thats also why Vera and DejaVu are not available there

**Comment by markwoon** [comment]
That's such a shame.  Thanks for the update.

**Comment by chrissimpkins** [comment]
@markwoon we are working on it with @davelab6.  It may involve a reduced character set if it happens. Will let you know once Dave and I have had the opportunity to run the proposal by Google.

**Comment by kleinbottle** [comment]
Any progress on the Google Fonts front? Or is it a closed case? Thanks.

**Comment by chrissimpkins** [comment]
@kleinbottle unfortunately they won't review with the DejaVu upstream glyphs in the sets.  The fact that they committed these to the public domain is apparently the issue.  Something related to international use restrictions associated with the public domain decision as I understand the conversation with @davelab6.
