### ISSUE TITLE
Box glyphs don't close vertically

### ISSUE THREAD

**Issue by gavineadie** [chrissimpkins/Hack#41]
The box glyphs don't form continuous vertical lines .. horizontals are OK.  Note the gaps in the vertical lines below (from Xcode).  Menlo, SourceCodePro and other "coding" fonts get it right:

<img width="699" alt="screenshot 2015-08-31 00 28 40" src="https://cloud.githubusercontent.com/assets/343117/9572095/4adee520-4f77-11e5-903c-c27063c2f9f1.png">

**Comment by gavineadie** [comment]
.. on the other hand, subscripts do look nice:

<img width="618" alt="screenshot 2015-08-31 00 49 15" src="https://cloud.githubusercontent.com/assets/343117/9572236/3c66ab38-4f7a-11e5-97f3-edb95c8433aa.png">

**Comment by chrissimpkins** [comment]
> The box glyphs don't form continuous lines

Mind giving this same block of text a try with this test version that uses tighter vertical spacing?  It is renamed 'Hack Tight' so that it can be installed along with the release version.

https://github.com/chrissimpkins/Hack/blob/vertical-spacing/build/test_builds/HackTight-Regular-h.ttf 

I'll take a look at the position of the glyphs to confirm that this isn't an alignment issue with the glyphs themselves rather than a line spacing issue.

**Comment by gavineadie** [comment]
Sorry, Chris, that URL points to a web page, and a complete clone of the repo doesn't contain that font file.

**Comment by gavineadie** [comment]
It's a little tighter, but doesn't close the gap.  I do prefer the slightly tighter spacing though:

<img width="705" alt="screenshot 2015-08-31 10 39 45" src="https://cloud.githubusercontent.com/assets/343117/9581319/c9497a9c-4fcc-11e5-848b-86c5dc9a043b.png">

**Comment by chrissimpkins** [comment]
Close but no cigar.  OK, probably in the glyphs themselves.  Going to shelve this until I get the vertical spacing issues sorted out or else we would redo it anyways.  Will get back on it once I have a stable set of vertical metrics to work with.  Will be releasing at least one tighter vert spacing version along with the current spacing down the road.  Will let you know when ready.

**Comment by msharov** [comment]
Other double line joints also do not quite line up, with ╩ ═ ╧ being a pixel lower than ╔ ╦. I'm using 16 point Hack-Regular.

**Comment by chrissimpkins** [comment]
Vertical metrics were updated across the entire font with significantly tighter vertical spacing. Mind giving these fonts a try and let me know how close we are on these glyphs?  Thanks.

Available in #111

**Comment by gavineadie** [comment]
Looks good
<img width="698" alt="screenshot 2015-09-21 10 31 14" src="https://cloud.githubusercontent.com/assets/343117/9994604/0951376c-604c-11e5-83eb-855497e193d0.png">

Note, I'm not using the 'junction' glyph (mentioned by @msharov), just the 'straights' and 'corners' .. Thanks for your work on this.

**Comment by chrissimpkins** [comment]
Fantastic.  My original vertical metrics changes led to these problems.  We have requests for looser spacing variants so we will need to address this down the line again.  Thank you very much for looking into this issue again.

**Comment by chrissimpkins** [comment]
I will close this issue when we release these changes unless you have any other associated alignment concerns.

**Comment by chrissimpkins** [comment]
These vertical spacing changes are now included in v2.015.  Thank you very much for the issue report and the testing that you performed on this issue.
