### ISSUE TITLE
[JetBrains, IntelliJ, Java renderer] @ sign breaks in javadoc tags like {@link hello} in IntelliJ IDEA

### ISSUE THREAD

**Issue by jevring** [chrissimpkins/Hack#42]
The @ sign by itself works fine, and in any code and string literals, it works fine. This *could* be an issue with IntelliJ IDEA, but it seems to work fine for other fonts. I have included a sample image.
![hack_font_javadoc_failure](https://cloud.githubusercontent.com/assets/11088499/9573480/54a5b44e-4fbd-11e5-8dac-f65c40cbaeb5.png)

**Comment by jdhoek** [comment]
I have just installed Hack, but I cannot reproduce this in IntelliJ IDEA (Ubuntu Linux 15.04); `{@link hello}` works as expected.

Perhaps you could add some details such as your operating system?

**Comment by jevring** [comment]
Sure, I'm using Windows 7, IDEA 14.1.4.
It's anything defined as a @tag, so things like @author and any custom tags also get this behavior. In my style, which is the default, these tags are underlined. It could be that @ with an underline changes to this other character seen in the image.

**Comment by aGustafsson** [comment]
I have the same issue (Windows 8.1, PhpStorm 9.0.2). Happens for bold oblique @ character.

**Comment by chrissimpkins** [comment]
Checking the JetBrains issue reporting forums for similar reports.  This is the third rendering issue that has been reported so far in JetBrains editors.  It's not clear to me where the problem lies.  I will post new issue reports there if I don't come up with any existing information.

Updates to follow.

**Comment by eXtreme** [comment]
Having the same problem, Windows 10, IntelliJ IDEA 14.1.4, TTF hack font.

Even more bizzare stuff happens when I installed OTF version:

![image](https://cloud.githubusercontent.com/assets/197671/9586528/a250ad24-501d-11e5-896c-8630c6ac6202.png)

**Comment by chrissimpkins** [comment]
@jevring here is the same block with the ttf files in WebStorm on OS X (10.10.5) that (to my knowledge) uses the same Java renderer as IntelliJ:

<img width="403" alt="webstormimage" src="https://cloud.githubusercontent.com/assets/4249591/9587139/dfcbfed0-4fee-11e5-8ed1-b38501012b39.png">

On OS X the JetBrains editors render their own oblique for many (but apparently not all) fonts with too much slant.  This is a known issue on the OS X platform and they have received reports about it.  

Your issue seems to be Windows specific based upon your report and the one by @eXtreme.   I've confirmed that the same text block renders with only the large slant issues in PyCharm on OS X as well.

**Comment by chrissimpkins** [comment]
@eXtreme Do you mind adding the actual text that you used in that screenshot as a codeblock?  I'd like to see what glyphs are involved.

**Comment by eXtreme** [comment]
@chrissimpkins well it is nothing out of ordinary:

```php
/**
 */
class ApplicationController implements ClassResourceInterface
{
    /** @var EventDispatcherInterface */
    protected $eventDispatcher;
    /** @var ApplicationManager */
    protected $applicationManager;
    /** @var CommandBus */
    protected $commandBus;
    /** @var RouterInterface */
    protected $router;

    public function __construct(
        EventDispatcherInterface $eventDispatcher,
        ApplicationManager $applicationManager,
        CommandBus $commandBus,
        RouterInterface $router
    )
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->applicationManager = $applicationManager;
        $this->commandBus = $commandBus;
        $this->router = $router;
    }
```

it's just spaces.

And this is how it looks with "Consolas" font:

![image](https://cloud.githubusercontent.com/assets/197671/9587363/7e0b78f4-5022-11e5-8f42-a1a90c4ad9c0.png)

you can see these little dots where spaces are.

**Comment by chrissimpkins** [comment]
Received report via Twitter that a (possible) workaround on the JetBrains editors is to turn off the bold highlighting.  
![cn0sfrmwgaan_z8](https://cloud.githubusercontent.com/assets/4249591/9607443/32d4429c-5097-11e5-9ed9-be84e19c677e.png)

Clearly that may not be of interest to you if you like the bold highlighting, but I link it for any who wants to make this issue go away until it is resolved.  

Another message that there is a JetBrains bug report dealing with this:

https://youtrack.jetbrains.com/issue/IDEA-138241

in which they point the finger at Java:

https://bugs.openjdk.java.net/browse/JDK-8078382

More info when available.  I will follow up on these issues and pass along any information that I receive.

**Comment by chrissimpkins** [comment]
Will you please give these new builds a try (v2.012)?  I've updated the name tables and adjusted the font names based upon what is currently recommended for cross-platform support.  Let's see if this addresses this issue.

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by jevring** [comment]
Now everything looks good. Thanks! =)

**Comment by chrissimpkins** [comment]
excellent!

**Comment by chrissimpkins** [comment]
Thanks for the issue report and for your testing to implement this fix.  It is now live in release v2.013.
