### ISSUE TITLE
[Windows 7, IntelliJ] the "g" character is sometimes not properly displayed

### ISSUE THREAD

**Issue by heymjo** [chrissimpkins/Hack#45]
Hi,

I noticed that the "g" in below line of java code sometimes is not displayed properly, it looks like a "q". Behaviour seems to depend on where the caret is in the current file. Sometimes it shows fine sometimes not.

![clipboard02](https://cloud.githubusercontent.com/assets/193792/9574708/7795b9c0-4fc9-11e5-929c-7e99e71e0e67.jpg)

**Comment by heymjo** [comment]
actually it happens with other characters ("j") as well, see below gif where i traverse a snippet of xml from top to bottom. Note when i move the caret back up the characters are restored line after line !

![test](https://cloud.githubusercontent.com/assets/193792/9575023/9fc37c2c-4fcc-11e5-97b4-50b5ef2af34c.gif)

**Comment by chrissimpkins** [comment]
bizarre.  OK, likely a vertical spacing issue in this editor.  will create a few spacing variations that we can try to see if they address it.

**Comment by chrissimpkins** [comment]
I am combing the JetBrains issue reporting forums today.  There are now several issues reported for the JetBrains editors that have not been reported for other editors (yet).  Will add a new issue report if I can't come up with anything.  

Updates to follow when I have them.

**Comment by heymjo** [comment]
alright cool, let me know if you want me to test something !

**Comment by Tiim** [comment]
I tried using build v2.011 like suggested in #77 but the issue remains unchanged.

![intellij_hack_font](https://cloud.githubusercontent.com/assets/1063187/9655535/fbe43e76-5231-11e5-8254-9f42c9a37cbc.gif)

**Comment by chrissimpkins** [comment]
Will you please give these new builds a try (v2.012)?  I've updated the name tables and adjusted the font names based upon what is currently recommended for cross-platform support.  Let's see if this addresses this issue.

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by Tiim** [comment]
Unfortunately the issue is still persists.

**Comment by chrissimpkins** [comment]
OK. I hoped this would be related to the name issue in these editors.  Back to the drawing board...

**Comment by heymjo** [comment]
Hi,

Tried the latest release, still same error but noticed that this only happens for font-size 12. As you can see in this gif i am changing the font size to 10-11-12-15 , only on 12 you can see these characters being clipped. Hoping this sheds some light on the problem !

![only-size-12](https://cloud.githubusercontent.com/assets/193792/9733593/c8079db0-562c-11e5-873a-ab98d7d707c3.gif)

**Comment by chrissimpkins** [comment]
@heymjo Thanks for this info.  Do you happen to know if this occurred at other text sizes in prior releases?  I wouldn't expect any of the changes that were included in this release to influence this problem.  Does it happen to go away at the 12px size when you adjust the line spacing setting to a larger (or smaller) value?

**Comment by heymjo** [comment]
Changing the line spacing does not make a difference. Indeed, previous versions have exactly the same behaviour only at size 12.

**Comment by chrissimpkins** [comment]
@heymjo thank you

**Comment by chrissimpkins** [comment]
This is a priority and I intend to address it this weekend.  I know this is interfering with your use.  I have a few thoughts and will make some test builds that we can try.  



—
Chris

**Comment by heymjo** [comment]
Great , thanks as lot !

**Comment by chrissimpkins** [comment]
I'm hoping that the new test build (v2.014) addresses this issue.  Vertical metrics have been updated. Please let me know how these files work. 

They are available in #111

**Comment by heymjo** [comment]
Fantastic, the issue has been resolved for me in this version :+1: . I am now going to use it as default font, many thanks and keep up the great work !

**Comment by chrissimpkins** [comment]
Great to hear this!  Any thoughts on the tighter spacing?

**Comment by heymjo** [comment]
For me it still looks good, but then again i was not so picky about it in the first place :-)

**Comment by chrissimpkins** [comment]
@heymjo That's great.  Good to hear this.  Waiting for a bit more input and will likely make this the default.  We are planning some additional builds with looser spacing and can consider going even tighter if anyone wants this.

**Comment by heymjo** [comment]
Reopening, unfortunately this behaviour has regressed from the .14 to the .15 release. Annoying because i did not keep the .14 release archive from #111  and it seems to have been removed :-|

**Comment by chrissimpkins** [comment]
I did a bit of repository cleanup.  The test build is still there.  Here is the link if you want it:

https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_014/2_014.tar.gz?raw=true

Question is why this changed between the builds.  To confirm, this is in IntelliJ IDEA on Windows?

**Comment by chrissimpkins** [comment]
Do you mind checking issue #100 as well?  This seems to be an associated issue and there is an active issue report on the JetBrains issue tracker about it:

https://youtrack.jetbrains.com/issue/IDEA-144785

**Comment by heymjo** [comment]
Hi, 

Strange things happening. It seems that when i first uninstall the font (going to the fonts directory and doing shift-delete), and only then install the new version it works fine. 

What i did previously was just installing the new font on top of the old one and then the problems started to appear again. So i confirm that the latest version is working fine still :+1:

**Comment by chrissimpkins** [comment]
excellent! the cache is our enemy.  :)
