### ISSUE TITLE
There's no visualize whitespace dots

### ISSUE THREAD

**Issue by EXL** [chrissimpkins/Hack#46]
Hi! Big thanks for font, it really is beautiful.

I use a useful visualize whitespace function in the Qt Creator IDE, and the Hack font is unfortunately not supported whitespace dots. But the symbols of end-of-file (diamond ◆), the tabulation (arrow →) and line break (downwards arrow↲) are displayed normally.

Screens. 
Consolas:
![Consolas](http://wstaw.org/m/2015/08/31/Untitled18.png)

Hack:
![Hack](http://wstaw.org/m/2015/08/31/Untitled19.png)

Maybe you missed the glyph with the necessary point?

**Comment by rspieker** [comment]
Like above, a big thanks!
Besides the whitespace character does not showing up (in BBEdit), it appears wider than a plain space character (if I turn off 'show invisibles > spaces' it aligns properly).

Whitespace - visible
![whitespace visible](https://cloud.githubusercontent.com/assets/981813/9575737/2cca8980-4fd2-11e5-851b-dfdb7d41e508.png)

Whitespace - hidden
![whitespace hidden](https://cloud.githubusercontent.com/assets/981813/9575746/3c4f188a-4fd2-11e5-9173-42ddf167098b.png)

**Comment by chrissimpkins** [comment]
@EXL I am assuming that this is the middle dot character that it is using (U+00B7)?

@rspieker Checking on it.

Thanks for reporting both of these issues.

**Comment by rspieker** [comment]
According to the [BBEdit 10.5.3 release notes](http://www.barebones.com/support/bbedit/arch_bbedit1053.html), you are correct that `U+00B7` is now used
> The display glyph for invisible spaces (when "Show Invisible" and "Show Spaces" are both turned on) is now U+00B7 (MIDDLE DOT). If spaces don't display when those settings are turned on, then your display font is missing that glyph, and you should report it to your font's developer as a bug. (I would have used U+1427 (CANADIAN SYLLABICS FINAL MIDDLE DOT) for the humour value alone, but not enough fonts supported that glyph. Sorry.)

It used to be different, according to [this ancient post](http://head-lights.blogspot.nl/2009/07/bbedit-characters.html), where the following characters where used:
- Carriage returns: `0x00AC` (172), unicode name "NOT SIGN" (¬)
- Nonprinting characters: `0x00BF` (191), unicode name "INVERTED QUESTION MARK" (¿)
- Non-breaking spaces: `0x2022` (8226), unicode name "BULLET" (•)
- Tabs: `0x2206` (8710), unicode name "INCREMENT" (∆)
- Spaces: `0x25CA` (9674), unicode name "LOZENGE" (◊)

**Comment by Yoshi325** [comment]
Also called an Interpunct: https://en.wikipedia.org/wiki/Interpunct

Unfortunately I cannot use this font while it is lacking this character. If possible, please add it.

**Comment by chrissimpkins** [comment]
Thanks for the reports.  Working on it.

**Comment by ezekg** [comment]
:+1:

**Comment by coredumperror** [comment]
Just chiming in to say that Eclipse also fails to show spaces as dots. Paragraph and tab characters display fine, though.

**Comment by chrissimpkins** [comment]
v2.011 is a test build of the ttf files that includes the middle dot glyph in all sets and adjustment in the width of the em box of this glyph that (hopefully) caused the issues reported here and in #27. 

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

Let me know if this addresses these issues.

**Comment by rspieker** [comment]
Yep, all four are now properly displaying! Thank you for the speedy fix and keep up the good work!

Regular
![Regular](https://cloud.githubusercontent.com/assets/981813/9592381/a9552e22-5042-11e5-88c1-b9a8e5748da2.png)

Oblique
![Oblique](https://cloud.githubusercontent.com/assets/981813/9592393/d2350f56-5042-11e5-8db3-e7873de251d8.png)

Bold
![Oblique](https://cloud.githubusercontent.com/assets/981813/9592404/df1a98c6-5042-11e5-9f1f-06b095ee5e0a.png)

Bold Oblique
![Bold Oblique](https://cloud.githubusercontent.com/assets/981813/9592409/e7e8a998-5042-11e5-9ce1-d6e0ad3768d4.png)

**Comment by chrissimpkins** [comment]
:+1:  will add this fix to the next release

**Comment by EXL** [comment]
:+1: Everything's cool, thanks!

![Hack](http://wstaw.org/m/2015/09/01/Untitled20.png)

Do not forget to close issue, and the like this issue after the release. :smile:

**Comment by chrissimpkins** [comment]
Thanks much for the issue report and assistance with testing the fix.  The bug fix is now live in the master branch as version 2.013.  Closing this issue as fixed.
