### ISSUE TITLE
[JetBrains, IntelliJ] Bold and italic rendering bug

### ISSUE THREAD

**Issue by coreequip** [chrissimpkins/Hack#50]
There is a bug under Windows 8.1 (TTFs) rendering the words _**MEDIA_TYPE**_ in bold, italic. See:

![hack-bug](https://cloud.githubusercontent.com/assets/1869598/9578092/768830a8-4fe7-11e5-850d-9fce580d7e04.png)

Besides this: Thanks for the font!

**Comment by cjstehno** [comment]
I ran into this issue as well on Windows 7 using TTF version with Java constant names (e.g. NEXT_STATE_KEY), which render in bold italic similar to the image shown above.

**Comment by chrissimpkins** [comment]
What text editors are you using?

**Comment by cjstehno** [comment]
IntelliJ

On Mon, Aug 31, 2015, 12:23 PM Chris Simpkins <notifications@github.com>
wrote:

> What text editors are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chrissimpkins/Hack/issues/50#issuecomment-136434344>.
>
-- 

Christopher J Stehno
chris.stehno@gmail.com
http://stehno.com

**Comment by chrissimpkins** [comment]
There seem to be a number of unusual rendering errors in IntelliJ (and other JetBrains editors).  See issues #45 and #42.  

I will check their issue tracker today to see if any of these issues have previously been reported.  If not, will add a new issue and see if we get any feedback.  Sorry for the troubles.

**Comment by heymjo** [comment]
Note that the Idea products (intellij, rubymine etc) are all based on the same runtime so if you manage to find a solution for one it is likely that "it will work for the others as well (tm)"

**Comment by heymjo** [comment]
having said that, intellij 15 will have "True HiDPI Support for Windows and Linux" which likely impacts font rendering : http://blog.jetbrains.com/idea/2015/06/intellij-idea-15-eap-is-open/ ... so we would need to test it on that version as well.

**Comment by Estigy** [comment]
Bug #60 is also related to this. Thanks for investigating!

**Comment by zlangbert** [comment]
I can confirm I see this bug in the latest Intellij 15 EAP

**Comment by chrissimpkins** [comment]
Received report via Twitter that a workaround on the JetBrains editors is to turn off the bold highlighting.  
![cn0sfrmwgaan_z8](https://cloud.githubusercontent.com/assets/4249591/9607443/32d4429c-5097-11e5-9ed9-be84e19c677e.png)

Clearly that may not be of interest to you if you like the bold highlighting, but I link it for any who wants to make this issue go away until it is resolved.  

Another message that there is a JetBrains bug report dealing with this:

https://youtrack.jetbrains.com/issue/IDEA-138241

in which they point the finger at Java:

https://bugs.openjdk.java.net/browse/JDK-8078382

More info when available.  I will follow these issues.

**Comment by ciscorucinski** [comment]
@chrissimpkins I am having this issue too, but I am actually wondering if this is a WINDOWS problem or a naming problem. I am only having issues with just Italics.

I am on Windows 10

I installed all 4 fonts; however, the fonts at C:\Windows\Fonts\Hack only show 2 fonts for me. Regular and Bold. There are no Italics or Bold Italics that are displayed. First clue!

So, I decided to delete the Hack fonts group. C:\Windows\Fonts and look for Hack. It shows its a group of fonts. Good. So I delete the group, and Windows tells me, "Are you sure you want to delete these 2 fonts permanently?" Only 2?? I know I installed all 4. In fact this is my 3rd time installing Hack just to make sure everything I did was right. Clue 2!

Click "Yes", and the Hack group is gone. Good. However, suprisingly, "Hack RegularOblique Italic" is now showing! However, I don't see the Bold-Italics...all that is showing is Italics. Clue 3! 

Lets go check out my IDE, but first restart the IDE to clear any cache of the fonts...this is one of the fonts that was not working correctly. TADA! My italics now works correctly!! However, my regular font and bold font don't work. I did test Bold-Italics and that has issues, too. Clue 4!

OK, so now lets delete the Italics at C:\Windows\Fonts. I find it and delete it. I get the message, "Are you sure you want to delete this font permanently?" and it displays the name "Hack-Oblique". Remember the name displayed at C:\Windows\Fonts\ is "Hack RegularOblique Italic". Maybe this is a hint at a naming issue???? Anyways, I click "Yes", and... (Clue 5)

...no surprise. "Hack BoldOblique Bold Italic" is now displayed. I could repeat everything; however, we know what will happen in my IDE. Everything won't work except for Bold-Italics.

So, lets delete "Hack BoldOblique Bold Italic", which prompts me and says the name is "Hack-BoldOblique". Click "Yes", and Hack is no longer installed on my machine

**Comment by ciscorucinski** [comment]
Summary of above: 

- I am on Windows 10.
- Installed all 4 fonts styles on my machine
- My C:\Windows\Fonts shows only shows 2 fonts; other 2 fonts are hidden!
- The fonts that are hidden are not being displayed correctly on my machine

**Comment by chrissimpkins** [comment]
@ciscorucinski incredibly helpful.  Let me look at the name tables.

**Comment by chrissimpkins** [comment]
Another issue report from @TrevorHayes: 

>I've tried installing both the ttf and otf files into my copy of Windows 7 Enterprise SP1 and while Windows will install either set of files in both cases the font family shows up with only the "regular" and "bold" fonts. If I use the font in an application, italics do not work. If I delete those two fonts then one of the oblique fonts will appear as the only font and then if I delete that the other oblique font will appear.

**Comment by Sustak** [comment]
I'm confirming the issue in Windows 10 with NetBeans IDE. The behaviour is exactly as described by @ciscorucinski above. Installing the OTF fonts instead produces exactly the same problem.

I'm joining the others: thanks for the font, it's simply great!

**Comment by ciscorucinski** [comment]
OK. ...well we have identified and confirmed an issue here, but we don't know if everyone that is having similar issues is dealing with the issue we just found.

**Comment by chrissimpkins** [comment]
Will you please give these new builds a try (v2.012)?  I've updated the name tables and adjusted the font names based upon what is currently recommended for cross-platform support.  Let's see if this addresses this issue.

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by TrevorHayes** [comment]
This has fixed the issue for me - Windows recognizes all 4 fonts as belonging to the same family at once and the font now appears correctly in the IntelliJ IDE as well.

Thanks!

**Comment by ciscorucinski** [comment]
Yes, v2.012 does fix this issue. I have not done any extensive checking, but all 4 fonts appear as the same font-family (nothing hidden), and my Android Studio IDE font settings are working as I want them.

**Comment by chrissimpkins** [comment]
@TrevorHayes @ciscorucinski :+1:

**Comment by Sustak** [comment]
The same here, Win10 recognizes all 4 fonts in the Hack family and NetBeans works with the bold italics font without the above issues.
Once again thanks, @chrissimpkins!

**Comment by chrissimpkins** [comment]
@Sustak excellent.  Glad to hear that.  Thanks for the report and the confirmations of the fix.  Will merge to master and release this fix over the weekend

**Comment by angrilove** [comment]
Fix it.Good job.

**Comment by chrissimpkins** [comment]
@angrilove Great, thank you!

**Comment by chrissimpkins** [comment]
Thanks for this issue report and for all of the testing/feedback that all of you provided.  This fix is now live in v2.013.  

@ciscorucinski your comments in this thread led to this fix and it addressed several other issues that were reported.  I'd like to add you to the contributors list if you don't mind emailing me your name.  

Closing this issue as fixed.
