### ISSUE TITLE
Add Emoji support

### ISSUE THREAD

**Issue by bb** [chrissimpkins/Hack#51]
It would be great to have Emoji support :sunglasses:.

I regularly use e.g. :pencil2:, :mag:, etc  as short labels in UI and they would also be nice in code comments. 

Maybe the glyphs from another typeface (with a compatible license) could be reused?

They should not necessarily be colored. Something like in Segoe UI Symbol would already be a great step ahead.

**Comment by AndyBean** [comment]
This might be a perfect place @bb for you to add a PR to the project.

**Comment by Widdershin** [comment]
Hi! I'm interested in getting support for emoji alongside Hack. I'm not really sure where to start though, could anyone point me in the right direction?

**Comment by chrissimpkins** [comment]
@Widdershin have a look at https://github.com/ryanoasis/nerd-fonts 

I believe that they may have patched Hack with emoji.  Definitely includes Font Awesome glyphs as I recall.
