### ISSUE TITLE
21 glyphs missing to support MES-1

### ISSUE THREAD

**Issue by schierlm** [chrissimpkins/Hack#52]
The following 21 glyphs are missing (some of them already covered by #21):

      Ĉĉ Ĝĝ Ĥĥ Ĳĳ Ĵĵ ĸ Ŀŀ ŉ Ŝŝ Ţţ Ŭŭ ♪

MES-1 is a character set standardized by the European Union that covers all characters that usually appear in European people's names (if they are written using the Latin alphabet), i. e. on ID cards, and therefore coverage is mandated in some EU countries for software used in the European public sector (I do not know if it makes sense to apply such a standard to a source code font, but you know bureaucracy...).

(there is also MES-2, which also covers some more Latin (letters usually not appearing in names), and some Greek and Cyrillic, and is voluntary to cover, but for that you would need to add 365 more glyphs - including those that are missing for MES-1)

----

For reference, MES-1 is defined as

    |ASCII uppercase letters        |0041-5A(26)|ABCDEFGHIJKLMNOPQRSTUVWXYZ|-----|
    |ASCII lowercase letters        |0061-7A(26)|abcdefghijklmnopqrstuvwxyz|-----|
    |ASCII decimal digits           |0030-39(10)|0123456789|---------------------|
    |ASCII special characters       |0020-2F(16)| !"#$%&'()*+,-./|---------------|
    |'->                |003A-40,5B-60,7B-7E(17)|:;<=>?@[\]^_`{|}~|--------------|
    
    |Latin-1 symbols                |00A0-BF(32)| ¡¢£¤¥¦§¨©ª«¬°±²³´µ¶·¸¹º»¼½¾¿|
    |Latin-1 uppercase letters      |00C0-DF(32)|ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞß|
    |Latin-1 lowercase letters      |00E0-FF(32)|àáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ|
    |Latin extended                 |0100-13(20)|ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒē|-----------|
    |'->                            |0116-2B(22)|ĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪī|---------|
    |'->                            |012E-4D(32)|ĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌō|
    |'->                            |0150-67(24)|ŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧ|-------|
    |'->                            |0168-7E(23)|ŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽž|--------|
    
    |Accents                        |02C7-C7(01)|ˇ|------------------------------|
    |'->                      |02D8-DB,DD-DD(05)|˘˙˚˛˝|--------------------------|
    |Typographic special characters |2015-15(01)|―|------------------------------|
    |'->                      |2018-19,1C-1D(04)|‘’“”|---------------------------|
    |Euro symbol                    |20AC-AC(01)|€|------------------------------|
    |Trademark symbol               |2122-22(01)|™|------------------------------|
    |Ohm symbol                     |2126-26(01)|Ω|------------------------------|
    |Vulgar fractions               |215B-5E(04)|⅛⅜⅝⅞|---------------------------|
    |Arrow symbols                  |2190-93(04)|←↑→↓|---------------------------|
    |Musical note symbol            |266A-6A(01)|♪|------------------------------|

And MES-2 also covers (the ones marked with `(*)` are not covered by Microsoft's "Windows Glyph List")

    |Latin extended                 |0114-15(02)|Ĕĕ|-----------------------------|
    |'->                      |012C-2D,4E-4F(04)|ĬĭŎŏ|---------------------------|
    |'->                      |0192-92,FA-FF(07)|ƒǺǻǼǽǾǿ|------------------------|
    |'->                      |1E80-85,F2-F3(08)|ẀẁẂẃẄẅỲỳ|-----------------------|
    |'->                        (*) |01DE-EF(18)|ǞǟǠǡǢǣǤǥǦǧǨǩǪǫǬǭǮǯ|-------------|
    |'->                  (*) |0218-1B,1E-1F(06)|ȘșȚțȞȟ|-------------------------|
    |'->      (*) |1E02-03,0A-0B,1E-1F,40-41(08)|ḂḃḊḋḞḟṀṁ|-----------------------|
    |'->            (*) |1E56-57,60-61,6A-6B(06)|ṖṗṠṡṪṫ|-------------------------|
    |More exotic Latin letters      |017F-7F(01)|ſ|------------------------------|
    |'->                  (*) |018F-8F,B7-B7(02)|ƏƷ|-----------------------------|
    |'->            (*) |0259-59,7C-7C,92-92(03)|əɼʒ|----------------------------|
    |'->                        (*) |1E9B-9B(01)|ẛ|------------------------------|
    |Latin Modifier letters         |02C6-C6(01)|ˆ|------------------------------|
    |'->                      |02C9-C9,DC-DC(02)|ˉ˜|-----------------------------|
    |'->                  (*) |02BB-BD,EE-EE(04)|ʻʼʽˮ|---------------------------|
    
    |Greek uppercase letters        |0391-A1(17)|ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡ|--------------|
    |'->                            |03A3-A9(07)|ΣΤΥΦΧΨΩ|------------------------|
    |Greek lowercase letters        |03B1-C9(25)|αβγδεζηθικλμνξοπρςστυφχψω|------|
    |Greek extended                 |0384-8A(07)|΄΅Ά·ΈΉΊ|------------------------|
    |'->                      |038C-8C,8E-90(04)|ΌΎΏΐ|---------------------------|
    |'->                      |03AA-B0,CA-CE(12)|ΪΫάέήίΰϊϋόύώ|-------------------|
    |'->            (*) |0374-75,7A-7A,7E-7E(04)|ʹ͵ͺ;|---------------------------|
    |'->                  (*) |03D7-D7,DA-E1(09)|ϗϚϛϜϝϞϟϠϡ|----------------------|
    |'->                  (*) |1F00-15,18-1D(28)|ἀἁἂἃἄἅἆἇἈἉἊἋἌἍἎἏἐἑἒἓἔἕἘἙἚἛἜἝ|---|
    |'->                        (*) |1F20-3F(32)|ἠἡἢἣἤἥἦἧἨἩἪἫἬἭἮἯἰἱἲἳἴἵἶἷἸἹἺἻἼἽἾἿ|
    |'->            (*) |1F40-45,48-4D,50-57(20)|ὀὁὂὃὄὅὈὉὊὋὌὍὐὑὒὓὔὕὖὗ|-----------|
    |'->            (*) |1F59-59,5B-5B,5D-5D(03)|ὙὛὝ|----------------------------|
    |'->                        (*) |1F5F-7D(31)|ὟὠὡὢὣὤὥὦὧὨὩὪὫὬὭὮὯὰάὲέὴήὶίὸόὺύὼώ||
    |'->                        (*) |1F80-9F(32)|ᾀᾁᾂᾃᾄᾅᾆᾇᾈᾉᾊᾋᾌᾍᾎᾏᾐᾑᾒᾓᾔᾕᾖᾗᾘᾙᾚᾛᾜᾝᾞᾟ|
    |'->                        (*) |1FA0-B4(21)|ᾠᾡᾢᾣᾤᾥᾦᾧᾨᾩᾪᾫᾬᾭᾮᾯᾰᾱᾲᾳᾴ|----------|
    |'->                  (*) |1FB6-C4,C6-D3(29)|ᾶᾷᾸᾹᾺΆᾼ᾽ι᾿῀῁ῂῃῄῆῇῈΈῊΉῌ῍῎῏ῐῑῒΐ|--|
    |'->                  (*) |1FD6-DB,DD-EF(25)|ῖῗῘῙῚΊ῝῞῟ῠῡῢΰῤῥῦῧῨῩῪΎῬ῭΅`|------|
    |'->                  (*) |1FF2-F4,F6-FE(12)|ῲῳῴῶῷῸΌῺΏῼ´῾|-------------------|
    
    |Cyrillic                       |0400-1F(32)|ЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОП|
    |'->                            |0420-3F(32)|РСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмноп|
    |'->                            |0440-5F(32)|рстуфхцчшщъыьэюяѐёђѓєѕіїјљњћќѝўџ|
    |'->                            |0490-91(02)|Ґґ|-----------------------------|
    |'->                        (*) |0492-B1(32)|ҒғҔҕҖҗҘҙҚқҜҝҞҟҠҡҢңҤҥҦҧҨҩҪҫҬҭҮүҰұ|
    |'->                  (*) |04B2-C4,C7-C8(21)|ҲҳҴҵҶҷҸҹҺһҼҽҾҿӀӁӂӃӄӇӈ|----------|
    |'->                  (*) |04CB-CC,D0-EB(30)|ӋӌӐӑӒӓӔӕӖӗӘәӚӛӜӝӞӟӠӡӢӣӤӥӦӧӨөӪӫ|-|
    |'->                  (*) |04EE-F5,F8-F9(10)|ӮӯӰӱӲӳӴӵӸӹ|---------------------|
    
    |Typographic symbols            |2013-14(02)|–—|-----------------------------|
    |'->          |2017-17,1A-1B,1E-1E,20-22(07)|‗‚‛„†‡•|------------------------|
    |'->          |2026-26,30-30,32-33,39-3A(06)|…‰′″‹›|-------------------------|
    |'->          |203C-3C,3E-3E,44-44,7F-7F(04)|‼‾⁄ⁿ|---------------------------|
    |'->                  (*) |204A-4A,82-82(02)|⁊₂|-----------------------------|
    |Currency symbols               |20A3-A4(02)|₣₤|-----------------------------|
    |'->                            |20A7-A7(01)|₧|------------------------------|
    |'->                        (*) |20AF-AF(01)|₯|------------------------------|
    |Business symbols               |2105-05(01)|℅|------------------------------|
    |'->                            |2116-16(01)|№|------------------------------|
    |Arrow symbols                  |2194-95(02)|↔↕|-----------------------------|
    |'->                            |21A8-A8(01)|↨|------------------------------|
    |Mathematical symbols           |2202-02(01)|∂|------------------------------|
    |'->          |2206-06,0F-0F,11-12,19-1A(06)|∆∏∑−∙√|-------------------------|
    |'->                |221E-1F,29-29,2B-2B(04)|∞∟∩∫|---------------------------|
    |'->                |2248-48,60-61,64-65(05)|≈≠≡≤≥|--------------------------|
    |'->                |2302-02,10-10,20-21(04)|⌂⌐⌠⌡|---------------------------|
    |'->            (*) |2200-00,03-03,08-09(04)|∀∃∈∉|---------------------------|
    |'->            (*) |2227-28,2A-2A,59-59(04)|∧∨∪≙|---------------------------|
    |'->            (*) |2282-83,95-95,97-97(04)|⊂⊃⊕⊗|---------------------------|
    |'->                        (*) |2329-2A(02)|〈〉|-----------------------------|
    |Box drawing characters         |2500-00(01)|─|------------------------------|
    |'->                |2502-02,0C-0C,10-10(03)|│┌┐|----------------------------|
    |'->                |2514-14,18-18,1C-1C(03)|└┘├|----------------------------|
    |'->          |2524-24,2C-2C,34-34,3C-3C(04)|┤┬┴┼|---------------------------|
    |'->                            |2550-6C(29)|═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬|--|
    |Block graphic characters       |2580-80(01)|▀|------------------------------|
    |'->                |2584-84,88-88,8C-8C(03)|▄█▌|----------------------------|
    |'->                            |2590-93(04)|▐░▒▓|---------------------------|
    |Shapes                         |25A0-A0(01)|■|------------------------------|
    |'->                            |25AC-AC(01)|▬|------------------------------|
    |'->          |25B2-B2,BA-BA,BC-BC,C4-C4(04)|▲►▼◄|---------------------------|
    |'->                      |25CA-CB,D8-D9(04)|◊○◘◙|---------------------------|
    |Miscellaneous symbols          |263A-3C(03)|☺☻☼|----------------------------|
    |'->                      |2640-40,42-42(02)|♀♂|-----------------------------|
    |'->                |2660-60,63-63,65-66(04)|♠♣♥♦|---------------------------|
    |'->                            |266B-6B(01)|♫|------------------------------|
    |Ligatures                      |FB01-02(02)|ﬁﬂ|-----------------------------|
    |Replacement character (*)      |FFFD-FD(01)|�|------------------------------|

**Comment by chrissimpkins** [comment]
I think that it is a great idea to support the MES-1 set.  Glancing through the MES-2 set, I can comment on the extended Greek character set.  This is something that @corelon and I discussed before this release and the feedback that I received was that these characters are not in common use in source code, rather they are primarily used in Greek literature.   I must admit to complete lack of knowledge in this area.

I'm definitely interested in hearing more from you and others about any of these characters that are felt to be important in the context of source code (very broadly defined) or any other application where this typeface might serve a purpose.

Thanks much for this feedback.  This is extremely helpful and I hope it stimulates further discussion about the necessary character set coverage.

**Comment by jublo** [comment]
Suggestion for `U+0132` `Ĳ`, as used in Dutch (see small sample below large letters):

![](https://cloud.githubusercontent.com/assets/6348321/10268335/75deecd0-6ab5-11e5-8d5f-d98c240d7447.png)

**Comment by jublo** [comment]
Suggestion for `U+0133` `ĳ`:

![](https://cloud.githubusercontent.com/assets/6348321/10268414/24969afa-6ab8-11e5-810a-192262425474.png)

**Comment by chrissimpkins** [comment]
These turned out great @jublo.  Mind submitting these in a PR?  We will run them through some centering testing with a number of triplet glyph combinations and incorporate them in the set.

**Comment by jublo** [comment]
Suggesting to copy `U+03BA` kappa to `U+0138` kra.

**Comment by jublo** [comment]
@schierlm What about `ŉ`?  Wikipedia says: 
> The codepoint is currently deprecated,[1] and the Unicode standard recommends that a sequence of an apostrophe followed by n be used instead,[2] as the use of deprecated characters such as ŉ is “strongly discouraged”.[3]
But it’s part of MES-1…

**Comment by schierlm** [comment]
I for myself have not seen anybody's name contain ŉ (but on the other hand, not ♪ either), so I probably won't miss that glyph (ĳ and the Esperanto ones are surely more important).

Probably those standardizing those character sets did not spend too much time discussing about every single glyph... (or those characters were supported in some legacy charset that was used before and nobody took the time to check if any name used it actually..)

So probably depends on how hard it is to add those... :)

**Comment by chrissimpkins** [comment]
How does the character set coverage influence this statement that you made?

> coverage is mandated in some EU countries for software used in the European public sector

**Comment by jublo** [comment]
Suggesting these:

![](https://cloud.githubusercontent.com/assets/6348321/10268878/4f393b42-6ac6-11e5-901b-28e6d64d281a.png)

![](https://cloud.githubusercontent.com/assets/6348321/10268881/59a8c944-6ac6-11e5-998c-99e4c50efc0d.png)

**Comment by schierlm** [comment]
@chrissimpkins  sorry I don't understand what exactly you are asking here...

bureaucracy says software used needs to cover all of MES-1. So, depending on how well you can bend the rules (e.g. if you can plausibly tell you are only using it for code, but not for scenarios that may show people's names, like email headers...), you may not be able to use the font in those environments if it does not cover MES-1. On the other hand, probably you cannot use it even when it covers MES-1 (because bureaucracy is bureaucracy and they may find reasons to ban whatever they want).

The only point I'm trying to make is that you want to add characters, probably it is a good idea to add those missing from MES-1 to take the wind out of the sails of those who like to argue/nitpick with MES-1.

**Comment by chrissimpkins** [comment]
@schierlm Michael, can you point me to information about these restrictions/rules and any information that you have about where (countries) they apply?  I am wondering whether this has the potential to limit embedding of the fonts (e.g. in software, TeX/pdf documents, presentations, etc) in locations where such rules are in place.   Your mention is the first that made me aware of this situation and I want to make sure that we are not unnecessarily limiting use of the fonts.  The musical note is not a high priority glyph for the set; however, if it means that we do not meet these standards and the fonts cannot be used in certain situations, then it takes much higher priority.

**Comment by schierlm** [comment]
Sorry if I have to disappoint you, but I'm not myself working in the public sector here and know most of it from another person who in 2009 filed a feature request against *my* open source project (which was a Windows utility to show metadata about truetype fonts, and he wanted it to analyze MES-1/2/3 coverage; I got the request by e-mail so I won't quote it here).

So I cannot really say which countries it applies to exactly; from the rationale of Johan van Wingen’s Negative ballot in http://www.evertype.com/standards/iso10646/pdf/cwa13873.pdf, I would assume The Netherlands are not in that list.

As far as I understand it [as already said, take this with a grain of salt as I'm not personally affected], the rationale for requiring MES-1 in fonts is to avoid situations where unsuspecting/non-technical users see replacement characters in "everyday life", e. g. when communicating via e-mail or private messages suddenly one of the sender name's characters (e. g. the ĳ in a Dutch person's name) is replaced by a �, which may cause some confusion when talking to that person later on the phone, for example. Embedding fonts should not fall in that category as the text in a presentation or PDF is already fixed and should not suddenly get more characters (although I have to admit I don't know whether embedding fonts may affect display of texts that users enter in PDF form fields), so if you use a font for a presentation that does not cover your characters, you will hopefully notice it yourself :-) . Also, unlike installing software or fonts, downloading and viewing PDFs does not require  Administrator permissions on Windows, and is therefore harder to regulate :-)

**Comment by chrissimpkins** [comment]
@schierlm Thank you! This is helpful. We will be able to support the MES-1 set.  We will handle further expansion for this concern as the need arises.  I really appreciate that you pointed this issue out.

**Comment by chrissimpkins** [comment]
@jublo do you have a set of source with the changes that you posted above?  We will plan to include all of the MES-1 glyphs in the set.  It looks like many of these are covered with the Esperanto set changes that we are working on in #10

**Comment by jublo** [comment]
> that we are working on in #10 

In #21, you meant.

**Comment by chrissimpkins** [comment]
correct, I updated it. thanks

**Comment by jublo** [comment]
Investigating which `MES-1` characters are missing as of 2.016, will follow-up soon.

**Comment by chrissimpkins** [comment]
The missing characters from the MES-1 character set are now included in the source and will be in the v2.017 builds.  Should be out in the next couple of days.

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release.  Thanks to all for the contributions and testing of these new glyphs.  We now have full MES-1 character set support.
