### ISSUE TITLE
[OS X] Renders incorrectly during Font Book installation and Sublime Text editor; MS Word is OK

### ISSUE THREAD

**Issue by cwotta** [chrissimpkins/Hack#54]
Both OTF and TTF versions seem to render correctly in:
- MS Word
- Font Book, once installed

...But do not work correctly in:
- Sublime Text 3 editor - it renders as some type of proportional font (I think the OS X Mavericks default font, since Sublime Text fails to render Hack)
- Font Book, during installation - it renders as seemingly-random glyphs

I saw the previous issue about rendering in JetBrains editors, but Sublime Text isn't one of them.

![screen shot 2015-08-31 at 12 42 33 pm](https://cloud.githubusercontent.com/assets/14058414/9584230/09dec614-4fde-11e5-8f60-b8222cdc7562.png)

**Comment by QuinnyPig** [comment]
@cwotta Just saw that on 10.9; what version of OS X are you using?

**Comment by gravyboat** [comment]
I'm also encountering the issue for both OTF and TTF installs where the font is incorrectly displayed during install on OS X 10.9.5.

**Comment by cwotta** [comment]
Yep, OS X 10.9.5!

**Comment by qbunt** [comment]
Also seeing this on OS X 10.9.5

**Comment by chrissimpkins** [comment]
Those are the Armenian glyphs that are displayed.  They are included in the set.  

**1.** Do you mind right clicking on the Hack font group in FontBook and choosing `Validate Font`?

If you don't get all greens let me know

<img width="631" alt="font-validate" src="https://cloud.githubusercontent.com/assets/4249591/9588068/0fd0d8bc-4ff4-11e5-8d27-d113ecc96143.png">

**2.** Have any of you customized your keyboard character mapping?

**Comment by qbunt** [comment]
I'm getting all greens inside FontBook, no customized character mapping for me.

**Comment by gravyboat** [comment]
Also getting all greens. No customized character mappings.

**Comment by cwotta** [comment]
Same as above: all greens, no customized character mappings!

**Comment by chrissimpkins** [comment]
Well then we have the default solution. You are all Armenian.  Issue closed.

**Comment by chrissimpkins** [comment]
;) 

Sorry all, I really have no idea what is going on if the files passed validation.  Let me check into any reports of similar issues on OS X for other typefaces.

Can you use it in any non-ST editors aside from Word?

**Comment by qbunt** [comment]
I just gave it a shot in WebStorm, Android Studio and Atom. No luck in WebStorm but Atom and Android Studio appear to work OK. Doesn't even get listed in WebStorm.

**Comment by cwotta** [comment]
Haha good solution!

It works correctly in TextWrangler and TextMate (and TextEdit, but I'm not sure that one's particularly helpful).

**Comment by chrissimpkins** [comment]
Perhaps a font caching issue on OS X? Maybe try a reboot if you did a number of install + remove + install sequences with the same font files.

**Comment by gravyboat** [comment]
Font seems to work fine in iTerm once installed. I did not perform any additional install/uninstall actions with the font file (otf or tff), this was on the first install. Font caching could definitely be an issue, I haven't rebooted in a few days.

**Comment by QuinnyPig** [comment]
Seems surprising to me that it'd be this prevalent were this merely a caching issue...

**Comment by bjankord** [comment]
Seeing the same issue.

**Comment by jhuckaby** [comment]
Seeing the same issue in OS X 10.8 Mountain Lion as well:
![screenshot 2015-09-01 11 01 09](https://cloud.githubusercontent.com/assets/700765/9612154/c508be26-5098-11e5-91aa-126742dee1ac.png)

**Comment by qbunt** [comment]
What's odd is if you install it, it appears to display/validates/functions fine, it even previews properly in QuickLook. 
<img width="415" alt="screen shot 2015-09-01 at 12 20 37 pm" src="https://cloud.githubusercontent.com/assets/187095/9614015/ee79f0a8-50a3-11e5-8bf4-01d6a06d4e72.png">

<img width="689" alt="screenshot 2015-09-01 12 20 26" src="https://cloud.githubusercontent.com/assets/187095/9614019/f3d0452a-50a3-11e5-9f2c-93ea1981c754.png">

I've also purged my font cache via ```sudo atsutil databases -remove``` but when you open either the TTF or the OTF, it previews in that window in Font Book. Not sure there's something wrong with the font or the OS, it's odd that it doesn't appear in Yosemite and up.

**Comment by chrissimpkins** [comment]
Will you please give these new builds a try (v2.012)?  I've updated the name tables and adjusted the font names based upon what is currently recommended for cross-platform support.  Let's see if this addresses this issue.  

**Download Links**
[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Regular.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Bold.ttf?raw=true)
[Italic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-Italic.ttf?raw=true)
[BoldItalic](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_012/Hack-BoldItalic.ttf?raw=true)

**Comment by jhuckaby** [comment]
I'm sorry to report this, but the new fonts you provided are still showing up as cryptic glyphs, when opened in Font Book (before and after installing).  I tested in OS X 10.8.5 and OS X 10.9.5.  Screenshots:

<img width="725" alt="screenshot 2015-09-05 09 44 25" src="https://cloud.githubusercontent.com/assets/700765/9700311/3cc42aaa-53b3-11e5-83f2-33ec771b3a1e.png">

<img width="764" alt="screenshot 2015-09-05 09 46 40" src="https://cloud.githubusercontent.com/assets/700765/9700312/41ac8292-53b3-11e5-9aac-b97a29a1cf94.png">

**Comment by chrissimpkins** [comment]
OK thanks for letting me know.  It was a long shot for this issue but figured we should give it a shot.  Will continue working on it.

**Comment by chrissimpkins** [comment]
Nothing that I did *should* have changed these behaviors, but there is a new test build available (v2.014) if you'd like to give this a try to see if we happen to change something that made this go away.

Available in #111

**Comment by jhuckaby** [comment]
Alas, same issue with OS X 10.8.5 and OS X 10.9.5 using Hack 2.014.  Screenies:
![screenshot 2015-09-21 09 27 15](https://cloud.githubusercontent.com/assets/700765/9997907/8456af2c-6043-11e5-8214-f42f58ad622a.png)
![screenshot 2015-09-21 09 29 28](https://cloud.githubusercontent.com/assets/700765/9997910/8c77961c-6043-11e5-9950-5e4e5827cade.png)

**Comment by chrissimpkins** [comment]
@jhuckaby Ok, thanks.  There wasn't a change that *should* have led to a solution here but I wanted to confirm that there was not a problem in the metrics that led to display issues there.  It did install and display ok on your OS X version despite the FontBook issues?

**Comment by jhuckaby** [comment]
No problem, happy to help!  Yup, the font installs just fine, and looks great after installing.  Apparently this bug only affects the FontBook preview window before installing.

Screenshot after install:
![screenshot 2015-09-21 09 36 44](https://cloud.githubusercontent.com/assets/700765/9998044/44ab0278-6044-11e5-8df8-286776bb9e48.png)

**Comment by chrissimpkins** [comment]
OK, thanks.  That is good to hear.  If anyone has issues with use of the font after they encounter these Font Book install issues, please let me know.

**Comment by qbunt** [comment]
@chrissimpkins just tested again on 10.9.5. The Quick Look previews and installs just fine as @jhuckaby mentions, it's just the pre-install screen in Font Book the face appears in odd characters. On later OS X versions (Yosemite for instance) it renders OK in the pre-install screen.

My guess (wild-ass guess) is that this could have nothing to do with your font, and everything to do with an edge case inside the 10.9 releases.

**Comment by chrissimpkins** [comment]
@qbunt Yeah, I am developing this on 10.10.5 and have never noticed this over numerous install / uninstall cycles.  I looked for some information on changes in Font Book with these new releases, but there aren't many details in the Apple documentation.  I suspect that it has something to do with the Unicode range support settings in the font builds, but I don't know how to modify it so that you see the appropriate character set during the install.

Incidentally, are all of you using older OS X releases or are these testing platforms?

**Comment by jhuckaby** [comment]
I run 10.10.5 on my main machine.  I keep 10.8.5 and 10.9.5 around for testing purposes :)

**Comment by cwotta** [comment]
10.9.5 is my main (only, at this point...) machine.  Don't go crazy trying to fix this for my sake; I'm sure I'll be off of 10.9.5 at some point!  Thanks for your work so far!

**Comment by chrissimpkins** [comment]
No worries!  Just trying to understand the scope of this issue.  I can't find data on what proportion of users are still on older versions of OS X.

**Comment by cwotta** [comment]
Not sure how accurate this is, but it might be close enough to say "Yeah, not going to waste my time on 10.9"  ;)

https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

**Comment by jhuckaby** [comment]
I work for a digital ad company (I know, sorry), and we analyze all incoming browser user agents which contain the OS X version.  Here is some data pulled our view logs yesterday (Sept 20, 2015):

OS Version | Number of Hits | Percentage
------------ | ------------- | ----------------
Mac OS X 10.10	| 595,721	| 6.53%
Mac OS X 10.9	| 210,660	| 2.31%
Mac OS X 10.6	| 102,143	| 1.12%
Mac OS X 10.7	| 79,325	| 0.87%
Mac OS X 10.8	| 59,485	| 0.65%
Mac OS X 10.5	| 10,936	| 0.12%
Mac OS X 10.11 (Beta)	| 5,593	| 0.061%
Mac OS X 10.4	| 896	 | 0.0098%

**Comment by chrissimpkins** [comment]
@cwotta & @jhuckaby These data actually surprise me.  I would not have expected > 50% of OS X users to still be running an older version of the OS nearly one year after release given that the system requirements have not changed since 10.8.x (and it is free!).  Interesting.

**Comment by jhuckaby** [comment]
Yeah, that is a bit surprising.  I think it's primarily because Mavericks is so stable now, and that Yosemite didn't really add anything Earth-shattering.  All my friends at work are still running Mavericks, and when asked why they didn't upgrade, the most common answer was "*Why?  What I have works just fine.*".  Also, no one could list a single feature added in Yosemite either (besides the new flat-shaded look).  Funny :)

**Comment by chrissimpkins** [comment]
> "Why upgrade? What I have works just fine." 

Seems like reason enough to me.

**Comment by qbunt** [comment]
Yeah I've gotta admit, I'm running 10.9.5 on my work machine not by choice, but by dependency. Minor iOS development annoyances aside, there's not a lot of motivation to upgrade, even for free. Thanks for looking into this @chrissimpkins, digging your work.

**Comment by jhuckaby** [comment]
I second that -- I'm really digging Hack.  Thanks a bunch @chrissimpkins :)

**Comment by chrissimpkins** [comment]
It's been a lot of fun and the developer response has been great.  All of these new changes are the result of issue reports.  Will be interesting to see where it leads.  I have a large number of things to address yet and lots of new ideas.   Keep an eye on the changelog if you continue to use it.

**Comment by Smolations** [comment]
Just for reference, The font previews, installs, and works/renders just fine (for me) in OS X 10.11 El Capitan and Sublime Text 3 (build 3083). :+1:

**Comment by chrissimpkins** [comment]
@Smolations thank you!!

**Comment by alanmcginnis** [comment]
Also works fine for me, same setup as @Smolations. **Thanks for this font!**

**Comment by chrissimpkins** [comment]
@alanmcginnis great!
