### ISSUE TITLE
[Linux, hinting] Rendering in Fedora 22 isn't too good

### ISSUE THREAD

**Issue by bioothod** [chrissimpkins/Hack#55]
Monospace vs Hack

![vim-monospace-hack-fonts](https://cloud.githubusercontent.com/assets/1847575/9589269/e1347044-5035-11e5-99de-c8fff561a51c.png)

See 'r', 'P' 'S' and '=' on the right side

**Comment by chrissimpkins** [comment]
Yeah, I agree that looks terrible.  What font size is this and does it look better at other sizes? Mind showing me another text editor screenshot on the same platform with the same font size?

**Comment by bioothod** [comment]
That's 10 size, 11 looks good.
I've found that it is so far only vim's problem, when setting this font in a terminal, there are no hinting artifacts.

But if I set full hinting in Fedora and specify 10 or less font size artifacts show up again. Setting hinting to 
So, it is 10 and less size and medium-to-full hinting.
Attached terminal screenshots (no and full hinting)

![size-10-hinting-none](https://cloud.githubusercontent.com/assets/1847575/9593998/6c7a7f0e-505e-11e5-860f-0fce8a277a12.png)
![size-10-hinting-full](https://cloud.githubusercontent.com/assets/1847575/9593997/6c78ee82-505e-11e5-828f-49a0afa2e1e2.png)

**Comment by chrissimpkins** [comment]
I reached out to Werner Lemberg and Dave Crossland today (ttfautohint) to see if they would be willing to provide some expertise.  I am using ttfautohint on the TrueType files and I think that we need a bit of optimization.  Let me see if hear back from either of them.  If not, we may just do a shotgun approach with a bit of trial and error.  Eventually, it will be ideal to have a manually instructed set of glyphs. I'd like to reach a bit more mature stage with the project before I delve into that because it is going to take some time.  If we happen across a type engineer who would like to contribute to this project, I am all for doing this sooner rather than later.

**Comment by bioothod** [comment]
Let me know if there will be newer builds, I will give it a try

**Comment by chrissimpkins** [comment]
Thank you very much.  That will be extremely helpful.   I will let you know.

**Comment by lemzwerg** [comment]
Whatever I try, I can't reproduce the ugliness with ftview (from the current git repository), using the regular and bold shapes from the repository's `build/ttf` directory (downloaded just now).  All possible hinting forms look OK, this is, native bytecode hinting, and both strong and light auto-hinting.  Especially with the 'r' and 'S' glyphs, I don't get any artifacts.  I've also tried some older version of ftview, and it looks always OK.

@bioothod: Please use the ftview demo program to check whether it shows the problems on your machine.

**Comment by chrissimpkins** [comment]
@lemzwerg Thank you Werner!

**Comment by davelab6** [comment]
I started a "designer's manual" project so please file an issue there explaining the user process you used so far :) 

https://github.com/davelab6/ttfautohint.com/issues

**Comment by chrissimpkins** [comment]
@davelab6 :+1:  Extremely helpful.  Thank you very much.  I'll submit it today

**Comment by bioothod** [comment]
Attached 2 screenshots with hinting on/off
Turning hinting on brings in artifacts
![hinting-on](https://cloud.githubusercontent.com/assets/1847575/9612446/6b7a17f0-50ee-11e5-9d33-bff922180fbd.png)
![hinting-off](https://cloud.githubusercontent.com/assets/1847575/9612447/6b7d765c-50ee-11e5-989d-055b5d72116e.png)

**Comment by lemzwerg** [comment]
Interesting.  Here is what I get.  This is FreeType from current git, compiled on a 32bit GNU/Linux box.  Note that version 2.5.3 returns a similar result.  'Hack-Regular.ttf' identifies itself as version 2.010; having 4fea277591543c1fd64a9cf06ec5803a as the md5sum.

So: What FreeType version do you have?  And please compare the 'ftoption.h' file installed on your Fedora box with the vanilla version from a FreeType source tarball.

![hack](https://cloud.githubusercontent.com/assets/1630245/9618082/4548d998-5104-11e5-99e9-6a695ee06f65.png)

**Comment by bioothod** [comment]
It is freetype 2.5.5 here.

Hack-Regular.ttf ms5sum is 4f24ab365554d35214a76add8d4c575f, downloaded from `prebuild/Hack-Regular.ttf`, it is the same file right now

Here is the difference between vanilla and fedora's `ftoption.h`:
```
--- /tmp/freetype-2.5.5/include/config/ftoption.h	2014-11-20 00:38:59.000000000 +0300
+++ /usr/include/freetype2/config/ftoption.h	2015-02-22 20:32:08.000000000 +0300
@@ -92,7 +92,7 @@
   /* This is done to allow FreeType clients to run unmodified, forcing     */
   /* them to display normal gray-level anti-aliased glyphs.                */
   /*                                                                       */
-/* #define FT_CONFIG_OPTION_SUBPIXEL_RENDERING */
+#define FT_CONFIG_OPTION_SUBPIXEL_RENDERING
 
 
   /*************************************************************************/
@@ -604,7 +604,7 @@
   /*   This option requires TT_CONFIG_OPTION_BYTECODE_INTERPRETER to be    */
   /*   defined.                                                            */
   /*                                                                       */
-/* #define TT_CONFIG_OPTION_SUBPIXEL_HINTING */
+#define TT_CONFIG_OPTION_SUBPIXEL_HINTING
 
 
   /*************************************************************************/
```

**Comment by lemzwerg** [comment]
Thanks.  I've just recompiled 2.5.5, with your settings, and I'm still not able to reproduce the issue.
Can you download the latest FreeType version together with the demo programs and compile it by yourself?

**Comment by chrissimpkins** [comment]
@bioothod This issue hasn't seen activity in a couple of weeks. Can you please provide an update on where things stand and whether this needs to remain open?  Thanks

**Comment by bioothod** [comment]
I will try to recompile the latest freetype as soon as time permits and reopen this issue if problem persists

**Comment by chrissimpkins** [comment]
No rush.  Feel free to reopen if it is still an issue in the version that you use when you get to it.
