### ISSUE TITLE
Issues with spacing in RStudio

### ISSUE THREAD

**Issue by noamross** [chrissimpkins/Hack#57]
I'm using Hack font in [RStudio](rstudio.com), and there are some odd spacing issues.  It's hard to describe so I'm showing it in this GIF.  See how the cursor doesn't match up with where the last
character is, as if the width information is incorrect:

![hack](https://cloud.githubusercontent.com/assets/571752/9594276/fa6bf906-500d-11e5-9ab5-cc920979f8c6.gif)

I'm using the OTF version of the font on OSX 10.10.4, and RStudio 0.99.660. It works fine in iTerm and Sublime Text.

Also, no dots show up for non-printing space characters.  Is this because of a missing glyph?

Pinging @kevinushey from RStudio in case he knows why this happens.

**Comment by chrissimpkins** [comment]
> Also, no dots show up for non-printing space characters. Is this because of a missing glyph?

Try these new test builds for the missing middle dot glyph issue.  The middle dot glyph was present but didn't actually have a glyph in it and the spacing was wider than for the rest of the set.  It's possible that this may be causing both issues depending upon how the cursor is being aligned.

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by kevinushey** [comment]
We use the Ace editor in RStudio, which calculates the cursor position assuming a monospaced font where each character is of identical width. I'm guessing that @chrissimpkins's conjecture is correct (a missing middle dot glyph => an incorrectly-sized character is rendered instead).

**Comment by chrissimpkins** [comment]
Thanks @kevinushey

**Comment by chrissimpkins** [comment]
The new build is hinted and can be used normally.  The changes will be included in the next release.

**Comment by noamross** [comment]
Works great, thanks!

![hack2](https://cloud.githubusercontent.com/assets/571752/9596197/2abcd004-5026-11e5-8c76-6d3cd0c25542.gif)

**Comment by chrissimpkins** [comment]
Good to hear.
