### ISSUE TITLE
Dots of the german umlauts not at the same high.

### ISSUE THREAD

**Issue by ceving** [chrissimpkins/Hack#61]
![2015-09-01 09_46_43-emacs sn-e1254vw7](https://cloud.githubusercontent.com/assets/795748/9598801/cdf185ea-508e-11e5-87e6-fec50564d132.png)

The dots of the 'ü' are lower than those of the 'ä' and 'ö'.

**Comment by alerque** [comment]
I use umlated o's and u's in Turkish, and I have  not observed t his problem. In fact they seem to come out to the same height for me (screenshot of Termite):

![selection_047](https://cloud.githubusercontent.com/assets/173595/9602265/b2250258-50af-11e5-93d7-89ffdfa7561c.png)

**Comment by chrissimpkins** [comment]
@ceving are you using the otf or ttf files?

**Comment by ceving** [comment]
@chrissimpkins I have used the TTF files on Windows 7 and Emacs 24.5.1 (i686-pc-mingw32).

**Comment by ceving** [comment]
I tried the TTF font on Linux in the XFCE4 terminal and got the same effect.
![xfce4-term-with-hack](https://cloud.githubusercontent.com/assets/795748/9905924/017bb372-5c88-11e5-8a57-0eb065d6c63e.png)

**Comment by chrissimpkins** [comment]
Looks like this is my fault.  These are just a hair lower in the source and I suspect that they are snapping down by a pixel in some editors/some renderers.  I will adjust this and try to add it in the next release which I hope to have out later this week.

<img width="1016" alt="umlauts" src="https://cloud.githubusercontent.com/assets/4249591/9906335/b4358e2e-5c57-11e5-9415-7b308c0f3bb3.png">

Can you let me know what text sizes you are seeing this at?  I will confirm that they are properly aligned after hinting.

**Comment by ceving** [comment]
@chrissimpkins On Windows I think I have used size 10 and on Debian I used 72 dpi and size 14 with anti-alias and full hinting.

**Comment by chrissimpkins** [comment]
@ceving thanks. I will try to make a test build that we can try before we push it in the release.

**Comment by chrissimpkins** [comment]
I addressed this as of the current test build (v2.014).  This will be pushed in the next release version.  If you'd like to give the new files a try to confirm that the alignment is correct, they are available in #111

**Comment by chrissimpkins** [comment]
These changes are now available in the v2.015 release.  Thank you very much for the issue report.  Please feel free to reopen if this did not address the problem for you.
