### ISSUE TITLE
Italic capital 'A' and underscore bugs

### ISSUE THREAD

**Issue by Paul-v-H** [chrissimpkins/Hack#63]
In italic, the capital 'A' is displayed as  a tilde ('~') and the underscore is displayed on top of the line instead of on the bottom.

(I am using the font in IntelliJ)

**Comment by Estigy** [comment]
This has already been reported as #60 ;-)

**Comment by Paul-v-H** [comment]
With a very different title, so I missed it. Sorry.

Nice font though! ;-)

**Comment by chrissimpkins** [comment]
No worries.  Sorry for the troubles. I am contacting JetBrains today.  Lots of issues going on with this Java renderer that will require their feedback to sort out.
