### ISSUE TITLE
Uppercase 'A' shows as '~' in bold italic

### ISSUE THREAD

**Issue by mdesmons** [chrissimpkins/Hack#71]
I'm using the Hack font in the IntelliJ IDE, and when using bold + italic, the letter 'A' shows as '~'.
Font used: Hack, 12 points.
OS : Windows 7

If using only bold, or only italic everything's fine, it's just the combination of both. Other letters seem fine.

Please see screenshot, hope this illustrates. The constant here is called "QUALIFIER" but shows as "QU~LIFIER":

![image](https://cloud.githubusercontent.com/assets/10752949/9625236/dea0bbe0-5197-11e5-9f39-54248821b024.png)

**Comment by mdesmons** [comment]
Sorry, closing it as it's duplicate of issue #60

**Comment by chrissimpkins** [comment]
thanks!
