### ISSUE TITLE
vim airline and zsh paradox look ugly

### ISSUE THREAD

**Issue by m42e** [chrissimpkins/Hack#72]
With the Hack font in mintty and Font Size 8, the arrows of vim airline and zsh paradox theme look very ugly. I'm using Cygwin with mintty on Windows 7 and the ttf font.

Am I doing something wrong?

Thank you very much.
Best Regards,
Matthias

![vim](https://cloud.githubusercontent.com/assets/2410802/9630354/0e6dea1e-517a-11e5-9d5d-8bb3c6d3caee.png)
![zshparadox](https://cloud.githubusercontent.com/assets/2410802/9630355/0e74bd26-517a-11e5-9248-f779207df57b.png)

**Comment by chrissimpkins** [comment]
Join us over in #33 to discuss this.  Working on spacing issues with the Powerline glyph set.  Will close this issue as a duplicate.  Feel free to reopen if this is not the case.

**Comment by f911** [comment]
I have met the same question
