### ISSUE TITLE
[OS X] [Emacs] Spacing issue

### ISSUE THREAD

**Issue by ob** [chrissimpkins/Hack#73]
Not sure if this is related to https://github.com/chrissimpkins/Hack/issues/38, but I see spaces taking a variable amount of space in Emacs on OS X. 

This is Hack (shown using whitespace-mode to highlight the spaces):

<img width="53" alt="screen shot 2015-09-02 at 9 02 38 am" src="https://cloud.githubusercontent.com/assets/4950/9636645/67fb1c74-5151-11e5-8d0f-a6baf69bb9bf.png">

This is exactly the same, using Inconsolata:

<img width="42" alt="screen shot 2015-09-02 at 9 03 22 am" src="https://cloud.githubusercontent.com/assets/4950/9636663/7d0c856c-5151-11e5-9be7-3a3ea0f4911b.png">

Note the misalignment of the pipe ("|") character. It happens with any letter, it doesn't have to be 'X'.

**Comment by chrissimpkins** [comment]
There is a bug in v2.010 with the whitespace indicator (middle dot).  Mind trying these files?

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by ob** [comment]
Yeah, those work! Thanks!

**Comment by chrissimpkins** [comment]
Great! I will push these fixes later this week.  Thanks for the report.
