### ISSUE TITLE
Windows 7 Enterprise: unable to install correctly

### ISSUE THREAD

**Issue by TrevorHayes** [chrissimpkins/Hack#75]
I've tried installing both the ttf and otf files into my copy of Windows 7 Enterprise SP1 and while Windows will install either set of files in both cases the font family shows up with only the "regular" and "bold" fonts. If I use the font in an application, italics do not work. If I delete those two fonts then one of the oblique fonts will appear as the only font and then if I delete that the other oblique font will appear.

**Comment by chrissimpkins** [comment]
Being discussed in #50.  Will repost this to that thread.  Come on over and join us as we work on this.
