### ISSUE TITLE
[JetBrains, IntelliJ, Linux] Font antialiasing/appearance problems in JetBrains editors on Linux

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#76]
Helpful thread in the JetBrains issue tracker:

https://youtrack.jetbrains.com/issue/IDEA-57233

Scroll to the most recent messages for a current set of recommendations.

**Comment by sheppe** [comment]
I'm also seeing issues in WebStorm and RubyMine (both based on JetBrains IntelliJ) on Windows 8.1.

**Comment by chrissimpkins** [comment]
Any more details on the issue that you are having?


—
Chris

**Comment by sheppe** [comment]
As I mentioned in the edit of my post, the release candidate download found in https://github.com/chrissimpkins/Hack/issues/60 fixes the issue.

**Comment by chrissimpkins** [comment]
apologies.  read it by email where edit was not available.
