### ISSUE TITLE
[IntelliJ, Windows 8.1] Underscore flickers and lower case g cuts off

### ISSUE THREAD

**Issue by Tiim** [chrissimpkins/Hack#77]
I'm using Hack in IntelliJ IDEA and the underscores seem to flicker from time to time
making them seem like a space. The lower case "g" seems to flicker between being sown and slightly cut off on the bottom.  

![screenshot 2015-09-03 10 38 51](https://cloud.githubusercontent.com/assets/1063187/9654153/18ac8030-5229-11e5-992a-a1ae3c5017bd.png)

1. There should be an underscore
2. The g got cut off

**Comment by chrissimpkins** [comment]
I think that this may be the same issue that was reported in #45.  If this is correct, do you mind closing this one and we will discuss in the original report?  Feel free to add this information to that thread and we will need to know whether you are using the otf or the ttf files.  If you are using the otf files, please try this new ttf build:

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

**Comment by Tiim** [comment]
You are right, this is a duplicate. I did not find the other issue on my quick search through the Issue Tracker. I was using v2.010 and will try your version now.

**Comment by chrissimpkins** [comment]
no worries.  let me know how it turns out
