### ISSUE TITLE
[Previously reported in #27 - Fix available] Hack does not render &middot;

### ISSUE THREAD

**Issue by alexandrudima** [chrissimpkins/Hack#78]
I really like this font and I've already abandoned 'Input' in favor of it :).

VSCode uses &amp;middot; to render leading/trailing whitespace and Hack does not render anything for this character.

So with Hack I get this:

![image](https://cloud.githubusercontent.com/assets/5047891/9659463/0263fdbc-5251-11e5-8f1e-8cac2e2f043a.png)

While with Consolas I get this:

![image](https://cloud.githubusercontent.com/assets/5047891/9659514/45e40a1e-5251-11e5-9917-e48e64e85a04.png)

**Comment by chrissimpkins** [comment]
Thanks Alexandru.  I'm glad to hear that it is working for you.  This is a definite bug with middle dot glyph that is fixed as of the v2.011 test release.  I will be pushing this release to the master branch later in the week.  You can find the new files in #27.  Will leave this open until you confirm that these files fix your issue.

**Comment by andrewconnell** [comment]
:+1:

**Comment by alexandrudima** [comment]
:+1: Thanks a lot!

**Comment by chrissimpkins** [comment]
No problem.  Sorry for the troubles.
