### ISSUE TITLE
qrencode -t ANSIUTF8 produces unuseable output [U+2588]

### ISSUE THREAD

**Issue by m42e** [chrissimpkins/Hack#81]
Hi,

Another issue with Hack. Using qrencode with ANSIUTF8 output format does not work. Seems the blocks are not compatible.

<img width="304" alt="bildschirmfoto 2015-09-03 um 20 16 06" src="https://cloud.githubusercontent.com/assets/2410802/9666817/a67e874c-5278-11e5-85ee-030aa6849de7.png">

What I expected:

<img width="307" alt="bildschirmfoto 2015-09-03 um 20 44 03" src="https://cloud.githubusercontent.com/assets/2410802/9667526/9903998c-527c-11e5-815d-7d1152696e47.png">

Thanks

**Comment by m42e** [comment]
Maybe he dump output is useful?

```
0000000 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
0000010 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000020 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000030 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
0000040 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000050 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000060 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
0000070 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96 88 e2
0000080 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000090 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
00000a0 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
00000b0 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
00000c0 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
00000d0 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
00000e0 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
00000f0 88 e2 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96
0000100 88 e2 96 88 20 e2 96 84 e2 96 84 e2 96 84 e2 96
0000110 84 e2 96 84 20 e2 96 88 e2 96 80 e2 96 80 20 e2
0000120 96 88 e2 96 88 e2 96 88 e2 96 80 e2 96 84 e2 96
0000130 84 e2 96 84 e2 96 88 e2 96 88 e2 96 84 e2 96 80
0000140 20 20 e2 96 88 e2 96 88 20 e2 96 84 e2 96 84 e2
0000150 96 84 e2 96 84 e2 96 84 20 e2 96 88 e2 96 88 e2
0000160 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96 88 e2
0000170 96 88 20 e2 96 88 20 20 20 e2 96 88 20 e2 96 88
0000180 e2 96 84 e2 96 80 e2 96 88 e2 96 88 e2 96 80 e2
0000190 96 84 e2 96 84 e2 96 80 20 e2 96 80 20 e2 96 80
00001a0 e2 96 80 e2 96 88 e2 96 88 20 20 e2 96 88 20 e2
00001b0 96 88 20 20 20 e2 96 88 20 e2 96 88 e2 96 88 e2
00001c0 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96 88 e2
00001d0 96 88 20 e2 96 88 e2 96 84 e2 96 84 e2 96 84 e2
00001e0 96 88 20 e2 96 88 20 e2 96 84 20 e2 96 88 20 20
00001f0 e2 96 80 e2 96 88 20 e2 96 88 e2 96 80 20 e2 96
0000200 84 e2 96 88 20 e2 96 84 e2 96 84 e2 96 88 20 e2
0000210 96 88 e2 96 84 e2 96 84 e2 96 84 e2 96 88 20 e2
0000220 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96 88 e2
0000230 96 88 e2 96 88 e2 96 88 e2 96 84 e2 96 84 e2 96
0000240 84 e2 96 84 e2 96 84 e2 96 84 e2 96 84 e2 96 88
0000250 20 e2 96 88 20 e2 96 80 e2 96 84 e2 96 88 e2 96
0000260 84 e2 96 80 20 e2 96 88 e2 96 84 e2 96 88 20 e2
0000270 96 80 20 e2 96 88 e2 96 84 e2 96 88 e2 96 84 e2
0000280 96 84 e2 96 84 e2 96 84 e2 96 84 e2 96 84 e2 96
0000290 84 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96
00002a0 88 e2 96 88 e2 96 88 e2 96 88 20 20 e2 96 88 20
00002b0 e2 96 88 e2 96 80 e2 96 84 e2 96 84 e2 96 88 e2
00002c0 96 80 e2 96 88 20 20 e2 96 84 e2 96 88 e2 96 88
00002d0 e2 96 84 e2 96 84 e2 96 88 e2 96 88 e2 96 80 20
00002e0 20 e2 96 84 e2 96 88 e2 96 80 20 e2 96 84 e2 96
00002f0 84 e2 96 80 e2 96 84 e2 96 84 e2 96 80 e2 96 88
0000300 e2 96 88 e2 96 88 e2 96 88 0a e2 96 88 e2 96 88
0000310 e2 96 88 e2 96 88 e2 96 84 e2 96 88 20 e2 96 80
0000320 20 e2 96 80 e2 96 84 e2 96 84 20 e2 96 80 e2 96
0000330 80 20 20 20 20 20 e2 96 84 e2 96 88 e2 96 84 20
0000340 e2 96 84 e2 96 80 e2 96 84 e2 96 88 e2 96 88 e2
0000350 96 84 e2 96 84 20 e2 96 80 e2 96 84 e2 96 88 e2
0000360 96 80 20 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a
0000370 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 80 e2
0000380 96 84 e2 96 80 e2 96 88 e2 96 84 e2 96 80 e2 96
0000390 84 e2 96 88 e2 96 88 e2 96 88 e2 96 84 20 e2 96
00003a0 88 e2 96 80 e2 96 84 e2 96 84 e2 96 80 e2 96 80
00003b0 e2 96 80 e2 96 80 e2 96 88 20 e2 96 80 e2 96 84
00003c0 e2 96 88 e2 96 84 20 e2 96 88 e2 96 80 20 e2 96
00003d0 80 e2 96 80 20 e2 96 88 e2 96 88 e2 96 88 e2 96
00003e0 88 0a e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
00003f0 88 e2 96 84 20 20 e2 96 88 e2 96 88 e2 96 84 e2
0000400 96 84 20 e2 96 88 e2 96 80 20 e2 96 88 e2 96 84
0000410 e2 96 84 20 e2 96 84 20 e2 96 84 e2 96 88 e2 96
0000420 84 e2 96 80 e2 96 80 e2 96 84 e2 96 80 e2 96 84
0000430 e2 96 88 e2 96 88 e2 96 80 20 e2 96 88 20 e2 96
0000440 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96
0000450 88 e2 96 88 e2 96 88 e2 96 88 e2 96 80 e2 96 80
0000460 20 e2 96 84 e2 96 80 20 e2 96 84 e2 96 80 e2 96
0000470 80 e2 96 88 e2 96 84 e2 96 88 20 20 e2 96 80 e2
0000480 96 80 e2 96 84 20 20 e2 96 84 e2 96 84 e2 96 84
0000490 e2 96 80 20 e2 96 84 e2 96 80 e2 96 84 e2 96 80
00004a0 e2 96 84 e2 96 80 e2 96 80 e2 96 88 e2 96 84 e2
00004b0 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96 88 e2
00004c0 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 80 e2 96
00004d0 80 e2 96 84 e2 96 88 e2 96 80 e2 96 84 e2 96 80
00004e0 20 e2 96 80 e2 96 84 e2 96 84 20 e2 96 88 20 20
00004f0 e2 96 88 e2 96 88 20 e2 96 80 e2 96 88 e2 96 80
0000500 20 e2 96 80 e2 96 80 e2 96 88 20 e2 96 84 e2 96
0000510 88 20 e2 96 88 e2 96 84 e2 96 84 e2 96 88 e2 96
0000520 88 e2 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96
0000530 88 e2 96 88 e2 96 84 e2 96 84 e2 96 80 e2 96 80
0000540 20 20 e2 96 84 e2 96 88 e2 96 88 e2 96 84 e2 96
0000550 84 e2 96 80 e2 96 88 e2 96 88 e2 96 80 e2 96 80
0000560 20 e2 96 84 e2 96 84 e2 96 88 e2 96 84 20 e2 96
0000570 88 e2 96 84 20 20 e2 96 80 e2 96 88 e2 96 88 e2
0000580 96 84 e2 96 80 e2 96 84 e2 96 80 e2 96 88 e2 96
0000590 88 e2 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96
00005a0 88 e2 96 88 e2 96 84 20 20 e2 96 80 e2 96 80 20
00005b0 e2 96 84 e2 96 88 e2 96 80 e2 96 80 e2 96 80 e2
00005c0 96 88 e2 96 88 e2 96 88 e2 96 80 20 e2 96 88 e2
00005d0 96 80 e2 96 80 e2 96 84 e2 96 84 20 e2 96 84 e2
00005e0 96 88 20 e2 96 88 e2 96 88 e2 96 84 e2 96 88 20
00005f0 e2 96 88 e2 96 80 20 e2 96 88 e2 96 88 e2 96 88
0000600 e2 96 88 0a e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000610 e2 96 84 e2 96 88 e2 96 84 e2 96 88 e2 96 84 e2
0000620 96 84 e2 96 84 e2 96 88 e2 96 80 20 20 e2 96 80
0000630 20 e2 96 88 e2 96 88 20 20 e2 96 88 e2 96 84 e2
0000640 96 80 e2 96 88 20 e2 96 84 e2 96 80 20 e2 96 84
0000650 e2 96 84 e2 96 84 20 e2 96 84 e2 96 88 e2 96 88
0000660 e2 96 80 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a
0000670 e2 96 88 e2 96 88 e2 96 88 e2 96 88 20 e2 96 84
0000680 e2 96 84 e2 96 84 e2 96 84 e2 96 84 20 e2 96 88
0000690 e2 96 84 e2 96 84 e2 96 80 e2 96 88 20 e2 96 80
00006a0 e2 96 80 20 e2 96 88 e2 96 84 20 e2 96 80 20 e2
00006b0 96 80 e2 96 80 e2 96 88 20 e2 96 88 e2 96 84 e2
00006c0 96 88 20 e2 96 84 e2 96 88 20 e2 96 80 e2 96 88
00006d0 e2 96 88 e2 96 88 e2 96 88 0a e2 96 88 e2 96 88
00006e0 e2 96 88 e2 96 88 20 e2 96 88 20 20 20 e2 96 88
00006f0 20 e2 96 88 e2 96 80 20 e2 96 84 e2 96 84 e2 96
0000700 88 e2 96 84 e2 96 84 e2 96 80 e2 96 84 e2 96 80
0000710 e2 96 84 e2 96 84 e2 96 84 20 e2 96 80 e2 96 88
0000720 20 e2 96 84 20 20 20 e2 96 88 e2 96 80 20 e2 96
0000730 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96
0000740 88 e2 96 88 e2 96 88 e2 96 88 20 e2 96 88 e2 96
0000750 84 e2 96 84 e2 96 84 e2 96 88 20 e2 96 88 e2 96
0000760 80 20 20 e2 96 80 e2 96 88 20 e2 96 88 20 e2 96
0000770 80 e2 96 88 e2 96 88 e2 96 80 20 e2 96 80 e2 96
0000780 84 20 e2 96 80 e2 96 84 e2 96 80 20 20 e2 96 84
0000790 e2 96 84 e2 96 88 e2 96 84 e2 96 88 e2 96 88 e2
00007a0 96 88 e2 96 88 0a e2 96 88 e2 96 88 e2 96 88 e2
00007b0 96 88 e2 96 84 e2 96 84 e2 96 84 e2 96 84 e2 96
00007c0 84 e2 96 84 e2 96 84 e2 96 88 e2 96 84 e2 96 88
00007d0 e2 96 84 e2 96 84 e2 96 84 e2 96 88 e2 96 84 e2
00007e0 96 84 e2 96 88 e2 96 84 e2 96 88 e2 96 88 e2 96
00007f0 88 e2 96 84 e2 96 88 e2 96 84 e2 96 84 e2 96 84
0000800 e2 96 88 e2 96 84 e2 96 84 e2 96 84 e2 96 88 e2
0000810 96 84 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000820 88 0a e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000830 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000840 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
0000850 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000860 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000870 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
0000880 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000890 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 0a e2 96
00008a0 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
00008b0 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
00008c0 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
00008d0 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
00008e0 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2
00008f0 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96
0000900 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88 e2 96 88
0000910 e2 96 88 e2 96 88 e2 96 88 0a                  
000091a
```

**Comment by chrissimpkins** [comment]
Can you provide the unicode range that this application is using to produce these?

**Comment by m42e** [comment]
Only these three:
* 0x2588
* 0x2584
* 0x2580

**Comment by chrissimpkins** [comment]
Mind testing this again with the new test build (v2.014).  I updated the vertical metrics to be consistent with that in DejaVu Sans Mono/Bitstream Vera Sans Mono/Menlo.  This will likely (begin to) address this issue.

Test files available in #111

**Comment by chrissimpkins** [comment]
Closing as no longer interested.  Please feel free to reopen if/when you have time to test this.

**Comment by m42e** [comment]
Sorry, didn't get a notification. I've tried it, works, with italic, bold and italic bold, but not with regular.

**Comment by jublo** [comment]
@m42e Consider clicking the “Subscribe” button in this issue’s sidebar.

**Comment by chrissimpkins** [comment]
@m42e Can you let us know what you are seeing in the regular set?  Will need to know how the spacing is off to address the alignment.  Images would be very helpful if possible.

**Comment by m42e** [comment]
@jublo I'm subscribed, but somehow missed it.

Regular:
<img width="304" alt="bildschirmfoto 2015-09-03 um 20 16 06" src="https://cloud.githubusercontent.com/assets/2410802/10268915/2145baa2-6ac7-11e5-8a99-453084ff73d8.png">
Bold:
<img width="307" alt="bildschirmfoto 2015-09-03 um 20 44 03" src="https://cloud.githubusercontent.com/assets/2410802/10268916/2168e1ee-6ac7-11e5-8115-afccc01a0d9e.png">

**Comment by chrissimpkins** [comment]
>  I'm subscribed, but somehow missed it.
No worries.  No rush.  

It seems that the rectangular box glyph width is completely different in the regular set than it is for the square boxes that are positioned on the baseline.

**Comment by m42e** [comment]
You can also see the issue, when opening http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt with Hack. At the bottom, there should be increasing bars, but the last element is much smaller than the others.

**Comment by chrissimpkins** [comment]
Any license on that specimen file? That would be incredibly useful for testing.

**Comment by m42e** [comment]
I don't know, it is provided by http://www.cl.cam.ac.uk/%7Emgk25/ but there is no license provided.

**Comment by chrissimpkins** [comment]
All of these need some work...

![box glyphs](https://cloud.githubusercontent.com/assets/4249591/10269542/1cfc3660-6aa9-11e5-8fcd-6e69171f1a00.png)

**Comment by chrissimpkins** [comment]
That last box on the lower right corner must be your problem

**Comment by m42e** [comment]
Exactly. If I look close you're right, there might be some more issues.

**Comment by chrissimpkins** [comment]
> I don't know, it is provided by http://www.cl.cam.ac.uk/%7Emgk25/ but there is no license provided. 
Thank you.  We will create something similar to take a look at these glyphs

**Comment by chrissimpkins** [comment]
We are modifying the block element glyphs as part of the v2.019 release.  Work in progress.  May need you to take a look at these qrencode displays again once available if you are free to do so.

**Comment by m42e** [comment]
I'll have a look

**Comment by chrissimpkins** [comment]
@m42e Matthias, can you provide an example of a typeface that does work here?  I took a look at the spacing in Source Code Pro and the alignment appears to be further off for these glyphs than what is going on in Hack.  I'd be interested in taking a look at the metrics on one that does work for you.  I've made changes to the glyphs involved here and they will be released in the upcoming v2.019, likely later this week.

**Comment by m42e** [comment]
Ubuntu Mono for Powerline works. It has some space but it is recognized by qr scanners. 
monofur for powerline works as well. with horizontal and vertical spaces.
PT Mono also looks good, except for slight spaces.

Hope this helps you. I really appreciate your hard work.

**Comment by chrissimpkins** [comment]
Thank you very much Matthias.  I will take a look.

**Comment by chrissimpkins** [comment]
If you happen to have some time, could I bother you to give this new build a try?  

https://github.com/chrissimpkins/Hack/tree/development/postbuild_processing/posthinted_builds

The regular set in this build includes glyph modifications that should be getting us closer to where we need to be with this issue.

**Comment by m42e** [comment]
Looks good to me :) :+1: Thank you very much.

**Comment by chrissimpkins** [comment]
vertical spacing OK?

**Comment by m42e** [comment]
Yes, ist a very small line, but this is same for all the other fonts I mentioned above.

**Comment by m42e** [comment]
<img width="212" alt="bildschirmfoto 2015-12-16 um 20 13 53" src="https://cloud.githubusercontent.com/assets/2410802/11851184/9253ab52-a431-11e5-9d41-985da8226d51.png">

**Comment by chrissimpkins** [comment]
Have you come across a font that does not have the lines in between?  I am planning to do some work on the hinting to see if I can narrow that further.

**Comment by Defman21** [comment]
It looks fine for me btw.
Using Hack Regular 11pt, Ubuntu 15.10 with 1.00 scaling factor.
![doge](http://i.imgur.com/uY3LRnl.png)

**Comment by chrissimpkins** [comment]
@Defman21 thanks for that screenshot.  I really appreciate it.  There are definitely size dependent spacing issues that are a result of the hinting.  I think that I can get closer to the image appearance that you display across our target font sizes with a bit of manual hinting work.

**Comment by chrissimpkins** [comment]
These fixes are now available in the v2.019 release. Thanks for this issue report and for all of your help with testing here @m42e + @Defman21

**Comment by Defman21** [comment]
You're welcome, thanks for your awesome font!

**Comment by chrissimpkins** [comment]
@Defman21 :+1:
