### ISSUE TITLE
[Powerline] Branch glyph not working with bold font variant

### ISSUE THREAD

**Issue by PatTheMav** [chrissimpkins/Hack#86]
I have been using the branch glyph from Powerline for my bash prompt's git status. Right now I'm using ANSI codes to make this glyph use "bold" font weight, but when using Hack as my Terminal window font, the glyph is not displayed properly.

When deactivating bold fonts for terminal, the correct glyph appears. So it looks like the bold font variant does not support the powerline glyphs.

**Comment by chrissimpkins** [comment]
That is correct.  The Powerline glyphs are only included in the regular set at the moment.  Rather than hacking the display of the glyph, it may be better to modify the glyph itself so that it has the proper weighting.  Want to join us in #33?  We are trying to improve the Powerline glyphs in that thread.

**Comment by PatTheMav** [comment]
Well you are right that giving the glyph the correct weights in the normal font should also be a priority (which would allow me to use the non-bold variant in my prompt), having the choice to use a higher font weight for styling would be appreciated (I used Menlo-for-Powerline so far).

**Comment by chrissimpkins** [comment]
Do you change the styling for any of the other Powerline glyphs?

**Comment by PatTheMav** [comment]
So far I'm only using the branch glyph in my prompt, so I'd be totally fine with the "normal" variant being a bit "bolder" so to speak.

**Comment by chrissimpkins** [comment]
Got it.  Will you please post a screenshot that demonstrates the weight that you are using and provide your platform and terminal application?  We've come across some differences in rendering in #33.

**Comment by PatTheMav** [comment]
Sure thing:

* Font weight: Hack Bold
* Platform: OSX El Capitan 10.11 Beta (15A278b)
* Terminal app: OSX Terminal Version 2.6 (361)

![hack glyph regular weight example](https://cloud.githubusercontent.com/assets/9436503/9694775/fb5df19c-535b-11e5-8628-bddcdf94511a.jpg)
![hack glyph bold weight example](https://cloud.githubusercontent.com/assets/9436503/9694776/fb86e778-535b-11e5-9058-81ff015da9ae.jpg)

**Comment by chrissimpkins** [comment]
Sorry, I meant can you display it with a set that shows the glyph with the weight that looks good to you?  I'm interested in the appearance that you are after with that glyph.

**Comment by PatTheMav** [comment]
Sure thing - here is the look I'm "coming from" so to speak. It's "Menlo for Powerline" with regular font weight for strings and bold font weight for the glyph and all brackets:

![menlo for powerline glyph example](https://cloud.githubusercontent.com/assets/9436503/9699875/002cbbf0-53f1-11e5-8238-fef1b7458895.jpg)

**Comment by jszakmeister** [comment]
FWIW, I'd like to see bold variants available too--though more to just have the symbol than a heavier weight.  I have the current line number bolded in Vim/MacVim with the old Powerline.  With Hack, I get the following in MacVim:

<img width="200" alt="screen shot 2015-09-10 at 5 41 20 am" src="https://cloud.githubusercontent.com/assets/448087/9785213/964006c0-577e-11e5-8050-df778fb53e5a.png">

With a patched DejaVu Sans Mono font I get:

<img width="284" alt="screen shot 2015-09-10 at 5 40 26 am" src="https://cloud.githubusercontent.com/assets/448087/9785194/78e85a1e-577e-11e5-8da1-d4656563ff88.png">

**Comment by kaicataldo** [comment]
Seeing the same thing as @jszakmeister. Love the font, @chrissimpkins - thanks for all your work on it!

**Comment by chrissimpkins** [comment]
@kaicataldo Thanks for your feedback Kai.  I'll make sure that we address the Powerline glyphs in an upcoming release.  Apologize for the delay.  We've been tackling a number of other issues.

**Comment by kaicataldo** [comment]
No need to apologize! Love the font - it's my go-to font on all my machines now :+1:

**Comment by chrissimpkins** [comment]
Great to hear that!

**Comment by chrissimpkins** [comment]
Here is a set of new test builds that include the current regular set Powerline glyphs in the bold set.  These should allow you to view the proper glyphs (though not the proper weight) until I can create actual bold versions of the glyphs to address this issue.  These will show up as Version 2.020;DEV-02172016.

https://github.com/chrissimpkins/Hack/tree/development/build/test_builds/DEV02172016 

Let me know if you come across any problems.

**Comment by kaicataldo** [comment]
Awesome :+1: I honestly don't know if a heavier weight version of the symbols is necessary. I think it makes more sense to leave them as is, but just to include them.

**Comment by chrissimpkins** [comment]
Do they show up for you now?

Anyone else in this thread have strong opinions about the weight?

**Comment by PatTheMav** [comment]
I'll check out the new version when I get home, but for starters I think that the normal weights being available in the bold version is good enough for now. 

I remember only the branch symbol being a great candidate for a higher don't weight.

**Comment by chrissimpkins** [comment]
more than happy to work on bolds if this is felt to be important.  I don't use these in bold and will defer to the judgment of those who do.  thanks in advance for having a look.

**Comment by PatTheMav** [comment]
Tried out the DEV versions, worked fine here and to be honest I'm actually quite happy with the weight of the glyphs the way they are. But this simplifies my prompt's color commands as I don't need to reset the bold font weight around the glyphs anymore.. 😉

**Comment by chrissimpkins** [comment]
@PatTheMav :+1:  great!

**Comment by kaicataldo** [comment]
I probably won't be able to try this out until tomorrow, but looking forward to it. Thanks for being so responsive!

**Comment by chrissimpkins** [comment]
@kaicataldo no worries at all.  there is no rush.  hope it works for you.

**Comment by chrissimpkins** [comment]
The Powerline glyphs are included in all font variants as of the v2.020 release which is now available.  Thanks to all for testing here.  Given that the consensus seems to be that the regular weight works fine, we will hold off on a heavier weight for the bold set.  Feel free to reopen if others feel differently.  Thanks to all for the testing.  Enjoy!
