### ISSUE TITLE
Remove svg Web Fonts? (input requested)

### ISSUE THREAD

**Issue by chrissimpkins** [chrissimpkins/Hack#88]
I received a pull request from @zachleat to remove the svg web fonts because Chrome 37 & Opera 24 now support DirectWrite.  

He referenced [this thread on Twitter where this issue was discussed](https://twitter.com/bram_stein/status/506812176212824066).

I'm opening this issue up for comments before we merge the PR.  Does anyone feel the need to maintain these files as part of our release builds and in the webfont packages that are available on jsdelivr (and soon to be on cdnjs)?

Thanks for your feedback.

**Comment by txtsd** [comment]
Might as well. SVG is outdated and isn't Opentype forward-compatible.

**Comment by chrissimpkins** [comment]
@txtsd thanks for the feedback

**Comment by chrissimpkins** [comment]
Leaving in the set for now.
