### ISSUE TITLE
Provide guidance about License compatability

### ISSUE THREAD

**Issue by kittylyst** [chrissimpkins/Hack#89]
The current License is rather obscure, from a non-font person viewpoint. Could you consider creating a document that indicates whether Hack font artefacts can be included in with other, differently-licensed code?

For example, can Hack be included with GPL software? Apache-licensed? Proprietary?

**Comment by chrissimpkins** [comment]
Short answer is that the intent and spirit of the licensing is to permit many of the above redistribution/embedding applications of the typeface, including commercial/proprietary uses.

I am in discussions with a SIL representative about the modifications that were made to the SIL license for this project (with the intent to maintain the terms of the Bitstream license that include restrictions against use of "Bitstream" and "Vera" in the names of derived fonts) and will have more guidance once we resolve these issues.

Guidance from SIL about how the language in the **unmodified version** of the SIL OFL v1.1 license addresses the FSF freedoms, DFSG compatibility, and OSD compatibility in the Details and Rationale section of this page on the SIL site: 

http://scripts.sil.org/OFL
