### ISSUE TITLE
VIM Arrows are a little bit too short (in height)

### ISSUE THREAD

**Issue by Fale** [chrissimpkins/Hack#90]
See snapshot
![snapshot1](https://cloud.githubusercontent.com/assets/77888/9706058/9830a018-54d9-11e5-9c00-86a8f0295e88.png)

**Comment by chrissimpkins** [comment]
This is Powerline?

**Comment by Fale** [comment]
It's vim-airline (https://github.com/bling/vim-airline)

**Comment by chrissimpkins** [comment]
And does this use the Powerline glyphs that are mapped to the Unicode PUA?

**Comment by Fale** [comment]
From vim-airline doc: "For the nice looking powerline symbols to appear, you will need to install a patched font. Instructions can be found in the official powerline documentation. Prepatched fonts can be found in the powerline-fonts repository." and I can confirm it was working properly with https://github.com/powerline/fonts

**Comment by chrissimpkins** [comment]
Try the new build in #87.  It includes Powerline glyph alignment improvements that we worked on in #33.  It's not quite perfect on all platforms, but much better at this point.

If this addresses your question, will you close this issue and continue any discussion about these Powerline glyphs in #33?

**Comment by Fale** [comment]
Thanks, yes, probably is the same of #33 .

**Comment by chrissimpkins** [comment]
interested in knowing how the new build looks for you if you don't mind providing feedback.
