### ISSUE TITLE
lower case i size 10 looks bold 

### ISSUE THREAD

**Issue by lpdunwell** [chrissimpkins/Hack#91]
different than the actual, lower case i size 10.
confirmed with win 10, notepad++ and IAR EW.
![i](https://cloud.githubusercontent.com/assets/5822148/9710281/134354e4-5539-11e5-9401-4bcf1d963fdc.PNG)

**Comment by chrissimpkins** [comment]
Is this with the otf files?

**Comment by lpdunwell** [comment]
Yes

Chris Simpkins <notifications@github.com> schrieb am Mo., 7. Sep. 2015
13:06:

**Comment by chrissimpkins** [comment]
Try the ttf files on Windows.  It should take care of the problem.  The TrueType instructions should render much better on Windows boxes than the otf hints.

If you don't mind, will you try the new build in #87?  They include a few bug fixes and will be merged into the master branch later today as the current release.

**Comment by lpdunwell** [comment]
oh wow. the ttf looks way better than the otf on windows 10.

**Comment by chrissimpkins** [comment]
Good to hear.  Let me know if you have any issues with it.  OK to close this issue?

**Comment by lpdunwell** [comment]
Great, thanks. Yep.

Cheers

**Comment by chrissimpkins** [comment]
glad it worked!
