### ISSUE TITLE
$ sign is too similar to s at 9

### ISSUE THREAD

**Issue by Fale** [chrissimpkins/Hack#92]
See image 
![snapshot2](https://cloud.githubusercontent.com/assets/77888/9712472/1ddfcace-554b-11e5-8f73-e739033c0182.png)

**Comment by chrissimpkins** [comment]
Can you include your platform, the application where you are using the typeface, and any antialiasing / hinting settings that you are using?

**Comment by schauveau** [comment]
I noticed that too in emacs and xterm (for instance in ttf 10pt with full hinting). Generally speaking, I find that the vertical bar of the $ is a bit too thin in all font sizes. It is fine if there is a lot of contrast (e.g. Black on White) but else it tends to disappear as in the example above.

This is not limited to small fonts. For instance, I do not like the black on white 16pt in the font-specimen page

![hack-dollar](https://cloud.githubusercontent.com/assets/14061306/9715970/d88dd932-5565-11e5-9d0b-3c125c12ef5d.png)

**Comment by chrissimpkins** [comment]
Noted.

**Comment by Fale** [comment]
It seems to me that the + has the same problem.
![snapshot3](https://cloud.githubusercontent.com/assets/77888/9717874/bf372504-5576-11e5-9bb3-f5cfcfae314b.png)

**Comment by chrissimpkins** [comment]
What is your thought about increasing the weight of the entire glyph,  not just the vertical stroke through it?  I did this with characters like the exclamation point (which has a semi bold weight in the regular set) with the intent to make these shapes more apparent.   Something we could try here as well.

**Comment by duud** [comment]
Please don't do this, it will decrease the readability for small sizes.

**Comment by chrissimpkins** [comment]
@duud how is the vertical stroke rendering for you?

**Comment by duud** [comment]
It's pretty thin but a have absolutely no difficulty to distinguish it from 'S'.

**Comment by chrissimpkins** [comment]
@duud OK thank you.

**Comment by alerque** [comment]
I think I'd be in favor of a bit more weight on the bar as well. I've caught myself looking back and squinting if the color contrast is too low to make sure I got the right character. At the same font size and context other glyphs are distinguished with much less conscious thought. It's not that I can't see the difference when I look, but the $ is not distinct enough from S to always catch the difference subconsciously.

**Comment by duud** [comment]
I'm also for increasing the weight of the bar.
Not for the whole glyph.

**Comment by chrissimpkins** [comment]
Got it.  Thank you for the input.

**Comment by jublo** [comment]
How about this?

![dollar-bar](https://cloud.githubusercontent.com/assets/6348321/10267592/69383d30-6a9a-11e5-9863-ddb01e082182.png)

**Comment by chrissimpkins** [comment]
@jublo Looks good.  Let's move forward with the change and we will test it at smaller sizes.  The concern has been over the width of the vertical stem when taken to small text sizes (becomes hairline).  This will be a good one to view in an editor on a development build after we hint.

**Comment by chrissimpkins** [comment]
I am going to give this a try in the next development build to see how it works.  I took a look through a number of different `$` designs and came across a typeface that included wider strokes above and below the main `S` portion of the glyph with a narrower stroke through the S component of the glyph.  It doesn't look 'right' at large sizes like that displayed below, but at smaller text sizes this may achieve the distinction between the `S` and `$`, *and* render better than a glyph with a uniform thick vertical bar through it (particularly in the bold sets).  Many fonts just use the thick vertical strokes above and below without a stroke through the S.  Another consideration, though I think that I like the top to bottom stroke myself.

<img width="279" alt="dollar-glyph" src="https://cloud.githubusercontent.com/assets/4249591/10384092/1c01ee58-6e05-11e5-8a42-a4287941cbc1.png">

Will be interested in your feedback when we have a build to test.

**Comment by chrissimpkins** [comment]
The new dollar glyph is available for testing in the v2.016 test build of the ttf files.  You can try download them here:

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by chrissimpkins** [comment]
Last chance to comment on the dollar symbol changes before we push them live as part of the v2.017 release this week.  See the test builds in the message above.

**Comment by chrissimpkins** [comment]
These changes were included in the v2.017 release
