### ISSUE TITLE
ttfs dones int stall in windows

### ISSUE THREAD

**Issue by teknopaul** [chrissimpkins/Hack#93]
Trying to install the 4 ttf files in the zip does not work in Windows.

It tries to replace "Hack" with each on eyou isntall so you only end up with one of the four.

This means Hack cant be used in eclipse.  you need one font "Hack" which supports bold and italic and italic&bold.

**Comment by chrissimpkins** [comment]
There is a fix for this in #87.  I hope to have this in the master branch later today.  Let me know if this does not work.  Thanks for the report.

**Comment by chrissimpkins** [comment]
This fix is now live in the v2.013 release.  I will close this issue.  Feel free to reopen if the new build did not address this problem.  Thanks for reporting it!
