### ISSUE TITLE
2.013 OTF doesn't render in OSX Font book

### ISSUE THREAD

**Issue by talios** [chrissimpkins/Hack#94]
Just downloaded the OFTs and added them to the OSX FontBook and I see that the regular doesn't render.  The TTF's work fine however...

<img width="791" alt="hack-oft-2013" src="https://cloud.githubusercontent.com/assets/19093/9723865/f3682b6c-561f-11e5-8052-7587174e09c2.png">

**Comment by talios** [comment]
Weird - just tried reinstalling the OFTs again and now they work/show correctly. Strange.

**Comment by chrissimpkins** [comment]
I validated both build types on OS X.  Does the font display in editors?

**Comment by chrissimpkins** [comment]
> Weird - just tried reinstalling the OFTs again and now they work/show correctly. 

Was this an initial Hack install or did you delete a prior version?

**Comment by talios** [comment]
I had a prior version installed and had deleted it from FontBook just prior to adding it.  Everything seems fine now, it could have just been some bad state in FontBooks preview until being restarted.

**Comment by chrissimpkins** [comment]
Good to hear. Please let me know if you come across any issues.
