### ISSUE TITLE
Underscore too thin, too low, and blurry.

### ISSUE THREAD

**Issue by lluixhi** [chrissimpkins/Hack#98]
I'm using Linux with the OTF version 2.0.13. My editor is NeoVim.
When lines containing the underscore are right above a cursor, or another character that fills a box (cell?), they're almost indistinguishable from spaces.

![underscore](https://cloud.githubusercontent.com/assets/3643824/9829762/1072a00c-58c8-11e5-9a50-351becae6d21.png)

And as said in #97, it looks like the right hand spacing is too big. (They're not centered!)

**Comment by chrissimpkins** [comment]
How does the ttf build render for you?  In general I would recommend it for screen use over the otf files on Linux.

**Comment by lluixhi** [comment]
They're even worse in TTF (though this might partially be the effect of flux)
![2015-09-11_22-09-24](https://cloud.githubusercontent.com/assets/3643824/9829972/112e1b7a-58d2-11e5-88a0-16a3df524fa8.png)

**Comment by chrissimpkins** [comment]
interesting OK.  I will take a look at it.  thanks for reporting this.

**Comment by lluixhi** [comment]
They simply disappeared with the TTF and slight hinting:

![hintslight](https://cloud.githubusercontent.com/assets/3643824/9830019/0260f200-58d4-11e5-9a9a-d69796e823dc.png)

**Comment by lluixhi** [comment]
This is the OTF font with slight hinting:

![2015-09-11_22-34-45](https://cloud.githubusercontent.com/assets/3643824/9830078/8140c7ca-58d5-11e5-9776-a7ccac3c61d2.png)

And with full hinting:

![2015-09-11_22-33-14](https://cloud.githubusercontent.com/assets/3643824/9830067/3da653e0-58d5-11e5-9b48-1ba60791685b.png)

**Comment by chrissimpkins** [comment]
@lluixhi thank you very much for all of these screenshots Aric.  These are very helpful.  I have other issue reports on the tilde glyph.  We will definitely address all of these.  

I will need to look into the box glyphs to see how they align with the underscores.  It looks like this is in part a vertical metrics issue (box glyph too close to the underscore) and a horizontal alignment issue (orientation of underscore to the top of the box glyph) if I understand you correctly.  

The tilde issue is a separate one.  That appears to be related to hinting.  We are working on hinting in the ttf builds in other issue threads.  The otf instruction sets will be addressed once I have a solid ttf build as the TrueType files are more widely used and across most platforms will display better on the screen than the otf builds.  What Linux distro are you on by the way?

**Comment by lluixhi** [comment]
Yes, that's correct.

I'm on Gentoo using Freetype 2.6. I'm using ST, the suckless terminal: http://st.suckless.org/

I think the main reason people on Fedora, Debian, etc. see different results in the font rendering is different distro defaults. I'm pretty sure Fedora turns off the LCD filter (sub pixel rendering) by default due to potential patent issues. Ubuntu and maybe Debian turn it on by default.

Fontconfig/Freetype defaults to Full Hinting and no subpixel rendering, with enabled antialiasing (i believe).. but Ubuntu uses a patched freetype that might change that behaviour.

People using Infinality (a popular patched freetype) are also going to see different results because it tries to mimic rendering on OSX and Windows.

**Comment by chrissimpkins** [comment]
@lluixhi headache source #1 at the moment!  But a problem that we need to deal with.  We will try to make it as usable as possible for everyone.  It is likely to take a combination of changes in glyph shapes / alignment and hinting across the TrueType and PostScript builds.  Fortunately there are developers across a broad range of renderer, editor, platform combinations who have been willing to test.

**Comment by chrissimpkins** [comment]
The position of the underscore is too low in the source and it is off center. I will correct these and plan for this change to be in the next release.  

Let me get some additional feedback about the vertical width of the underscore stroke on other platforms before we introduce this change.

**Comment by chrissimpkins** [comment]
New test build v2.014 is available that addresses this issue.  Vertical metrics were updated, the underscores were made slightly larger in the vertical dimension and they were properly centered.  

Files are available in #111.  Please let me know what you think.

**Comment by chrissimpkins** [comment]
Closing as solved. Please feel free to reopen if the current build does not address your issue.  Thanks for the report.
